# Import Libraries

In [24]:
import pandas as pd
import numpy as np
import h5py
import spacy
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.model_selection import GridSearchCV, cross_val_score
from sklearn.ensemble import RandomForestClassifier
import matplotlib.pyplot as plt
import os
import string as st
import tensorflow as tf
from sklearn.decomposition import PCA, TruncatedSVD
from imblearn.ensemble import BalancedBaggingClassifier
from imblearn.combine import SMOTETomek
from imblearn.under_sampling import NearMiss
from sklearn.tree import DecisionTreeClassifier
from xgboost import XGBClassifier
from collections import Counter
from sklearn.svm import SVC, LinearSVC
from sklearn.naive_bayes import MultinomialNB

import warnings
warnings.filterwarnings('ignore')
pd.set_option('display.max_columns', None)  # Show all columns
pd.set_option('display.max_rows', None)  # Show all rows
pd.set_option('display.max_colwidth', None)  # Show full content in each cell
pd.set_option('display.width', 1000)  # Set max width

# Load spaCy's English model
nlp = spacy.load('en_core_web_sm')

# Linguistic Modules

In [ ]:
def preprocess_text(text):
    # Define interrogative words to KEEP
    interrogatives = {"what", "why", "how", "who", "where", "when", "which", "whom", "whose", "no", "not",
                    "very" ,"too" ,"too" ,"just", "if", "but", "however", "without", "like"}
    custom_stopwords = set(nlp.Defaults.stop_words)
    custom_stopwords -= interrogatives

    doc = nlp(text.lower().strip())  # Lowercase and remove whitespace
    
# Process tokens: lemmatize, filter stopwords/punct/numbers, keep interrogatives
    tokens = [
        token.lemma_ 
        for token in doc 
        if (
            (not token.is_stop or token.text in interrogatives) and  # Keep interrogatives
            not token.is_punct and token.is_alpha  # Remove punctuation, Keep words
        )
    ]

    return ' '.join(tokens)

In [26]:
def extract_linguistic_features(text):
    doc = nlp(text)
    features = {
        'num_verbs': len([token for token in doc if token.pos_ == 'VERB']),
        'num_nouns': len([token for token in doc if token.pos_ == 'NOUN']),
        'sentence_length': len(doc),
        'number_present': any(token.pos_ == 'NUM' for token in doc)
    }
    return features

# Pre-Processing

### Import Data

In [75]:
mapping = {
    'knowledge': 'knowledge',
    'remember': 'knowledge',
    'comprehension': 'comprehension',
    'understand': 'comprehension',
    'application': 'application',
    'apply': 'application',
    'analysis': 'analysis',
    'analyse': 'analysis',
    'evaluation': 'evaluation',
    'evaluate': 'evaluation',
    'synthesis': 'synthesis',
    'create': 'synthesis'
}


# Load dataset
df = pd.DataFrame()
for i in [1,2,3,4,5]:
    q_df = pd.read_csv(os.getcwd().replace('notebook' , 'dataset') + '/dataset' + str(i) + '.csv')
    q_df['dataset_id'] = i
    print(i)
    print(q_df['label'].value_counts())
    df = pd.concat([df , q_df])

# Apply preprocessing
df['label'] = df['label'].str.lower()
df['label'] = df['label'].replace(mapping)

df['processed_question'] = df['question'].apply(preprocess_text)
df['processed_question'] = [''.join(text) for text in df['processed_question']]

1
label
Analysis         100
Knowledge        100
Comprehension    100
Evaluation       100
Synthesis        100
Application      100
Name: count, dtype: int64
2
label
COMPREHENSION    135
APPLY             72
EVALUATE          57
ANALYSIS          56
KNOWLEDGE         50
SYNTHESIS         45
Name: count, dtype: int64
3
label
COMPREHENSION    37
EVALUATE         33
ANALYSIS         30
SYNTHESIS        29
APPLY            29
KNOWLEDGE        23
Name: count, dtype: int64
4
label
Synthesis        29
Knowledge        22
Evaluation       21
Comprehension    20
Analysis         19
Application      15
Name: count, dtype: int64
5
label
COMPREHENSION    669
KNOWLEDGE        149
EVALUATION       107
APPLICATION      100
ANALYSIS          99
SYNTHESIS         76
Name: count, dtype: int64

In [60]:
mapping = {
    'knowledge': 'knowledge',
    'remember': 'knowledge',
    'comprehension': 'comprehension',
    'understand': 'comprehension',
    'application': 'application',
    'apply': 'application',
    'analysis': 'analysis',
    'analyse': 'analysis',
    'evaluation': 'evaluation',
    'evaluate': 'evaluation',
    'synthesis': 'synthesis',
    'create': 'synthesis'
}

# Load dataset
test_df = pd.read_csv(os.getcwd().replace('notebook' , 'dataset') + '/dataset' + str(1) + '.csv')
    
test_df = test_df.reset_index(drop=True)

# Apply preprocessing
test_df['label'] = test_df['label'].str.lower()
test_df['label'] = test_df['label'].replace(mapping)

test_df['processed_question'] = test_df['question'].apply(preprocess_text)
test_df['processed_question'] = [''.join(text) for text in test_df['processed_question']]

## Tokenize

### Vectorization

In [61]:
# token_pattern: words of 2+ word-chars, but not all digits
token_pattern = r"(?u)\b[a-zA-Z]{3,}\b"

vectorizer = TfidfVectorizer(
    min_df= 5 , ngram_range=(1,2), use_idf= True, norm= 'l2', token_pattern= token_pattern
                             )
tfidf = vectorizer.fit_transform(df['processed_question'])

# Convert TF-IDF sparse matrix to DataFrame with appropriate column names
tfidf_df = pd.DataFrame(tfidf.toarray(), columns= vectorizer.get_feature_names_out(), index=df.index)

print('Training Shape: ' + str(tfidf_df.shape))

Training Shape: (722, 340)

In [62]:
test_tfidf = vectorizer.transform(test_df['processed_question'])

# Convert TF-IDF sparse matrix to DataFrame with appropriate column names
test_tfidf_df = pd.DataFrame(test_tfidf.toarray(), columns= vectorizer.get_feature_names_out(), index=test_df.index)

print('Test Shape: ' + str(test_tfidf_df.shape))

Test Shape: (600, 340)

### Label Balancing

In [ ]:
mask = df['dataset_id'].isin([5,6])
to_us_df   = df[mask]
to_keep_df = df[~mask]

to_keep = vectorizer.transform(to_keep_df['processed_question'])
to_us = vectorizer.transform(to_us_df['processed_question'])

df_to_us = pd.DataFrame(
    to_us.toarray(), 
    columns=vectorizer.get_feature_names_out()
)

df_to_keep = pd.DataFrame(
    to_keep.toarray(), 
    columns=vectorizer.get_feature_names_out()
)
df_to_keep['bt_label'] = to_keep_df['label'].values

x , y = df_to_us , to_us_df['label']
x_resampled , y_resampled = NearMiss().fit_resample(x , y)


x_resampled['bt_label'] = y_resampled

df_final = pd.concat([df_to_keep, x_resampled], ignore_index=True)

print(df_final.shape)
print(df_final['bt_label'].value_counts())

x = df_final.drop(columns= 'bt_label')
y = df_final['bt_label']

### Else run below, no need for resampling

In [46]:
x , y = tfidf_df , df['label']
print(x.shape)
print(y.value_counts())

# x , y = x_resampled , y_resampled

(1322, 502)
label
comprehension    292
application      216
evaluation       211
analysis         205
synthesis        203
knowledge        195
Name: count, dtype: int64

# Modelling

## Basic Machine Learning

### Same subset

In [47]:
x_train , x_test , y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=34 , stratify= y)

### Different subset

In [63]:
x_train , y_train = tfidf_df , df['label']
x_test , y_test = test_tfidf , test_df['label']

### Random Forest

In [64]:
params = {
    'n_estimators' : [2 , 5 , 10 , 100, 250 , 500],
    'criterion' : ['gini' , 'entropy'],
    # 'max_depth' : [None , 10 , 100 , 250 , 500]
}
param_search = GridSearchCV(estimator= RandomForestClassifier(), param_grid= params, cv=5, n_jobs= -1, verbose= 2)

param_search.fit(x, y)

cv_results = pd.DataFrame(param_search.cv_results_)
cv_results = cv_results[["mean_test_score", "params"]].head(10).sort_values(by="mean_test_score", ascending=False)

cv_results

Fitting 5 folds for each of 12 candidates, totalling 60 fits
[CV] END .....................criterion=gini, n_estimators=2; total time=   0.0s
[CV] END .....................criterion=gini, n_estimators=2; total time=   0.0s
[CV] END .....................criterion=gini, n_estimators=2; total time=   0.0s
[CV] END .....................criterion=gini, n_estimators=2; total time=   0.0s
[CV] END .....................criterion=gini, n_estimators=2; total time=   0.0s
[CV] END .....................criterion=gini, n_estimators=5; total time=   0.0s
[CV] END .....................criterion=gini, n_estimators=5; total time=   0.0s
[CV] END .....................criterion=gini, n_estimators=5; total time=   0.0s
[CV] END .....................criterion=gini, n_estimators=5; total time=   0.0s
[CV] END .....................criterion=gini, n_estimators=5; total time=   0.0s
[CV] END ....................criterion=gini, n_estimators=10; total time=   0.0s
[CV] END ....................criterion=gini, n_estimators=10; total time=   0.0s
[CV] END ....................criterion=gini, n_estimators=10; total time=   0.0s
[CV] END ....................criterion=gini, n_estimators=10; total time=   0.0s
[CV] END ....................criterion=gini, n_estimators=10; total time=   0.0s
[CV] END ...................criterion=gini, n_estimators=100; total time=   0.3s
[CV] END ...................criterion=gini, n_estimators=100; total time=   0.3s
[CV] END ...................criterion=gini, n_estimators=100; total time=   0.3s
[CV] END ..................criterion=entropy, n_estimators=2; total time=   0.0s
[CV] END ..................criterion=entropy, n_estimators=2; total time=   0.0s
[CV] END ..................criterion=entropy, n_estimators=2; total time=   0.0s
[CV] END ..................criterion=entropy, n_estimators=2; total time=   0.0s
[CV] END ..................criterion=entropy, n_estimators=2; total time=   0.0s
[CV] END ..................criterion=entropy, n_estimators=5; total time=   0.0s
[CV] END ..................criterion=entropy, n_estimators=5; total time=   0.0s
[CV] END ..................criterion=entropy, n_estimators=5; total time=   0.0s
[CV] END ..................criterion=entropy, n_estimators=5; total time=   0.0s
[CV] END ...................criterion=gini, n_estimators=100; total time=   0.4s
[CV] END ..................criterion=entropy, n_estimators=5; total time=   0.0s
[CV] END ...................criterion=gini, n_estimators=100; total time=   0.4s
[CV] END .................criterion=entropy, n_estimators=10; total time=   0.1s
[CV] END .................criterion=entropy, n_estimators=10; total time=   0.0s
[CV] END .................criterion=entropy, n_estimators=10; total time=   0.1s
[CV] END .................criterion=entropy, n_estimators=10; total time=   0.0s
[CV] END .................criterion=entropy, n_estimators=10; total time=   0.1s
[CV] END ................criterion=entropy, n_estimators=100; total time=   0.4s
[CV] END ................criterion=entropy, n_estimators=100; total time=   0.4s
[CV] END ................criterion=entropy, n_estimators=100; total time=   0.4s
[CV] END ...................criterion=gini, n_estimators=250; total time=   0.8s
[CV] END ...................criterion=gini, n_estimators=250; total time=   0.8s
[CV] END ................criterion=entropy, n_estimators=100; total time=   0.4s
[CV] END ...................criterion=gini, n_estimators=250; total time=   0.9s
[CV] END ................criterion=entropy, n_estimators=100; total time=   0.4s
[CV] END ...................criterion=gini, n_estimators=250; total time=   0.9s
[CV] END ................criterion=entropy, n_estimators=250; total time=   0.9s
[CV] END ................criterion=entropy, n_estimators=250; total time=   0.9s
[CV] END ...................criterion=gini, n_estimators=500; total time=   1.7s
[CV] END ...................criterion=gini, n_estimators=500; total time=   1.7s
[CV] END ................criterion=entropy, n_estimators=250; total time=   1.0s
[CV] END ................criterion=entropy, n_estimators=250; total time=   1.0s
[CV] END ...................criterion=gini, n_estimators=250; total time=   0.9s
[CV] END ................criterion=entropy, n_estimators=250; total time=   1.0s
[CV] END ................criterion=entropy, n_estimators=500; total time=   1.5s
[CV] END ...................criterion=gini, n_estimators=500; total time=   1.6s
[CV] END ................criterion=entropy, n_estimators=500; total time=   1.5s
[CV] END ...................criterion=gini, n_estimators=500; total time=   1.2s
[CV] END ................criterion=entropy, n_estimators=500; total time=   1.3s
[CV] END ...................criterion=gini, n_estimators=500; total time=   1.3s
[CV] END ................criterion=entropy, n_estimators=500; total time=   1.3s
[CV] END ................criterion=entropy, n_estimators=500; total time=   1.3s

   mean_test_score                                         params
5         0.749714     {'criterion': 'gini', 'n_estimators': 500}
3         0.749691     {'criterion': 'gini', 'n_estimators': 100}
4         0.746690     {'criterion': 'gini', 'n_estimators': 250}
9         0.739114  {'criterion': 'entropy', 'n_estimators': 100}
2         0.727770      {'criterion': 'gini', 'n_estimators': 10}
8         0.714917   {'criterion': 'entropy', 'n_estimators': 10}
1         0.705838       {'criterion': 'gini', 'n_estimators': 5}
7         0.668036    {'criterion': 'entropy', 'n_estimators': 5}
0         0.614282       {'criterion': 'gini', 'n_estimators': 2}
6         0.591635    {'criterion': 'entropy', 'n_estimators': 2}

In [65]:
classifier = RandomForestClassifier(n_estimators=500 , criterion= 'gini', n_jobs= -1)
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
print(classification_report(y_test , y_pred, digits= 4))

               precision    recall  f1-score   support

     analysis     0.8219    0.6000    0.6936       100
  application     0.4083    0.4900    0.4455       100
comprehension     0.4118    0.4900    0.4475       100
   evaluation     0.4000    0.4800    0.4364       100
    knowledge     0.4700    0.4700    0.4700       100
    synthesis     0.6029    0.4100    0.4881       100

     accuracy                         0.4900       600
    macro avg     0.5192    0.4900    0.4968       600
 weighted avg     0.5192    0.4900    0.4968       600

In [84]:
question = 'What are different types of single level indexing?'
processed_q = preprocess_text(question)
tfidf_q = vectorizer.transform([processed_q])
tfidf_q = pd.DataFrame(tfidf_q.toarray(), columns=vectorizer.get_feature_names_out())



# Adding linguistic features
q_ling_features = pd.DataFrame([extract_linguistic_features(question)])

# Concatenate DataFrames
token_q = pd.concat([q_ling_features, tfidf_q], axis=1)

print(classifier.predict(tfidf_q))

['knowledge']

### Decision Tree

In [66]:
params = {
    'min_samples_split' : [2 , 5 , 10 , 50 , 100],
    'criterion' : ['gini' , 'entropy'],
    'max_depth' : [None , 5 , 10 , 50 , 100 , 250 , 500]
}
param_search = GridSearchCV(estimator= DecisionTreeClassifier(), param_grid= params, cv=5, n_jobs= -1, verbose= 2)

param_search.fit(x , y)

cv_results = pd.DataFrame(param_search.cv_results_)
cv_results = cv_results[["mean_test_score", "params"]].head(10).sort_values(by="mean_test_score", ascending=False)

cv_results

Fitting 5 folds for each of 70 candidates, totalling 350 fits
[CV] END criterion=gini, max_depth=None, min_samples_split=2; total time=   0.0s
[CV] END criterion=gini, max_depth=None, min_samples_split=2; total time=   0.0s
[CV] END criterion=gini, max_depth=None, min_samples_split=2; total time=   0.1s
[CV] END criterion=gini, max_depth=None, min_samples_split=5; total time=   0.1s
[CV] END criterion=gini, max_depth=None, min_samples_split=5; total time=   0.0s
[CV] END criterion=gini, max_depth=None, min_samples_split=5; total time=   0.1s
[CV] END criterion=gini, max_depth=None, min_samples_split=2; total time=   0.1s
[CV] END criterion=gini, max_depth=None, min_samples_split=2; total time=   0.1s
[CV] END criterion=gini, max_depth=None, min_samples_split=5; total time=   0.1s
[CV] END criterion=gini, max_depth=None, min_samples_split=10; total time=   0.0s
[CV] END criterion=gini, max_depth=None, min_samples_split=10; total time=   0.1s
[CV] END criterion=gini, max_depth=None, min_samples_split=5; total time=   0.1s
[CV] END criterion=gini, max_depth=None, min_samples_split=10; total time=   0.1s
[CV] END criterion=gini, max_depth=None, min_samples_split=50; total time=   0.0s
[CV] END criterion=gini, max_depth=None, min_samples_split=10; total time=   0.1s
[CV] END criterion=gini, max_depth=None, min_samples_split=50; total time=   0.0s
[CV] END criterion=gini, max_depth=None, min_samples_split=50; total time=   0.0s
[CV] END criterion=gini, max_depth=None, min_samples_split=50; total time=   0.1s
[CV] END criterion=gini, max_depth=None, min_samples_split=10; total time=   0.1s
[CV] END ...criterion=gini, max_depth=5, min_samples_split=2; total time=   0.0s
[CV] END ...criterion=gini, max_depth=5, min_samples_split=5; total time=   0.0s
[CV] END ...criterion=gini, max_depth=5, min_samples_split=2; total time=   0.0s
[CV] END criterion=gini, max_depth=None, min_samples_split=50; total time=   0.1s
[CV] END criterion=gini, max_depth=None, min_samples_split=100; total time=   0.1s
[CV] END ..criterion=gini, max_depth=5, min_samples_split=10; total time=   0.0s
[CV] END ...criterion=gini, max_depth=5, min_samples_split=5; total time=   0.0s
[CV] END criterion=gini, max_depth=None, min_samples_split=100; total time=   0.0s
[CV] END ...criterion=gini, max_depth=5, min_samples_split=5; total time=   0.0s
[CV] END ...criterion=gini, max_depth=5, min_samples_split=5; total time=   0.0s
[CV] END ...criterion=gini, max_depth=5, min_samples_split=2; total time=   0.0s
[CV] END ...criterion=gini, max_depth=5, min_samples_split=2; total time=   0.0s
[CV] END criterion=gini, max_depth=None, min_samples_split=100; total time=   0.0s
[CV] END ..criterion=gini, max_depth=5, min_samples_split=50; total time=   0.0s
[CV] END ..criterion=gini, max_depth=5, min_samples_split=10; total time=   0.0s
[CV] END .criterion=gini, max_depth=5, min_samples_split=100; total time=   0.0s
[CV] END ..criterion=gini, max_depth=5, min_samples_split=10; total time=   0.0s
[CV] END ..criterion=gini, max_depth=5, min_samples_split=10; total time=   0.0s
[CV] END ...criterion=gini, max_depth=5, min_samples_split=5; total time=   0.0s
[CV] END ..criterion=gini, max_depth=5, min_samples_split=50; total time=   0.0s
[CV] END criterion=gini, max_depth=None, min_samples_split=100; total time=   0.1s
[CV] END .criterion=gini, max_depth=5, min_samples_split=100; total time=   0.0s
[CV] END ..criterion=gini, max_depth=5, min_samples_split=50; total time=   0.0s
[CV] END ..criterion=gini, max_depth=5, min_samples_split=50; total time=   0.0s
[CV] END ...criterion=gini, max_depth=5, min_samples_split=2; total time=   0.0s
[CV] END .criterion=gini, max_depth=5, min_samples_split=100; total time=   0.0s
[CV] END ..criterion=gini, max_depth=5, min_samples_split=50; total time=   0.0s
[CV] END .criterion=gini, max_depth=5, min_samples_split=100; total time=   0.0s
[CV] END ..criterion=gini, max_depth=5, min_samples_split=10; total time=   0.0s
[CV] END .criterion=gini, max_depth=5, min_samples_split=100; total time=   0.0s
[CV] END ..criterion=gini, max_depth=10, min_samples_split=2; total time=   0.0s
[CV] END ..criterion=gini, max_depth=10, min_samples_split=2; total time=   0.0s
[CV] END ..criterion=gini, max_depth=10, min_samples_split=2; total time=   0.0s
[CV] END .criterion=gini, max_depth=10, min_samples_split=50; total time=   0.0s
[CV] END .criterion=gini, max_depth=10, min_samples_split=10; total time=   0.0s
[CV] END ..criterion=gini, max_depth=10, min_samples_split=5; total time=   0.0s
[CV] END ..criterion=gini, max_depth=10, min_samples_split=5; total time=   0.0s
[CV] END ..criterion=gini, max_depth=10, min_samples_split=2; total time=   0.0s
[CV] END .criterion=gini, max_depth=10, min_samples_split=10; total time=   0.0s
[CV] END criterion=gini, max_depth=None, min_samples_split=100; total time=   0.1s
[CV] END ..criterion=gini, max_depth=10, min_samples_split=5; total time=   0.0s
[CV] END criterion=gini, max_depth=10, min_samples_split=100; total time=   0.0s
[CV] END .criterion=gini, max_depth=10, min_samples_split=10; total time=   0.0s
[CV] END ..criterion=gini, max_depth=10, min_samples_split=2; total time=   0.0s
[CV] END .criterion=gini, max_depth=10, min_samples_split=50; total time=   0.0s
[CV] END ..criterion=gini, max_depth=10, min_samples_split=5; total time=   0.0s
[CV] END .criterion=gini, max_depth=10, min_samples_split=50; total time=   0.0s
[CV] END .criterion=gini, max_depth=10, min_samples_split=10; total time=   0.0s
[CV] END .criterion=gini, max_depth=10, min_samples_split=50; total time=   0.0s
[CV] END criterion=gini, max_depth=10, min_samples_split=100; total time=   0.0s
[CV] END criterion=gini, max_depth=10, min_samples_split=100; total time=   0.0s
[CV] END ..criterion=gini, max_depth=10, min_samples_split=5; total time=   0.0s
[CV] END criterion=gini, max_depth=10, min_samples_split=100; total time=   0.0s
[CV] END .criterion=gini, max_depth=10, min_samples_split=10; total time=   0.0s
[CV] END .criterion=gini, max_depth=50, min_samples_split=50; total time=   0.0s
[CV] END .criterion=gini, max_depth=10, min_samples_split=50; total time=   0.0s
[CV] END .criterion=gini, max_depth=50, min_samples_split=10; total time=   0.0s
[CV] END ..criterion=gini, max_depth=50, min_samples_split=5; total time=   0.1s
[CV] END ..criterion=gini, max_depth=50, min_samples_split=2; total time=   0.1s
[CV] END criterion=gini, max_depth=10, min_samples_split=100; total time=   0.0s
[CV] END criterion=gini, max_depth=50, min_samples_split=100; total time=   0.0s
[CV] END .criterion=gini, max_depth=50, min_samples_split=50; total time=   0.0s
[CV] END ..criterion=gini, max_depth=50, min_samples_split=2; total time=   0.1s
[CV] END .criterion=gini, max_depth=50, min_samples_split=50; total time=   0.1s
[CV] END .criterion=gini, max_depth=100, min_samples_split=2; total time=   0.1s
[CV] END .criterion=gini, max_depth=100, min_samples_split=5; total time=   0.0s
[CV] END ..criterion=gini, max_depth=50, min_samples_split=2; total time=   0.0s
[CV] END criterion=gini, max_depth=50, min_samples_split=100; total time=   0.0s
[CV] END ..criterion=gini, max_depth=50, min_samples_split=2; total time=   0.0s
[CV] END criterion=gini, max_depth=100, min_samples_split=10; total time=   0.1s
[CV] END ..criterion=gini, max_depth=50, min_samples_split=5; total time=   0.1s
[CV] END .criterion=gini, max_depth=50, min_samples_split=10; total time=   0.1s
[CV] END criterion=gini, max_depth=50, min_samples_split=100; total time=   0.0s
[CV] END .criterion=gini, max_depth=50, min_samples_split=50; total time=   0.0s
[CV] END ..criterion=gini, max_depth=50, min_samples_split=5; total time=   0.0s
[CV] END .criterion=gini, max_depth=100, min_samples_split=2; total time=   0.1s
[CV] END .criterion=gini, max_depth=100, min_samples_split=5; total time=   0.0s
[CV] END .criterion=gini, max_depth=100, min_samples_split=2; total time=   0.0s
[CV] END criterion=gini, max_depth=100, min_samples_split=10; total time=   0.1s
[CV] END criterion=gini, max_depth=100, min_samples_split=10; total time=   0.0s
[CV] END ..criterion=gini, max_depth=50, min_samples_split=2; total time=   0.0s
[CV] END .criterion=gini, max_depth=50, min_samples_split=10; total time=   0.0s
[CV] END .criterion=gini, max_depth=50, min_samples_split=50; total time=   0.0s
[CV] END ..criterion=gini, max_depth=50, min_samples_split=5; total time=   0.1s
[CV] END criterion=gini, max_depth=50, min_samples_split=100; total time=   0.1s
[CV] END .criterion=gini, max_depth=100, min_samples_split=5; total time=   0.0s
[CV] END .criterion=gini, max_depth=100, min_samples_split=2; total time=   0.1s
[CV] END ..criterion=gini, max_depth=50, min_samples_split=5; total time=   0.1s
[CV] END .criterion=gini, max_depth=100, min_samples_split=2; total time=   0.1s
[CV] END .criterion=gini, max_depth=50, min_samples_split=10; total time=   0.1s
[CV] END criterion=gini, max_depth=100, min_samples_split=10; total time=   0.1s
[CV] END criterion=gini, max_depth=100, min_samples_split=50; total time=   0.1s
[CV] END criterion=gini, max_depth=50, min_samples_split=100; total time=   0.1s
[CV] END .criterion=gini, max_depth=50, min_samples_split=10; total time=   0.1s
[CV] END criterion=gini, max_depth=100, min_samples_split=100; total time=   0.1s
[CV] END .criterion=gini, max_depth=100, min_samples_split=5; total time=   0.1s
[CV] END .criterion=gini, max_depth=100, min_samples_split=5; total time=   0.1s
[CV] END .criterion=gini, max_depth=250, min_samples_split=2; total time=   0.0s
[CV] END .criterion=gini, max_depth=250, min_samples_split=5; total time=   0.1s
[CV] END criterion=gini, max_depth=100, min_samples_split=10; total time=   0.1s
[CV] END criterion=gini, max_depth=100, min_samples_split=50; total time=   0.1s
[CV] END criterion=gini, max_depth=250, min_samples_split=50; total time=   0.1s
[CV] END criterion=gini, max_depth=100, min_samples_split=100; total time=   0.1s
[CV] END criterion=gini, max_depth=250, min_samples_split=10; total time=   0.1s
[CV] END .criterion=gini, max_depth=250, min_samples_split=5; total time=   0.1s
[CV] END .criterion=gini, max_depth=250, min_samples_split=2; total time=   0.1s
[CV] END .criterion=gini, max_depth=250, min_samples_split=5; total time=   0.0s
[CV] END .criterion=gini, max_depth=500, min_samples_split=2; total time=   0.1s
[CV] END criterion=gini, max_depth=250, min_samples_split=100; total time=   0.1s
[CV] END criterion=gini, max_depth=100, min_samples_split=50; total time=   0.2s
[CV] END criterion=gini, max_depth=250, min_samples_split=10; total time=   0.0s
[CV] END criterion=gini, max_depth=100, min_samples_split=100; total time=   0.1s
[CV] END criterion=gini, max_depth=250, min_samples_split=100; total time=   0.0s
[CV] END .criterion=gini, max_depth=500, min_samples_split=2; total time=   0.0s
[CV] END .criterion=gini, max_depth=500, min_samples_split=2; total time=   0.1s
[CV] END .criterion=gini, max_depth=250, min_samples_split=2; total time=   0.1s
[CV] END .criterion=gini, max_depth=250, min_samples_split=5; total time=   0.1s
[CV] END criterion=gini, max_depth=250, min_samples_split=50; total time=   0.1s
[CV] END criterion=gini, max_depth=250, min_samples_split=10; total time=   0.1s
[CV] END criterion=gini, max_depth=250, min_samples_split=10; total time=   0.0s
[CV] END criterion=gini, max_depth=100, min_samples_split=100; total time=   0.1s
[CV] END criterion=gini, max_depth=100, min_samples_split=100; total time=   0.0s
[CV] END .criterion=gini, max_depth=250, min_samples_split=2; total time=   0.0s
[CV] END criterion=gini, max_depth=100, min_samples_split=50; total time=   0.1s
[CV] END .criterion=gini, max_depth=500, min_samples_split=5; total time=   0.1s
[CV] END criterion=gini, max_depth=250, min_samples_split=100; total time=   0.1s
[CV] END criterion=gini, max_depth=250, min_samples_split=10; total time=   0.0s
[CV] END criterion=gini, max_depth=250, min_samples_split=50; total time=   0.0s
[CV] END .criterion=gini, max_depth=250, min_samples_split=5; total time=   0.1s
[CV] END .criterion=gini, max_depth=500, min_samples_split=2; total time=   0.1s
[CV] END criterion=gini, max_depth=250, min_samples_split=50; total time=   0.1s
[CV] END criterion=gini, max_depth=500, min_samples_split=100; total time=   0.0s
[CV] END .criterion=gini, max_depth=250, min_samples_split=2; total time=   0.1s
[CV] END criterion=gini, max_depth=500, min_samples_split=10; total time=   0.1s
[CV] END .criterion=gini, max_depth=500, min_samples_split=5; total time=   0.0s
[CV] END criterion=gini, max_depth=250, min_samples_split=50; total time=   0.0s
[CV] END criterion=gini, max_depth=100, min_samples_split=50; total time=   0.1s
[CV] END criterion=gini, max_depth=250, min_samples_split=100; total time=   0.0s
[CV] END criterion=gini, max_depth=500, min_samples_split=100; total time=   0.0s
[CV] END criterion=entropy, max_depth=None, min_samples_split=10; total time=   0.0s
[CV] END criterion=entropy, max_depth=5, min_samples_split=2; total time=   0.0s
[CV] END criterion=gini, max_depth=250, min_samples_split=100; total time=   0.1s
[CV] END criterion=entropy, max_depth=None, min_samples_split=2; total time=   0.1s
[CV] END criterion=entropy, max_depth=5, min_samples_split=50; total time=   0.0s
[CV] END criterion=entropy, max_depth=5, min_samples_split=10; total time=   0.0s
[CV] END criterion=entropy, max_depth=None, min_samples_split=50; total time=   0.0s
[CV] END criterion=entropy, max_depth=5, min_samples_split=2; total time=   0.0s
[CV] END .criterion=gini, max_depth=500, min_samples_split=2; total time=   0.1s
[CV] END .criterion=gini, max_depth=500, min_samples_split=5; total time=   0.0s
[CV] END criterion=entropy, max_depth=5, min_samples_split=10; total time=   0.0s
[CV] END criterion=gini, max_depth=500, min_samples_split=10; total time=   0.1s
[CV] END criterion=gini, max_depth=500, min_samples_split=100; total time=   0.0s
[CV] END criterion=entropy, max_depth=5, min_samples_split=2; total time=   0.0s
[CV] END criterion=entropy, max_depth=5, min_samples_split=50; total time=   0.0s
[CV] END criterion=entropy, max_depth=10, min_samples_split=2; total time=   0.0s
[CV] END criterion=entropy, max_depth=5, min_samples_split=100; total time=   0.0s
[CV] END criterion=entropy, max_depth=5, min_samples_split=5; total time=   0.0s
[CV] END criterion=entropy, max_depth=5, min_samples_split=10; total time=   0.0s
[CV] END criterion=entropy, max_depth=None, min_samples_split=10; total time=   0.1s
[CV] END criterion=entropy, max_depth=None, min_samples_split=100; total time=   0.0s
[CV] END criterion=entropy, max_depth=10, min_samples_split=2; total time=   0.0s
[CV] END criterion=entropy, max_depth=None, min_samples_split=2; total time=   0.1s
[CV] END criterion=entropy, max_depth=5, min_samples_split=5; total time=   0.0s
[CV] END criterion=entropy, max_depth=10, min_samples_split=5; total time=   0.0s
[CV] END criterion=entropy, max_depth=5, min_samples_split=10; total time=   0.0s
[CV] END .criterion=gini, max_depth=500, min_samples_split=5; total time=   0.1s
[CV] END criterion=entropy, max_depth=5, min_samples_split=100; total time=   0.0s
[CV] END criterion=gini, max_depth=500, min_samples_split=100; total time=   0.1s
[CV] END criterion=gini, max_depth=500, min_samples_split=10; total time=   0.1s
[CV] END criterion=entropy, max_depth=5, min_samples_split=10; total time=   0.0s
[CV] END criterion=entropy, max_depth=10, min_samples_split=10; total time=   0.0s
[CV] END criterion=entropy, max_depth=5, min_samples_split=5; total time=   0.0s
[CV] END criterion=entropy, max_depth=5, min_samples_split=100; total time=   0.0s
[CV] END criterion=entropy, max_depth=None, min_samples_split=5; total time=   0.0s
[CV] END criterion=entropy, max_depth=5, min_samples_split=5; total time=   0.0s
[CV] END criterion=entropy, max_depth=5, min_samples_split=50; total time=   0.0s
[CV] END criterion=entropy, max_depth=10, min_samples_split=2; total time=   0.0s
[CV] END criterion=entropy, max_depth=None, min_samples_split=100; total time=   0.0s
[CV] END criterion=entropy, max_depth=5, min_samples_split=100; total time=   0.0s
[CV] END criterion=entropy, max_depth=5, min_samples_split=5; total time=   0.0s
[CV] END criterion=entropy, max_depth=None, min_samples_split=10; total time=   0.1s
[CV] END criterion=entropy, max_depth=5, min_samples_split=100; total time=   0.0s
[CV] END criterion=entropy, max_depth=10, min_samples_split=2; total time=   0.0s
[CV] END criterion=gini, max_depth=500, min_samples_split=100; total time=   0.0s
[CV] END criterion=entropy, max_depth=10, min_samples_split=10; total time=   0.0s
[CV] END criterion=entropy, max_depth=10, min_samples_split=50; total time=   0.0s
[CV] END criterion=entropy, max_depth=5, min_samples_split=50; total time=   0.0s
[CV] END criterion=entropy, max_depth=10, min_samples_split=5; total time=   0.0s
[CV] END criterion=entropy, max_depth=None, min_samples_split=5; total time=   0.0s
[CV] END criterion=entropy, max_depth=10, min_samples_split=2; total time=   0.0s
[CV] END .criterion=gini, max_depth=500, min_samples_split=5; total time=   0.1s
[CV] END criterion=gini, max_depth=500, min_samples_split=50; total time=   0.1s
[CV] END criterion=entropy, max_depth=5, min_samples_split=50; total time=   0.0s
[CV] END criterion=entropy, max_depth=None, min_samples_split=2; total time=   0.0s
[CV] END criterion=entropy, max_depth=10, min_samples_split=50; total time=   0.0s
[CV] END criterion=entropy, max_depth=10, min_samples_split=10; total time=   0.0s
[CV] END criterion=entropy, max_depth=None, min_samples_split=100; total time=   0.1s
[CV] END criterion=entropy, max_depth=10, min_samples_split=5; total time=   0.0s
[CV] END criterion=gini, max_depth=500, min_samples_split=50; total time=   0.0s
[CV] END criterion=entropy, max_depth=None, min_samples_split=5; total time=   0.0s
[CV] END criterion=entropy, max_depth=10, min_samples_split=10; total time=   0.0s
[CV] END criterion=entropy, max_depth=None, min_samples_split=2; total time=   0.0s
[CV] END criterion=entropy, max_depth=10, min_samples_split=5; total time=   0.0s
[CV] END criterion=entropy, max_depth=50, min_samples_split=2; total time=   0.0s
[CV] END criterion=entropy, max_depth=None, min_samples_split=10; total time=   0.1s
[CV] END criterion=entropy, max_depth=10, min_samples_split=5; total time=   0.0s
[CV] END criterion=gini, max_depth=500, min_samples_split=10; total time=   0.1s
[CV] END criterion=entropy, max_depth=10, min_samples_split=10; total time=   0.0s
[CV] END criterion=entropy, max_depth=10, min_samples_split=50; total time=   0.1s
[CV] END criterion=entropy, max_depth=50, min_samples_split=5; total time=   0.1s
[CV] END criterion=entropy, max_depth=None, min_samples_split=5; total time=   0.0s
[CV] END criterion=entropy, max_depth=10, min_samples_split=100; total time=   0.0s
[CV] END criterion=gini, max_depth=500, min_samples_split=50; total time=   0.1s
[CV] END criterion=entropy, max_depth=10, min_samples_split=50; total time=   0.0s
[CV] END criterion=entropy, max_depth=None, min_samples_split=100; total time=   0.1s
[CV] END criterion=entropy, max_depth=None, min_samples_split=2; total time=   0.1s
[CV] END criterion=entropy, max_depth=50, min_samples_split=2; total time=   0.1s
[CV] END criterion=entropy, max_depth=None, min_samples_split=50; total time=   0.0s
[CV] END criterion=entropy, max_depth=10, min_samples_split=100; total time=   0.0s
[CV] END criterion=entropy, max_depth=10, min_samples_split=50; total time=   0.0s
[CV] END criterion=entropy, max_depth=50, min_samples_split=50; total time=   0.1s
[CV] END criterion=gini, max_depth=500, min_samples_split=10; total time=   0.1s
[CV] END criterion=entropy, max_depth=50, min_samples_split=5; total time=   0.1s
[CV] END criterion=entropy, max_depth=None, min_samples_split=100; total time=   0.0s

   mean_test_score                                                              params
0         0.709634    {'criterion': 'gini', 'max_depth': None, 'min_samples_split': 2}
1         0.702090    {'criterion': 'gini', 'max_depth': None, 'min_samples_split': 5}
2         0.698290   {'criterion': 'gini', 'max_depth': None, 'min_samples_split': 10}
3         0.671003   {'criterion': 'gini', 'max_depth': None, 'min_samples_split': 50}
4         0.662707  {'criterion': 'gini', 'max_depth': None, 'min_samples_split': 100}
5         0.290540       {'criterion': 'gini', 'max_depth': 5, 'min_samples_split': 2}
6         0.289783       {'criterion': 'gini', 'max_depth': 5, 'min_samples_split': 5}
7         0.289028      {'criterion': 'gini', 'max_depth': 5, 'min_samples_split': 10}
8         0.279180      {'criterion': 'gini', 'max_depth': 5, 'min_samples_split': 50}
9         0.278422     {'criterion': 'gini', 'max_depth': 5, 'min_samples_split': 100}

In [67]:
dt = DecisionTreeClassifier(criterion= 'gini', max_depth= None, min_samples_split = 2)
dt.fit(x_train, y_train)
y_pred = dt.predict(x_test)
print(classification_report(y_test , y_pred, digits= 4))

               precision    recall  f1-score   support

     analysis     0.6824    0.5800    0.6270       100
  application     0.3396    0.3600    0.3495       100
comprehension     0.3333    0.3700    0.3507       100
   evaluation     0.2897    0.4200    0.3429       100
    knowledge     0.5278    0.3800    0.4419       100
    synthesis     0.4568    0.3700    0.4088       100

     accuracy                         0.4133       600
    macro avg     0.4383    0.4133    0.4201       600
 weighted avg     0.4383    0.4133    0.4201       600

In [87]:
question = 'What are different types of single level indexing?'
processed_q = preprocess_text(question)
tfidf_q = vectorizer.transform([processed_q])
tfidf_q = pd.DataFrame(tfidf_q.toarray(), columns=vectorizer.get_feature_names_out())



# Adding linguistic features
q_ling_features = pd.DataFrame([extract_linguistic_features(question)])

# Concatenate DataFrames
token_q = pd.concat([q_ling_features, tfidf_q], axis=1)

print(dt.predict(tfidf_q))

['knowledge']

### XGBoost

In [68]:
y_mapper = {
    'knowledge' : 0,
    'comprehension' : 1,
    'application' : 2,
    'analysis' : 3,
    'synthesis' : 4,
    'evaluation' : 5
}

xgb_y = y.map(y_mapper)
xgb_y_train = y_train.map(y_mapper)
xgb_y_test = y_test.map(y_mapper)

In [69]:
params = {
    'max_depth' : [None , 250],
    'n_estimators': [100, 200],
    'learning_rate': [0.01, 0.1 , 0.3],
    'subsample': [0.8, 0.9]
}
param_search = GridSearchCV(estimator= XGBClassifier(objective='multi:softprob' , verbosity= 1), 
                            param_grid= params, cv=5, n_jobs= -1,return_train_score=True, verbose=2)

param_search.fit(x , xgb_y)

cv_results = pd.DataFrame(param_search.cv_results_)
cv_results = cv_results[["mean_test_score", "params"]].head(10).sort_values(by="mean_test_score", ascending=False)

cv_results

Fitting 5 folds for each of 24 candidates, totalling 120 fits
[CV] END learning_rate=0.01, max_depth=None, n_estimators=100, subsample=0.8; total time=   0.7s
[CV] END learning_rate=0.01, max_depth=None, n_estimators=100, subsample=0.9; total time=   0.7s
[CV] END learning_rate=0.01, max_depth=None, n_estimators=100, subsample=0.9; total time=   0.7s
[CV] END learning_rate=0.01, max_depth=None, n_estimators=100, subsample=0.8; total time=   0.7s
[CV] END learning_rate=0.01, max_depth=None, n_estimators=100, subsample=0.8; total time=   0.7s
[CV] END learning_rate=0.01, max_depth=None, n_estimators=100, subsample=0.8; total time=   0.8s
[CV] END learning_rate=0.01, max_depth=None, n_estimators=100, subsample=0.9; total time=   0.8s
[CV] END learning_rate=0.01, max_depth=None, n_estimators=100, subsample=0.9; total time=   0.8s
[CV] END learning_rate=0.01, max_depth=None, n_estimators=100, subsample=0.9; total time=   0.8s
[CV] END learning_rate=0.01, max_depth=None, n_estimators=100, subsample=0.8; total time=   0.8s
[CV] END learning_rate=0.01, max_depth=None, n_estimators=200, subsample=0.8; total time=   1.4s
[CV] END learning_rate=0.01, max_depth=None, n_estimators=200, subsample=0.8; total time=   1.3s
[CV] END learning_rate=0.01, max_depth=None, n_estimators=200, subsample=0.8; total time=   1.3s
[CV] END learning_rate=0.01, max_depth=None, n_estimators=200, subsample=0.8; total time=   1.4s
[CV] END learning_rate=0.01, max_depth=None, n_estimators=200, subsample=0.9; total time=   1.3s
[CV] END learning_rate=0.01, max_depth=None, n_estimators=200, subsample=0.9; total time=   1.3s
[CV] END learning_rate=0.01, max_depth=None, n_estimators=200, subsample=0.9; total time=   1.4s
[CV] END learning_rate=0.01, max_depth=None, n_estimators=200, subsample=0.9; total time=   1.4s
[CV] END learning_rate=0.01, max_depth=None, n_estimators=200, subsample=0.8; total time=   1.5s
[CV] END learning_rate=0.01, max_depth=None, n_estimators=200, subsample=0.9; total time=   1.5s
[CV] END learning_rate=0.01, max_depth=250, n_estimators=100, subsample=0.8; total time=   1.8s
[CV] END learning_rate=0.01, max_depth=250, n_estimators=100, subsample=0.8; total time=   1.9s
[CV] END learning_rate=0.01, max_depth=250, n_estimators=100, subsample=0.8; total time=   1.8s
[CV] END learning_rate=0.01, max_depth=250, n_estimators=100, subsample=0.8; total time=   1.9s
[CV] END learning_rate=0.01, max_depth=250, n_estimators=100, subsample=0.9; total time=   2.0s
[CV] END learning_rate=0.01, max_depth=250, n_estimators=100, subsample=0.8; total time=   2.1s
[CV] END learning_rate=0.01, max_depth=250, n_estimators=100, subsample=0.9; total time=   2.0s
[CV] END learning_rate=0.01, max_depth=250, n_estimators=100, subsample=0.9; total time=   2.0s
[CV] END learning_rate=0.01, max_depth=250, n_estimators=100, subsample=0.9; total time=   2.1s
[CV] END learning_rate=0.01, max_depth=250, n_estimators=100, subsample=0.9; total time=   2.2s
[CV] END learning_rate=0.1, max_depth=None, n_estimators=100, subsample=0.8; total time=   0.7s
[CV] END learning_rate=0.1, max_depth=None, n_estimators=100, subsample=0.8; total time=   0.7s
[CV] END learning_rate=0.01, max_depth=250, n_estimators=200, subsample=0.8; total time=   4.0s
[CV] END learning_rate=0.01, max_depth=250, n_estimators=200, subsample=0.8; total time=   3.7s
[CV] END learning_rate=0.1, max_depth=None, n_estimators=100, subsample=0.8; total time=   0.7s
[CV] END learning_rate=0.1, max_depth=None, n_estimators=100, subsample=0.8; total time=   0.7s
[CV] END learning_rate=0.1, max_depth=None, n_estimators=100, subsample=0.8; total time=   0.7s
[CV] END learning_rate=0.01, max_depth=250, n_estimators=200, subsample=0.8; total time=   3.9s
[CV] END learning_rate=0.1, max_depth=None, n_estimators=100, subsample=0.9; total time=   0.7s
[CV] END learning_rate=0.1, max_depth=None, n_estimators=100, subsample=0.9; total time=   0.6s
[CV] END learning_rate=0.01, max_depth=250, n_estimators=200, subsample=0.8; total time=   3.8s
[CV] END learning_rate=0.1, max_depth=None, n_estimators=100, subsample=0.9; total time=   0.7s
[CV] END learning_rate=0.1, max_depth=None, n_estimators=100, subsample=0.9; total time=   0.7s
[CV] END learning_rate=0.01, max_depth=250, n_estimators=200, subsample=0.8; total time=   4.0s
[CV] END learning_rate=0.1, max_depth=None, n_estimators=100, subsample=0.9; total time=   0.7s
[CV] END learning_rate=0.01, max_depth=250, n_estimators=200, subsample=0.9; total time=   4.0s
[CV] END learning_rate=0.01, max_depth=250, n_estimators=200, subsample=0.9; total time=   4.1s
[CV] END learning_rate=0.01, max_depth=250, n_estimators=200, subsample=0.9; total time=   4.2s
[CV] END learning_rate=0.01, max_depth=250, n_estimators=200, subsample=0.9; total time=   4.2s
[CV] END learning_rate=0.01, max_depth=250, n_estimators=200, subsample=0.9; total time=   4.5s
[CV] END learning_rate=0.1, max_depth=None, n_estimators=200, subsample=0.8; total time=   1.2s
[CV] END learning_rate=0.1, max_depth=None, n_estimators=200, subsample=0.8; total time=   1.2s
[CV] END learning_rate=0.1, max_depth=None, n_estimators=200, subsample=0.8; total time=   1.2s
[CV] END learning_rate=0.1, max_depth=None, n_estimators=200, subsample=0.8; total time=   1.1s
[CV] END learning_rate=0.1, max_depth=None, n_estimators=200, subsample=0.8; total time=   1.1s
[CV] END learning_rate=0.1, max_depth=None, n_estimators=200, subsample=0.9; total time=   1.3s
[CV] END learning_rate=0.1, max_depth=None, n_estimators=200, subsample=0.9; total time=   1.1s
[CV] END learning_rate=0.1, max_depth=None, n_estimators=200, subsample=0.9; total time=   1.2s
[CV] END learning_rate=0.1, max_depth=None, n_estimators=200, subsample=0.9; total time=   1.2s
[CV] END learning_rate=0.1, max_depth=None, n_estimators=200, subsample=0.9; total time=   1.3s
[CV] END learning_rate=0.1, max_depth=250, n_estimators=100, subsample=0.8; total time=   1.3s
[CV] END learning_rate=0.1, max_depth=250, n_estimators=100, subsample=0.8; total time=   1.3s
[CV] END learning_rate=0.1, max_depth=250, n_estimators=100, subsample=0.8; total time=   1.5s
[CV] END learning_rate=0.1, max_depth=250, n_estimators=100, subsample=0.8; total time=   1.4s
[CV] END learning_rate=0.1, max_depth=250, n_estimators=100, subsample=0.8; total time=   1.7s
[CV] END learning_rate=0.1, max_depth=250, n_estimators=100, subsample=0.9; total time=   1.6s
[CV] END learning_rate=0.1, max_depth=250, n_estimators=100, subsample=0.9; total time=   1.6s
[CV] END learning_rate=0.1, max_depth=250, n_estimators=100, subsample=0.9; total time=   1.5s
[CV] END learning_rate=0.1, max_depth=250, n_estimators=100, subsample=0.9; total time=   1.5s
[CV] END learning_rate=0.1, max_depth=250, n_estimators=100, subsample=0.9; total time=   1.7s
[CV] END learning_rate=0.3, max_depth=None, n_estimators=100, subsample=0.8; total time=   0.7s
[CV] END learning_rate=0.1, max_depth=250, n_estimators=200, subsample=0.8; total time=   2.4s
[CV] END learning_rate=0.1, max_depth=250, n_estimators=200, subsample=0.8; total time=   2.1s
[CV] END learning_rate=0.1, max_depth=250, n_estimators=200, subsample=0.8; total time=   2.2s
[CV] END learning_rate=0.3, max_depth=None, n_estimators=100, subsample=0.8; total time=   0.6s
[CV] END learning_rate=0.1, max_depth=250, n_estimators=200, subsample=0.8; total time=   2.4s
[CV] END learning_rate=0.3, max_depth=None, n_estimators=100, subsample=0.8; total time=   0.7s
[CV] END learning_rate=0.1, max_depth=250, n_estimators=200, subsample=0.8; total time=   2.4s
[CV] END learning_rate=0.3, max_depth=None, n_estimators=100, subsample=0.8; total time=   0.6s
[CV] END learning_rate=0.3, max_depth=None, n_estimators=100, subsample=0.8; total time=   0.6s
[CV] END learning_rate=0.1, max_depth=250, n_estimators=200, subsample=0.9; total time=   2.3s
[CV] END learning_rate=0.3, max_depth=None, n_estimators=100, subsample=0.9; total time=   0.7s
[CV] END learning_rate=0.1, max_depth=250, n_estimators=200, subsample=0.9; total time=   2.3s
[CV] END learning_rate=0.3, max_depth=None, n_estimators=100, subsample=0.9; total time=   0.6s
[CV] END learning_rate=0.1, max_depth=250, n_estimators=200, subsample=0.9; total time=   2.2s
[CV] END learning_rate=0.3, max_depth=None, n_estimators=100, subsample=0.9; total time=   0.6s
[CV] END learning_rate=0.3, max_depth=None, n_estimators=100, subsample=0.9; total time=   0.6s
[CV] END learning_rate=0.1, max_depth=250, n_estimators=200, subsample=0.9; total time=   2.4s
[CV] END learning_rate=0.1, max_depth=250, n_estimators=200, subsample=0.9; total time=   2.5s
[CV] END learning_rate=0.3, max_depth=None, n_estimators=100, subsample=0.9; total time=   0.7s
[CV] END learning_rate=0.3, max_depth=None, n_estimators=200, subsample=0.8; total time=   1.0s
[CV] END learning_rate=0.3, max_depth=None, n_estimators=200, subsample=0.8; total time=   1.1s
[CV] END learning_rate=0.3, max_depth=None, n_estimators=200, subsample=0.8; total time=   1.1s
[CV] END learning_rate=0.3, max_depth=None, n_estimators=200, subsample=0.8; total time=   1.1s
[CV] END learning_rate=0.3, max_depth=None, n_estimators=200, subsample=0.9; total time=   1.0s
[CV] END learning_rate=0.3, max_depth=None, n_estimators=200, subsample=0.8; total time=   1.1s
[CV] END learning_rate=0.3, max_depth=None, n_estimators=200, subsample=0.9; total time=   1.2s
[CV] END learning_rate=0.3, max_depth=None, n_estimators=200, subsample=0.9; total time=   1.1s
[CV] END learning_rate=0.3, max_depth=None, n_estimators=200, subsample=0.9; total time=   1.1s
[CV] END learning_rate=0.3, max_depth=250, n_estimators=100, subsample=0.8; total time=   0.9s
[CV] END learning_rate=0.3, max_depth=None, n_estimators=200, subsample=0.9; total time=   1.2s
[CV] END learning_rate=0.3, max_depth=250, n_estimators=100, subsample=0.8; total time=   0.9s
[CV] END learning_rate=0.3, max_depth=250, n_estimators=100, subsample=0.8; total time=   1.0s
[CV] END learning_rate=0.3, max_depth=250, n_estimators=100, subsample=0.8; total time=   1.1s
[CV] END learning_rate=0.3, max_depth=250, n_estimators=100, subsample=0.9; total time=   1.0s
[CV] END learning_rate=0.3, max_depth=250, n_estimators=100, subsample=0.9; total time=   1.1s
[CV] END learning_rate=0.3, max_depth=250, n_estimators=100, subsample=0.9; total time=   1.0s
[CV] END learning_rate=0.3, max_depth=250, n_estimators=100, subsample=0.8; total time=   1.3s
[CV] END learning_rate=0.3, max_depth=250, n_estimators=100, subsample=0.9; total time=   1.1s
[CV] END learning_rate=0.3, max_depth=250, n_estimators=100, subsample=0.9; total time=   1.2s
[CV] END learning_rate=0.3, max_depth=250, n_estimators=200, subsample=0.8; total time=   1.6s
[CV] END learning_rate=0.3, max_depth=250, n_estimators=200, subsample=0.8; total time=   1.6s
[CV] END learning_rate=0.3, max_depth=250, n_estimators=200, subsample=0.8; total time=   1.4s
[CV] END learning_rate=0.3, max_depth=250, n_estimators=200, subsample=0.8; total time=   1.6s
[CV] END learning_rate=0.3, max_depth=250, n_estimators=200, subsample=0.9; total time=   1.5s
[CV] END learning_rate=0.3, max_depth=250, n_estimators=200, subsample=0.8; total time=   1.6s
[CV] END learning_rate=0.3, max_depth=250, n_estimators=200, subsample=0.9; total time=   1.5s
[CV] END learning_rate=0.3, max_depth=250, n_estimators=200, subsample=0.9; total time=   1.5s
[CV] END learning_rate=0.3, max_depth=250, n_estimators=200, subsample=0.9; total time=   1.5s
[CV] END learning_rate=0.3, max_depth=250, n_estimators=200, subsample=0.9; total time=   1.4s

   mean_test_score                                                                             params
9         0.730049   {'learning_rate': 0.1, 'max_depth': None, 'n_estimators': 100, 'subsample': 0.9}
8         0.730049   {'learning_rate': 0.1, 'max_depth': None, 'n_estimators': 100, 'subsample': 0.8}
6         0.727047   {'learning_rate': 0.01, 'max_depth': 250, 'n_estimators': 200, 'subsample': 0.8}
7         0.721750   {'learning_rate': 0.01, 'max_depth': 250, 'n_estimators': 200, 'subsample': 0.9}
4         0.714182   {'learning_rate': 0.01, 'max_depth': 250, 'n_estimators': 100, 'subsample': 0.8}
5         0.713422   {'learning_rate': 0.01, 'max_depth': 250, 'n_estimators': 100, 'subsample': 0.9}
2         0.686149  {'learning_rate': 0.01, 'max_depth': None, 'n_estimators': 200, 'subsample': 0.8}
3         0.675566  {'learning_rate': 0.01, 'max_depth': None, 'n_estimators': 200, 'subsample': 0.9}
0         0.658902  {'learning_rate': 0.01, 'max_depth': None, 'n_estimators': 100, 'subsample': 0.8}
1         0.652098  {'learning_rate': 0.01, 'max_depth': None, 'n_estimators': 100, 'subsample': 0.9}

In [70]:
xgb = XGBClassifier(learning_rate=0.1, max_depth=None, n_estimators=100, subsample=0.9)
xgb.fit(x_train, xgb_y_train)
y_pred = xgb.predict(x_test)
print(classification_report(xgb_y_test , y_pred, digits= 4))

              precision    recall  f1-score   support

           0     0.0000    0.0000    0.0000       100
           1     0.0000    0.0000    0.0000       100
           2     0.0000    0.0000    0.0000       100
           3     0.0000    0.0000    0.0000       100
           4     0.0000    0.0000    0.0000       100
           5     0.1667    1.0000    0.2857       100

    accuracy                         0.1667       600
   macro avg     0.0278    0.1667    0.0476       600
weighted avg     0.0278    0.1667    0.0476       600

In [91]:
question = 'What are different types of single level indexing?'
processed_q = preprocess_text(question)
tfidf_q = vectorizer.transform([processed_q])
tfidf_q = pd.DataFrame(tfidf_q.toarray(), columns=vectorizer.get_feature_names_out())



# Adding linguistic features
q_ling_features = pd.DataFrame([extract_linguistic_features(question)])

# Concatenate DataFrames
token_q = pd.concat([q_ling_features, tfidf_q], axis=1)
# token_q = token_q.drop(columns= ['blooms_verb_present'])

print(xgb.predict(tfidf_q))

[0]

### Linear SVM

In [71]:
params = {
    'penalty': ['l2'],
    'loss': ['squared_hinge' , 'hinge'],
    'dual': [True, False],
    'C': [0.1, 1, 10, 100]
}
param_search = GridSearchCV(estimator= LinearSVC(), param_grid= params, cv=5, n_jobs= -1, return_train_score=True, verbose= 2)

param_search.fit(x , y)

cv_results = pd.DataFrame(param_search.cv_results_)
cv_results = cv_results[["mean_test_score", "params"]].head(10).sort_values(by="mean_test_score", ascending=False)

cv_results

Fitting 5 folds for each of 16 candidates, totalling 80 fits
[CV] END ...C=0.1, dual=True, loss=squared_hinge, penalty=l2; total time=   0.0s
[CV] END ...C=0.1, dual=True, loss=squared_hinge, penalty=l2; total time=   0.0s
[CV] END ...C=0.1, dual=True, loss=squared_hinge, penalty=l2; total time=   0.0s
[CV] END ...C=0.1, dual=True, loss=squared_hinge, penalty=l2; total time=   0.0s
[CV] END ...C=0.1, dual=True, loss=squared_hinge, penalty=l2; total time=   0.0s
[CV] END ...........C=0.1, dual=True, loss=hinge, penalty=l2; total time=   0.0s
[CV] END ...........C=0.1, dual=True, loss=hinge, penalty=l2; total time=   0.0s
[CV] END ...........C=0.1, dual=True, loss=hinge, penalty=l2; total time=   0.0s
[CV] END ...........C=0.1, dual=True, loss=hinge, penalty=l2; total time=   0.0s
[CV] END ..........C=0.1, dual=False, loss=hinge, penalty=l2; total time=   0.0s
[CV] END ..C=0.1, dual=False, loss=squared_hinge, penalty=l2; total time=   0.0s
[CV] END ..........C=0.1, dual=False, loss=hinge, penalty=l2; total time=   0.0s
[CV] END ...........C=0.1, dual=True, loss=hinge, penalty=l2; total time=   0.0s
[CV] END ..C=0.1, dual=False, loss=squared_hinge, penalty=l2; total time=   0.0s
[CV] END ..........C=0.1, dual=False, loss=hinge, penalty=l2; total time=   0.0s[CV] END ..........C=0.1, dual=False, loss=hinge, penalty=l2; total time=   0.0s

[CV] END ..C=0.1, dual=False, loss=squared_hinge, penalty=l2; total time=   0.0s
[CV] END ..C=0.1, dual=False, loss=squared_hinge, penalty=l2; total time=   0.0s
[CV] END ..........C=0.1, dual=False, loss=hinge, penalty=l2; total time=   0.0s
[CV] END ..C=0.1, dual=False, loss=squared_hinge, penalty=l2; total time=   0.0s
[CV] END ............C=1, dual=False, loss=hinge, penalty=l2; total time=   0.0s
[CV] END .....C=1, dual=True, loss=squared_hinge, penalty=l2; total time=   0.0s
[CV] END ............C=1, dual=False, loss=hinge, penalty=l2; total time=   0.0s
[CV] END .....C=1, dual=True, loss=squared_hinge, penalty=l2; total time=   0.0s
[CV] END .....C=1, dual=True, loss=squared_hinge, penalty=l2; total time=   0.0s
[CV] END ............C=1, dual=False, loss=hinge, penalty=l2; total time=   0.0s
[CV] END ............C=1, dual=False, loss=hinge, penalty=l2; total time=   0.0s
[CV] END ....C=1, dual=False, loss=squared_hinge, penalty=l2; total time=   0.0s
[CV] END ....C=1, dual=False, loss=squared_hinge, penalty=l2; total time=   0.0s
[CV] END .....C=1, dual=True, loss=squared_hinge, penalty=l2; total time=   0.0s
[CV] END .............C=1, dual=True, loss=hinge, penalty=l2; total time=   0.0s
[CV] END ....C=1, dual=False, loss=squared_hinge, penalty=l2; total time=   0.0s
[CV] END .....C=1, dual=True, loss=squared_hinge, penalty=l2; total time=   0.0s
[CV] END ............C=1, dual=False, loss=hinge, penalty=l2; total time=   0.0s
[CV] END .............C=1, dual=True, loss=hinge, penalty=l2; total time=   0.0s
[CV] END .............C=1, dual=True, loss=hinge, penalty=l2; total time=   0.0s
[CV] END ....C=1, dual=False, loss=squared_hinge, penalty=l2; total time=   0.0s
[CV] END ....C=1, dual=False, loss=squared_hinge, penalty=l2; total time=   0.0s
[CV] END ...........C=10, dual=False, loss=hinge, penalty=l2; total time=   0.0s
[CV] END ...........C=10, dual=False, loss=hinge, penalty=l2; total time=   0.0s
[CV] END .............C=1, dual=True, loss=hinge, penalty=l2; total time=   0.0s
[CV] END ...........C=10, dual=False, loss=hinge, penalty=l2; total time=   0.0s
[CV] END ...........C=10, dual=False, loss=hinge, penalty=l2; total time=   0.0s
[CV] END .............C=1, dual=True, loss=hinge, penalty=l2; total time=   0.0s
[CV] END ...C=10, dual=False, loss=squared_hinge, penalty=l2; total time=   0.0s
[CV] END ....C=10, dual=True, loss=squared_hinge, penalty=l2; total time=   0.0s
[CV] END ...C=10, dual=False, loss=squared_hinge, penalty=l2; total time=   0.0s
[CV] END ............C=10, dual=True, loss=hinge, penalty=l2; total time=   0.0s
[CV] END ....C=10, dual=True, loss=squared_hinge, penalty=l2; total time=   0.0s
[CV] END ...C=10, dual=False, loss=squared_hinge, penalty=l2; total time=   0.0s
[CV] END ...C=10, dual=False, loss=squared_hinge, penalty=l2; total time=   0.0s
[CV] END ....C=10, dual=True, loss=squared_hinge, penalty=l2; total time=   0.1s
[CV] END ...........C=10, dual=False, loss=hinge, penalty=l2; total time=   0.0s
[CV] END ...C=10, dual=False, loss=squared_hinge, penalty=l2; total time=   0.0s
[CV] END ............C=10, dual=True, loss=hinge, penalty=l2; total time=   0.1s
[CV] END ....C=10, dual=True, loss=squared_hinge, penalty=l2; total time=   0.0s
[CV] END ....C=10, dual=True, loss=squared_hinge, penalty=l2; total time=   0.0s
[CV] END ............C=10, dual=True, loss=hinge, penalty=l2; total time=   0.0s
[CV] END ............C=10, dual=True, loss=hinge, penalty=l2; total time=   0.1s
[CV] END ...C=100, dual=True, loss=squared_hinge, penalty=l2; total time=   0.1s
[CV] END ...C=100, dual=True, loss=squared_hinge, penalty=l2; total time=   0.1s
[CV] END ............C=10, dual=True, loss=hinge, penalty=l2; total time=   0.0s
[CV] END ...........C=100, dual=True, loss=hinge, penalty=l2; total time=   0.1s
[CV] END ...C=100, dual=True, loss=squared_hinge, penalty=l2; total time=   0.1s
[CV] END ...........C=100, dual=True, loss=hinge, penalty=l2; total time=   0.1s
[CV] END ...........C=100, dual=True, loss=hinge, penalty=l2; total time=   0.1s

/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END ..........C=100, dual=False, loss=hinge, penalty=l2; total time=   0.0s
[CV] END ..........C=100, dual=False, loss=hinge, penalty=l2; total time=   0.0s
[CV] END ..........C=100, dual=False, loss=hinge, penalty=l2; total time=   0.0s
[CV] END ...........C=100, dual=True, loss=hinge, penalty=l2; total time=   0.1s
[CV] END ..........C=100, dual=False, loss=hinge, penalty=l2; total time=   0.0s
[CV] END ..........C=100, dual=False, loss=hinge, penalty=l2; total time=   0.0s
[CV] END ..C=100, dual=False, loss=squared_hinge, penalty=l2; total time=   0.1s
[CV] END ..C=100, dual=False, loss=squared_hinge, penalty=l2; total time=   0.1s
[CV] END ..C=100, dual=False, loss=squared_hinge, penalty=l2; total time=   0.0s
[CV] END ..C=100, dual=False, loss=squared_hinge, penalty=l2; total time=   0.0s
[CV] END ..C=100, dual=False, loss=squared_hinge, penalty=l2; total time=   0.0s
[CV] END ...C=100, dual=True, loss=squared_hinge, penalty=l2; total time=   0.1s
[CV] END ...........C=100, dual=True, loss=hinge, penalty=l2; total time=   0.1s
[CV] END ...C=100, dual=True, loss=squared_hinge, penalty=l2; total time=   0.1s

   mean_test_score                                                               params
0         0.745149   {'C': 0.1, 'dual': True, 'loss': 'squared_hinge', 'penalty': 'l2'}
2         0.745149  {'C': 0.1, 'dual': False, 'loss': 'squared_hinge', 'penalty': 'l2'}
4         0.739874     {'C': 1, 'dual': True, 'loss': 'squared_hinge', 'penalty': 'l2'}
6         0.739874    {'C': 1, 'dual': False, 'loss': 'squared_hinge', 'penalty': 'l2'}
5         0.736832             {'C': 1, 'dual': True, 'loss': 'hinge', 'penalty': 'l2'}
1         0.723957           {'C': 0.1, 'dual': True, 'loss': 'hinge', 'penalty': 'l2'}
9         0.717167            {'C': 10, 'dual': True, 'loss': 'hinge', 'penalty': 'l2'}
8         0.716424    {'C': 10, 'dual': True, 'loss': 'squared_hinge', 'penalty': 'l2'}
3              NaN          {'C': 0.1, 'dual': False, 'loss': 'hinge', 'penalty': 'l2'}
7              NaN            {'C': 1, 'dual': False, 'loss': 'hinge', 'penalty': 'l2'}

In [72]:
lsvm = LinearSVC(C= 0.1, dual= True, loss= 'squared_hinge', penalty= 'l2')
lsvm.fit(x_train, y_train)
y_pred = lsvm.predict(x_test)
print(classification_report(y_test, y_pred, digits= 4))

               precision    recall  f1-score   support

     analysis     0.8133    0.6100    0.6971       100
  application     0.3846    0.4500    0.4147       100
comprehension     0.3364    0.7400    0.4625       100
   evaluation     0.6364    0.3500    0.4516       100
    knowledge     0.6383    0.3000    0.4082       100
    synthesis     0.5465    0.4700    0.5054       100

     accuracy                         0.4867       600
    macro avg     0.5592    0.4867    0.4899       600
 weighted avg     0.5592    0.4867    0.4899       600

In [94]:
question = 'What are different types of single level indexing?'
processed_q = preprocess_text(question)
tfidf_q = vectorizer.transform([processed_q])
tfidf_q = pd.DataFrame(tfidf_q.toarray(), columns=vectorizer.get_feature_names_out())



# Adding linguistic features
q_ling_features = pd.DataFrame([extract_linguistic_features(question)])

# Concatenate DataFrames
token_q = pd.concat([q_ling_features, tfidf_q], axis=1)

print(lsvm.predict(tfidf_q))

['analysis']

### Naive Bayes

In [73]:
params = {
    'alpha': [1e-1000,1e-500,1e-100, 1e-50,1e-20,1e-10,1e-06],
    'fit_prior': [True, False],
    'force_alpha': [True, False]
}
param_search = GridSearchCV(estimator= MultinomialNB(), param_grid= params, cv=5, n_jobs= -1)

param_search.fit(x, y)

cv_results = pd.DataFrame(param_search.cv_results_)
cv_results = cv_results[["mean_test_score", "params"]].head(10).sort_values(by="mean_test_score", ascending=False)

cv_results

/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:898: RuntimeWarning: divide by zero encountered in log
  self.feature_log_prob_ = np.log(smoothed_fc) - np.log(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:898: RuntimeWarning: divide by zero encountered in log
  self.feature_log_prob_ = np.log(smoothed_fc) - np.log(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:898: RuntimeWarning: divide by zero encountered in log
  self.feature_log_prob_ = np.log(smoothed_fc) - np.log(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:898: RuntimeWarning: divide by zero encountered in log
  self.feature_log_prob_ = np.log(smoothed_fc) - np.log(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:898: RuntimeWarning: divide by zero encountered in log
  self.feature_log_prob_ = np.log(smoothed_fc) - np.log(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:898: RuntimeWarning: divide by zero encountered in log
  self.feature_log_prob_ = np.log(smoothed_fc) - np.log(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:898: RuntimeWarning: divide by zero encountered in log
  self.feature_log_prob_ = np.log(smoothed_fc) - np.log(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:898: RuntimeWarning: divide by zero encountered in log
  self.feature_log_prob_ = np.log(smoothed_fc) - np.log(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:898: RuntimeWarning: divide by zero encountered in log
  self.feature_log_prob_ = np.log(smoothed_fc) - np.log(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:898: RuntimeWarning: divide by zero encountered in log
  self.feature_log_prob_ = np.log(smoothed_fc) - np.log(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:898: RuntimeWarning: divide by zero encountered in log
  self.feature_log_prob_ = np.log(smoothed_fc) - np.log(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:898: RuntimeWarning: divide by zero encountered in log
  self.feature_log_prob_ = np.log(smoothed_fc) - np.log(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:898: RuntimeWarning: divide by zero encountered in log
  self.feature_log_prob_ = np.log(smoothed_fc) - np.log(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:898: RuntimeWarning: divide by zero encountered in log
  self.feature_log_prob_ = np.log(smoothed_fc) - np.log(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:898: RuntimeWarning: divide by zero encountered in log
  self.feature_log_prob_ = np.log(smoothed_fc) - np.log(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:898: RuntimeWarning: divide by zero encountered in log
  self.feature_log_prob_ = np.log(smoothed_fc) - np.log(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:898: RuntimeWarning: divide by zero encountered in log
  self.feature_log_prob_ = np.log(smoothed_fc) - np.log(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:898: RuntimeWarning: divide by zero encountered in log
  self.feature_log_prob_ = np.log(smoothed_fc) - np.log(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:898: RuntimeWarning: divide by zero encountered in log
  self.feature_log_prob_ = np.log(smoothed_fc) - np.log(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:898: RuntimeWarning: divide by zero encountered in log
  self.feature_log_prob_ = np.log(smoothed_fc) - np.log(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(

   mean_test_score                                                      params
3         0.650612    {'alpha': 0.0, 'fit_prior': False, 'force_alpha': False}
7         0.650612    {'alpha': 0.0, 'fit_prior': False, 'force_alpha': False}
1         0.649105     {'alpha': 0.0, 'fit_prior': True, 'force_alpha': False}
5         0.649105     {'alpha': 0.0, 'fit_prior': True, 'force_alpha': False}
9         0.649105  {'alpha': 1e-100, 'fit_prior': True, 'force_alpha': False}
8         0.630203   {'alpha': 1e-100, 'fit_prior': True, 'force_alpha': True}
0         0.155069      {'alpha': 0.0, 'fit_prior': True, 'force_alpha': True}
2         0.155069     {'alpha': 0.0, 'fit_prior': False, 'force_alpha': True}
4         0.155069      {'alpha': 0.0, 'fit_prior': True, 'force_alpha': True}
6         0.155069     {'alpha': 0.0, 'fit_prior': False, 'force_alpha': True}

In [74]:
nb = MultinomialNB(alpha= 0.0, fit_prior= False, force_alpha= False)
nb.fit(x_train, y_train)
y_pred = nb.predict(x_test)
print(classification_report(y_test , y_pred, digits= 4))

               precision    recall  f1-score   support

     analysis     0.4480    0.5600    0.4978       100
  application     0.3596    0.4100    0.3832       100
comprehension     0.4186    0.5400    0.4716       100
   evaluation     0.5270    0.3900    0.4483       100
    knowledge     0.5000    0.3200    0.3902       100
    synthesis     0.4574    0.4300    0.4433       100

     accuracy                         0.4417       600
    macro avg     0.4518    0.4417    0.4391       600
 weighted avg     0.4518    0.4417    0.4391       600

In [97]:
question = 'What are different types of single level indexing?'
processed_q = preprocess_text(question)
tfidf_q = vectorizer.transform([processed_q])
tfidf_q = pd.DataFrame(tfidf_q.toarray(), columns=vectorizer.get_feature_names_out())



# Adding linguistic features
q_ling_features = pd.DataFrame([extract_linguistic_features(question)])

# Concatenate DataFrames
token_q = pd.concat([q_ling_features, tfidf_q], axis=1)

print(nb.predict(tfidf_q))

['analysis']