# Import Libraries

In [1]:
import pandas as pd
import numpy as np
import h5py
import spacy
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.model_selection import GridSearchCV, cross_val_score
from sklearn.ensemble import RandomForestClassifier
import matplotlib.pyplot as plt
import os
import string as st
import tensorflow as tf
from sklearn.decomposition import PCA, TruncatedSVD
from imblearn.ensemble import BalancedBaggingClassifier
from imblearn.combine import SMOTETomek
from imblearn.under_sampling import NearMiss
from sklearn.tree import DecisionTreeClassifier
from xgboost import XGBClassifier
from collections import Counter
from sklearn.svm import SVC, LinearSVC
from sklearn.naive_bayes import MultinomialNB

import warnings
warnings.filterwarnings('ignore')
pd.set_option('display.max_columns', None)  # Show all columns
pd.set_option('display.max_rows', None)  # Show all rows
pd.set_option('display.max_colwidth', None)  # Show full content in each cell
pd.set_option('display.width', 1000)  # Set max width

# Load spaCy's English model
nlp = spacy.load('en_core_web_sm')

# Linguistic Modules

In [2]:
def preprocess_text(text):
    # Define interrogative words to KEEP
    interrogatives = {"what", "why", "how", "who", "where", "when", "which", "whom", "whose", "no", "not",
                    "very" ,"too" ,"too" ,"just", "if", "but", "however", "without", "like"}
    custom_stopwords = set(nlp.Defaults.stop_words)
    custom_stopwords -= interrogatives

    doc = nlp(text.lower().strip())  # Lowercase and remove whitespace
    
# Process tokens: lemmatize, filter stopwords/punct/numbers, keep interrogatives
    tokens = [
        token.lemma_ 
        for token in doc 
        if (
            (not token.is_stop or token.text in interrogatives) and  # Keep interrogatives
            not token.is_punct and token.is_alpha                                  # Remove punctuation
            # (token.is_alpha or token.like_num)                       # Keep words/numbers
        )
    ]

    return ' '.join(tokens)

In [3]:
def extract_linguistic_features(text):
    doc = nlp(text)
    features = {
        'num_verbs': len([token for token in doc if token.pos_ == 'VERB']),
        'num_nouns': len([token for token in doc if token.pos_ == 'NOUN']),
        'sentence_length': len(doc),
        'number_present': any(token.pos_ == 'NUM' for token in doc)
    }
    return features

# Pre-Processing

### Import Data

In [ ]:
mapping = {
    'knowledge': 'knowledge',
    'remember': 'knowledge',
    'comprehension': 'comprehension',
    'understand': 'comprehension',
    'application': 'application',
    'apply': 'application',
    'analysis': 'analysis',
    'analyse': 'analysis',
    'evaluation': 'evaluation',
    'evaluate': 'evaluation',
    'synthesis': 'synthesis',
    'create': 'synthesis'
}
label_mapper = {
    'BT1' : 'knowledge',
    'BT2' : 'comprehension',
    'BT3' : 'application',
    'BT4' : 'analysis',
    'BT5' : 'synthesis',
    'BT6' : 'evaluation'
}


# Load dataset
df = pd.DataFrame()
for i in [1,2,3,4,5]:
    q_df = pd.read_csv(os.getcwd().replace('notebook' , 'dataset') + '/dataset' + str(i) + '.csv')
    q_df['dataset_id'] = i
    df = pd.concat([df , q_df])

# Apply preprocessing
df['label'] = df['label'].replace(label_mapper)
df['label'] = df['label'].str.lower()
df['label'] = df['label'].replace(mapping)

df['processed_question'] = df['question'].apply(preprocess_text)
df['processed_question'] = [''.join(text) for text in df['processed_question']]

1
label
Analysis         100
Knowledge        100
Comprehension    100
Evaluation       100
Synthesis        100
Application      100
Name: count, dtype: int64
2
label
COMPREHENSION    135
APPLY             72
EVALUATE          57
ANALYSIS          56
KNOWLEDGE         50
SYNTHESIS         45
Name: count, dtype: int64
3
label
COMPREHENSION    37
EVALUATE         33
ANALYSIS         30
SYNTHESIS        29
APPLY            29
KNOWLEDGE        23
Name: count, dtype: int64
4
label
Synthesis        29
Knowledge        22
Evaluation       21
Comprehension    20
Analysis         19
Application      15
Name: count, dtype: int64
5
label
COMPREHENSION    669
KNOWLEDGE        149
EVALUATION       107
APPLICATION      100
ANALYSIS          99
SYNTHESIS         76
Name: count, dtype: int64

## Tokenize

### Vectorization

In [5]:
# token_pattern: words of 2+ word-chars, but not all digits
token_pattern = r"(?u)\b[a-zA-Z]{3,}\b"

vectorizer = TfidfVectorizer(
    min_df= 5 , ngram_range=(1,2), use_idf= True, norm= 'l2', token_pattern= token_pattern
                             )
tfidf = vectorizer.fit_transform(df['processed_question'])

# Convert TF-IDF sparse matrix to DataFrame with appropriate column names
tfidf_df = pd.DataFrame(tfidf.toarray(), columns= vectorizer.get_feature_names_out(), index=df.index)

print('Training Shape: ' + str(tfidf_df.shape))

Training Shape: (2522, 1028)

# Feature Extraction

### Adding Linguistic Features

Execute if linguistic features like count for verb,noun,etc needed

In [7]:
# Adding linguistic features
ling_features = df['question'].apply(extract_linguistic_features).apply(pd.Series)

In [167]:
# Concatenate DataFrames
token_df = pd.concat([ling_features, tfidf_df], axis=1)

token_df.columns = token_df.columns.map(str)

In [168]:
token_df.head(5)

,num_verbs,num_nouns,sentence_length,number_present,action,algorithm,analysis,analysis determine,analyze,analyze datum,animal,app,application,apply,apply principle,approach,appropriate,architectural,area,argue,argument,art,article,artistic,assess,assess value,association,author,base,basic,behavior,benefit,book,break,break complex,build,building,business,calculate,calculus,campaign,car,case,categorize,categorize different,cause,change,character,characteristic,chemical,chemical reaction,choice,choose,city,class,classify,classify different,climate,cognitive,combine,combine create,community,compare,compare contrast,complex,component,compose,computer,concept,concept analyze,conclude,conclusion,conclusion draw,conduct,consequence,construct,consumer,contemporary,context,contradictory,contradictory information,contrast,convince,correct,correct usage,country,create,create illustrated,criterion,cultural,customer,cycle,data,datum,datum identify,debate,decide,decision,defend,define,definition,demand,demonstrate,demonstrate correct,demonstrate step,derive,derive equation,describe,design,determine,develop,develop new,development,diagram,differ,difference,different,different type,differentiate,discriminate,discuss,distinguish,document,draw,draw combine,economic,ecosystem,education,educational,effect,effect different,effective,efficient,element,energy,engineering,enhance,environmental,equation,equation calculate,ethical,evaluate,event,examine,examine datum,example,exercise,experience,experiment,explain,explain concept,explain what,fact,factor,famous,favorite,feature,find,finding,flowchart,follow,food,form,formula,formulate,friendly,function,functional,future,generalize,generalize historical,generate,give,good,grade,group,growth,happen,historical,historical event,history,how,how break,how build,how classify,how create,how derive,how design,how develop,how experiment,how generate,how infer,how old,how relate,how use,human,hypothesis,idea,identify,identify contradictory,identify miss,identify redundant,illustrate,illustrate process,illustrated,illustrated diagram,impact,implication,importance,important,improve,infer,influence,information,information complex,innovative,integrate,intelligence,interaction,interpret,invent,invent new,investigate,involve,involve compose,judge,justify,key,knowledge,label,language,law,learn,let,let discuss,life,like,line,list,literary,literature,main,major,make,management,market,marketing,marketing strategy,mathematical,mean,meaning,measure,medical,medium,method,miss,miss information,model,modern,modification,modify,movement,movie,music,narrative,new,new method,new software,not,novel,object,old,olympic,online,order,outcome,outline,paper,paraphrase,part,particular,pattern,performance,perspective,physics,piece,plan,plant,platform,play,poem,point,policy,political,population,position,potential,predict,predict future,predict outcome,present,principle,problem,problem involve,procedure,process,product,program,programming,project,provide,psychological,psychology,public,question,quote,rank,rate,reaction,recall,recite,recognize,recognize subjectivity,recommend,redundant,redundant information,relate,relate knowledge,relationship,relationship different,relevant,renewable,renewable energy,research,research question,restate,result,rewrite,role,science,scientific,scientific method,select,select appropriate,select relevant,set,social,social medium,societal,society,sociology,software,solution,solve,sound,source,specie,speech,stage,state,statement,statistical,step,step identify,step involve,story,strategy,strategy use,structure,student,study,style,subjectivity,summarize,supply,support,survey,sustainable,system,tabulate,team,technique,technique use,technological,technology,tell,term,test,test hypothesis,theory,think,time,translate,transportation,trend,type,understand,understanding,urban,usage,usage scientific,use,use identify,use knowledge,use statistical,user,value,variable,verify,verify value,viewpoint,visual,volume,water,way,website,what,what association,what conclusion,what happen,what step,what strategy,what technique,when,which,who,why,word,work,write,year
0,1,3,14,False,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.887648,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.460522,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2,3,10,False,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.677555,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.735472,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1,2,4,False,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1,2,6,True,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.758521,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.651648,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1,1,3,False,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

### Label Balancing

### NOTE: Run below resampling if dataset 1 , 4 or both included

In [9]:
mask = df['dataset_id'].isin([5])
to_us_df   = df[mask]
to_keep_df = df[~mask]

to_keep = vectorizer.transform(to_keep_df['processed_question'])
to_us = vectorizer.transform(to_us_df['processed_question'])

df_to_us = pd.DataFrame(
    to_us.toarray(), 
    columns=vectorizer.get_feature_names_out()
)

df_to_keep = pd.DataFrame(
    to_keep.toarray(), 
    columns=vectorizer.get_feature_names_out()
)
df_to_keep['bt_label'] = to_keep_df['label'].values

x , y = df_to_us , to_us_df['label']
x_resampled , y_resampled = NearMiss().fit_resample(x , y)


x_resampled['bt_label'] = y_resampled

df_final = pd.concat([df_to_keep, x_resampled], ignore_index=True)

print(df_final.shape)
print(df_final['bt_label'].value_counts())

x = df_final.drop(columns= 'bt_label')
y = df_final['bt_label']

(1778, 1029)
bt_label
comprehension    368
application      292
evaluation       287
analysis         281
synthesis        279
knowledge        271
Name: count, dtype: int64

### Else run below, no need for resampling

In [8]:
x , y = tfidf_df , df['label']
print(x.shape)
print(y.value_counts())

# x , y = x_resampled , y_resampled

(2522, 1028)
label
comprehension    961
knowledge        344
evaluation       318
application      316
analysis         304
synthesis        279
Name: count, dtype: int64

# Modelling

## Basic Machine Learning

In [10]:
x_train , x_test , y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=34 , stratify= y)

### Random Forest

In [11]:
params = {
    'n_estimators' : [2 , 5 , 10 , 100, 250 , 500],
    'criterion' : ['gini' , 'entropy'],
    # 'max_depth' : [None , 10 , 100 , 250 , 500]
}
param_search = GridSearchCV(estimator= RandomForestClassifier(), param_grid= params, cv=5, n_jobs= -1, verbose= 2)

param_search.fit(x, y)

cv_results = pd.DataFrame(param_search.cv_results_)
cv_results = cv_results[["mean_test_score", "params"]].head(10).sort_values(by="mean_test_score", ascending=False)

cv_results

Fitting 5 folds for each of 12 candidates, totalling 60 fits
[CV] END .....................criterion=gini, n_estimators=2; total time=   0.1s
[CV] END .....................criterion=gini, n_estimators=2; total time=   0.1s
[CV] END ....................criterion=gini, n_estimators=10; total time=   0.1s
[CV] END .....................criterion=gini, n_estimators=2; total time=   0.1s
[CV] END .....................criterion=gini, n_estimators=5; total time=   0.1s
[CV] END .....................criterion=gini, n_estimators=5; total time=   0.1s
[CV] END .....................criterion=gini, n_estimators=2; total time=   0.1s
[CV] END .....................criterion=gini, n_estimators=2; total time=   0.1s
[CV] END ....................criterion=gini, n_estimators=10; total time=   0.1s
[CV] END ....................criterion=gini, n_estimators=10; total time=   0.1s
[CV] END ....................criterion=gini, n_estimators=10; total time=   0.1s
[CV] END .....................criterion=gini, n_estimators=5; total time=   0.1s
[CV] END .....................criterion=gini, n_estimators=5; total time=   0.1s
[CV] END .....................criterion=gini, n_estimators=5; total time=   0.1s
[CV] END ....................criterion=gini, n_estimators=10; total time=   0.1s
[CV] END ...................criterion=gini, n_estimators=100; total time=   0.7s
[CV] END ...................criterion=gini, n_estimators=100; total time=   0.7s
[CV] END ...................criterion=gini, n_estimators=100; total time=   0.7s
[CV] END ...................criterion=gini, n_estimators=100; total time=   0.6s
[CV] END ...................criterion=gini, n_estimators=100; total time=   0.7s
[CV] END ..................criterion=entropy, n_estimators=2; total time=   0.1s
[CV] END ..................criterion=entropy, n_estimators=2; total time=   0.1s
[CV] END ..................criterion=entropy, n_estimators=2; total time=   0.1s
[CV] END ..................criterion=entropy, n_estimators=2; total time=   0.1s
[CV] END ..................criterion=entropy, n_estimators=2; total time=   0.1s
[CV] END ..................criterion=entropy, n_estimators=5; total time=   0.1s
[CV] END ...................criterion=gini, n_estimators=250; total time=   1.7s
[CV] END ..................criterion=entropy, n_estimators=5; total time=   0.1s
[CV] END ...................criterion=gini, n_estimators=250; total time=   1.7s
[CV] END ..................criterion=entropy, n_estimators=5; total time=   0.1s
[CV] END ...................criterion=gini, n_estimators=250; total time=   1.8s
[CV] END ..................criterion=entropy, n_estimators=5; total time=   0.1s
[CV] END ...................criterion=gini, n_estimators=250; total time=   1.9s
[CV] END ...................criterion=gini, n_estimators=250; total time=   1.8s
[CV] END ..................criterion=entropy, n_estimators=5; total time=   0.1s
[CV] END .................criterion=entropy, n_estimators=10; total time=   0.1s
[CV] END .................criterion=entropy, n_estimators=10; total time=   0.1s
[CV] END .................criterion=entropy, n_estimators=10; total time=   0.1s
[CV] END .................criterion=entropy, n_estimators=10; total time=   0.1s
[CV] END .................criterion=entropy, n_estimators=10; total time=   0.1s
[CV] END ................criterion=entropy, n_estimators=100; total time=   0.8s
[CV] END ................criterion=entropy, n_estimators=100; total time=   0.8s
[CV] END ................criterion=entropy, n_estimators=100; total time=   0.8s
[CV] END ................criterion=entropy, n_estimators=100; total time=   0.8s
[CV] END ................criterion=entropy, n_estimators=100; total time=   0.9s
[CV] END ...................criterion=gini, n_estimators=500; total time=   3.5s
[CV] END ...................criterion=gini, n_estimators=500; total time=   3.2s
[CV] END ................criterion=entropy, n_estimators=250; total time=   1.7s
[CV] END ...................criterion=gini, n_estimators=500; total time=   3.6s
[CV] END ...................criterion=gini, n_estimators=500; total time=   3.6s
[CV] END ...................criterion=gini, n_estimators=500; total time=   3.7s
[CV] END ................criterion=entropy, n_estimators=250; total time=   1.8s
[CV] END ................criterion=entropy, n_estimators=250; total time=   2.0s
[CV] END ................criterion=entropy, n_estimators=250; total time=   2.0s
[CV] END ................criterion=entropy, n_estimators=250; total time=   2.0s
[CV] END ................criterion=entropy, n_estimators=500; total time=   2.9s
[CV] END ................criterion=entropy, n_estimators=500; total time=   2.6s
[CV] END ................criterion=entropy, n_estimators=500; total time=   2.6s
[CV] END ................criterion=entropy, n_estimators=500; total time=   2.5s
[CV] END ................criterion=entropy, n_estimators=500; total time=   2.4s

   mean_test_score                                         params
4         0.730625     {'criterion': 'gini', 'n_estimators': 250}
5         0.728935     {'criterion': 'gini', 'n_estimators': 500}
3         0.725556     {'criterion': 'gini', 'n_estimators': 100}
9         0.724447  {'criterion': 'entropy', 'n_estimators': 100}
2         0.707566      {'criterion': 'gini', 'n_estimators': 10}
8         0.695768   {'criterion': 'entropy', 'n_estimators': 10}
7         0.658644    {'criterion': 'entropy', 'n_estimators': 5}
1         0.656927       {'criterion': 'gini', 'n_estimators': 5}
0         0.596767       {'criterion': 'gini', 'n_estimators': 2}
6         0.590544    {'criterion': 'entropy', 'n_estimators': 2}

In [24]:
classifier = RandomForestClassifier(n_estimators=250 , criterion= 'gini', n_jobs= -1)
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
print(classification_report(y_test , y_pred))

               precision    recall  f1-score   support

     analysis       0.92      0.80      0.86        56
  application       0.73      0.75      0.74        59
comprehension       0.79      0.72      0.75        74
   evaluation       0.84      0.81      0.82        57
    knowledge       0.62      0.85      0.72        54
    synthesis       0.86      0.79      0.82        56

     accuracy                           0.78       356
    macro avg       0.79      0.79      0.79       356
 weighted avg       0.79      0.78      0.78       356

In [25]:
question = 'How many total disk access is needed to search a record using two level indexing?'
processed_q = preprocess_text(question)
tfidf_q = vectorizer.transform([processed_q])
tfidf_q = pd.DataFrame(tfidf_q.toarray(), columns=vectorizer.get_feature_names_out())



# Adding linguistic features
q_ling_features = pd.DataFrame([extract_linguistic_features(question)])

# Concatenate DataFrames
token_q = pd.concat([q_ling_features, tfidf_q], axis=1)

print(classifier.predict(tfidf_q))

['application']

### Decision Tree

In [14]:
params = {
    'min_samples_split' : [2 , 5 , 10 , 50 , 100],
    'criterion' : ['gini' , 'entropy'],
    'max_depth' : [None , 5 , 10 , 50 , 100 , 250 , 500]
}
param_search = GridSearchCV(estimator= DecisionTreeClassifier(), param_grid= params, cv=5, n_jobs= -1, verbose= 2)

param_search.fit(x , y)

cv_results = pd.DataFrame(param_search.cv_results_)
cv_results = cv_results[["mean_test_score", "params"]].head(10).sort_values(by="mean_test_score", ascending=False)

cv_results

Fitting 5 folds for each of 70 candidates, totalling 350 fits
[CV] END criterion=gini, max_depth=None, min_samples_split=2; total time=   0.1s
[CV] END criterion=gini, max_depth=None, min_samples_split=2; total time=   0.1s
[CV] END criterion=gini, max_depth=None, min_samples_split=2; total time=   0.1s
[CV] END criterion=gini, max_depth=None, min_samples_split=2; total time=   0.1s
[CV] END criterion=gini, max_depth=None, min_samples_split=2; total time=   0.1s
[CV] END criterion=gini, max_depth=None, min_samples_split=5; total time=   0.1s
[CV] END criterion=gini, max_depth=None, min_samples_split=5; total time=   0.1s
[CV] END criterion=gini, max_depth=None, min_samples_split=5; total time=   0.1s
[CV] END criterion=gini, max_depth=None, min_samples_split=5; total time=   0.1s
[CV] END criterion=gini, max_depth=None, min_samples_split=5; total time=   0.1s
[CV] END criterion=gini, max_depth=None, min_samples_split=10; total time=   0.1s
[CV] END criterion=gini, max_depth=None, min_samples_split=10; total time=   0.1s
[CV] END criterion=gini, max_depth=None, min_samples_split=10; total time=   0.1s
[CV] END criterion=gini, max_depth=None, min_samples_split=10; total time=   0.1s
[CV] END criterion=gini, max_depth=None, min_samples_split=10; total time=   0.1s
[CV] END criterion=gini, max_depth=None, min_samples_split=50; total time=   0.1s
[CV] END criterion=gini, max_depth=None, min_samples_split=50; total time=   0.1s
[CV] END criterion=gini, max_depth=None, min_samples_split=50; total time=   0.1s
[CV] END criterion=gini, max_depth=None, min_samples_split=50; total time=   0.1s
[CV] END criterion=gini, max_depth=None, min_samples_split=50; total time=   0.1s
[CV] END criterion=gini, max_depth=None, min_samples_split=100; total time=   0.1s
[CV] END criterion=gini, max_depth=None, min_samples_split=100; total time=   0.1s
[CV] END criterion=gini, max_depth=None, min_samples_split=100; total time=   0.1s
[CV] END criterion=gini, max_depth=None, min_samples_split=100; total time=   0.1s
[CV] END ...criterion=gini, max_depth=5, min_samples_split=2; total time=   0.1s
[CV] END ...criterion=gini, max_depth=5, min_samples_split=2; total time=   0.1s
[CV] END ...criterion=gini, max_depth=5, min_samples_split=5; total time=   0.1s
[CV] END ...criterion=gini, max_depth=5, min_samples_split=2; total time=   0.1s
[CV] END ...criterion=gini, max_depth=5, min_samples_split=2; total time=   0.1s
[CV] END ...criterion=gini, max_depth=5, min_samples_split=2; total time=   0.1s
[CV] END ...criterion=gini, max_depth=5, min_samples_split=5; total time=   0.1s
[CV] END ...criterion=gini, max_depth=5, min_samples_split=5; total time=   0.1s
[CV] END criterion=gini, max_depth=None, min_samples_split=100; total time=   0.1s
[CV] END ...criterion=gini, max_depth=5, min_samples_split=5; total time=   0.1s
[CV] END ...criterion=gini, max_depth=5, min_samples_split=5; total time=   0.1s
[CV] END ..criterion=gini, max_depth=5, min_samples_split=10; total time=   0.0s
[CV] END ..criterion=gini, max_depth=5, min_samples_split=10; total time=   0.0s
[CV] END ..criterion=gini, max_depth=5, min_samples_split=10; total time=   0.0s
[CV] END ..criterion=gini, max_depth=5, min_samples_split=10; total time=   0.0s
[CV] END ..criterion=gini, max_depth=5, min_samples_split=50; total time=   0.0s
[CV] END ..criterion=gini, max_depth=5, min_samples_split=50; total time=   0.0s
[CV] END ..criterion=gini, max_depth=5, min_samples_split=10; total time=   0.0s
[CV] END ..criterion=gini, max_depth=5, min_samples_split=50; total time=   0.0s
[CV] END ..criterion=gini, max_depth=5, min_samples_split=50; total time=   0.0s
[CV] END ..criterion=gini, max_depth=5, min_samples_split=50; total time=   0.0s
[CV] END .criterion=gini, max_depth=5, min_samples_split=100; total time=   0.0s
[CV] END .criterion=gini, max_depth=5, min_samples_split=100; total time=   0.0s
[CV] END .criterion=gini, max_depth=5, min_samples_split=100; total time=   0.0s
[CV] END .criterion=gini, max_depth=5, min_samples_split=100; total time=   0.0s
[CV] END ..criterion=gini, max_depth=10, min_samples_split=2; total time=   0.1s
[CV] END ..criterion=gini, max_depth=10, min_samples_split=2; total time=   0.1s
[CV] END .criterion=gini, max_depth=5, min_samples_split=100; total time=   0.1s
[CV] END ..criterion=gini, max_depth=10, min_samples_split=2; total time=   0.1s
[CV] END ..criterion=gini, max_depth=10, min_samples_split=2; total time=   0.1s
[CV] END ..criterion=gini, max_depth=10, min_samples_split=2; total time=   0.1s
[CV] END ..criterion=gini, max_depth=10, min_samples_split=5; total time=   0.1s
[CV] END ..criterion=gini, max_depth=10, min_samples_split=5; total time=   0.1s
[CV] END ..criterion=gini, max_depth=10, min_samples_split=5; total time=   0.1s
[CV] END .criterion=gini, max_depth=10, min_samples_split=10; total time=   0.1s
[CV] END ..criterion=gini, max_depth=10, min_samples_split=5; total time=   0.1s
[CV] END ..criterion=gini, max_depth=10, min_samples_split=5; total time=   0.1s
[CV] END .criterion=gini, max_depth=10, min_samples_split=10; total time=   0.1s
[CV] END .criterion=gini, max_depth=10, min_samples_split=10; total time=   0.1s
[CV] END .criterion=gini, max_depth=10, min_samples_split=10; total time=   0.1s
[CV] END .criterion=gini, max_depth=10, min_samples_split=50; total time=   0.1s
[CV] END .criterion=gini, max_depth=10, min_samples_split=10; total time=   0.1s
[CV] END .criterion=gini, max_depth=10, min_samples_split=50; total time=   0.1s
[CV] END .criterion=gini, max_depth=10, min_samples_split=50; total time=   0.1s
[CV] END criterion=gini, max_depth=10, min_samples_split=100; total time=   0.1s
[CV] END .criterion=gini, max_depth=10, min_samples_split=50; total time=   0.1s
[CV] END criterion=gini, max_depth=10, min_samples_split=100; total time=   0.1s
[CV] END .criterion=gini, max_depth=10, min_samples_split=50; total time=   0.1s
[CV] END criterion=gini, max_depth=10, min_samples_split=100; total time=   0.1s
[CV] END criterion=gini, max_depth=10, min_samples_split=100; total time=   0.1s
[CV] END criterion=gini, max_depth=10, min_samples_split=100; total time=   0.1s
[CV] END ..criterion=gini, max_depth=50, min_samples_split=2; total time=   0.1s
[CV] END ..criterion=gini, max_depth=50, min_samples_split=2; total time=   0.1s
[CV] END ..criterion=gini, max_depth=50, min_samples_split=2; total time=   0.1s
[CV] END ..criterion=gini, max_depth=50, min_samples_split=5; total time=   0.1s
[CV] END ..criterion=gini, max_depth=50, min_samples_split=5; total time=   0.1s
[CV] END ..criterion=gini, max_depth=50, min_samples_split=2; total time=   0.1s
[CV] END ..criterion=gini, max_depth=50, min_samples_split=2; total time=   0.1s
[CV] END ..criterion=gini, max_depth=50, min_samples_split=5; total time=   0.1s
[CV] END ..criterion=gini, max_depth=50, min_samples_split=5; total time=   0.1s
[CV] END .criterion=gini, max_depth=50, min_samples_split=10; total time=   0.1s
[CV] END .criterion=gini, max_depth=50, min_samples_split=10; total time=   0.1s
[CV] END ..criterion=gini, max_depth=50, min_samples_split=5; total time=   0.1s
[CV] END .criterion=gini, max_depth=50, min_samples_split=50; total time=   0.1s
[CV] END .criterion=gini, max_depth=50, min_samples_split=10; total time=   0.1s
[CV] END .criterion=gini, max_depth=50, min_samples_split=50; total time=   0.1s
[CV] END .criterion=gini, max_depth=50, min_samples_split=10; total time=   0.1s
[CV] END .criterion=gini, max_depth=50, min_samples_split=10; total time=   0.1s
[CV] END .criterion=gini, max_depth=50, min_samples_split=50; total time=   0.1s
[CV] END criterion=gini, max_depth=50, min_samples_split=100; total time=   0.1s
[CV] END .criterion=gini, max_depth=50, min_samples_split=50; total time=   0.1s
[CV] END criterion=gini, max_depth=50, min_samples_split=100; total time=   0.1s
[CV] END .criterion=gini, max_depth=50, min_samples_split=50; total time=   0.1s
[CV] END .criterion=gini, max_depth=100, min_samples_split=2; total time=   0.1s
[CV] END criterion=gini, max_depth=50, min_samples_split=100; total time=   0.1s
[CV] END criterion=gini, max_depth=50, min_samples_split=100; total time=   0.1s
[CV] END .criterion=gini, max_depth=100, min_samples_split=2; total time=   0.1s
[CV] END .criterion=gini, max_depth=100, min_samples_split=2; total time=   0.1s
[CV] END criterion=gini, max_depth=50, min_samples_split=100; total time=   0.1s
[CV] END .criterion=gini, max_depth=100, min_samples_split=5; total time=   0.1s
[CV] END .criterion=gini, max_depth=100, min_samples_split=2; total time=   0.1s
[CV] END .criterion=gini, max_depth=100, min_samples_split=5; total time=   0.1s
[CV] END .criterion=gini, max_depth=100, min_samples_split=2; total time=   0.1s
[CV] END .criterion=gini, max_depth=100, min_samples_split=5; total time=   0.1s
[CV] END criterion=gini, max_depth=100, min_samples_split=10; total time=   0.1s
[CV] END criterion=gini, max_depth=100, min_samples_split=10; total time=   0.1s
[CV] END .criterion=gini, max_depth=100, min_samples_split=5; total time=   0.1s
[CV] END .criterion=gini, max_depth=100, min_samples_split=5; total time=   0.1s
[CV] END criterion=gini, max_depth=100, min_samples_split=10; total time=   0.1s
[CV] END criterion=gini, max_depth=100, min_samples_split=50; total time=   0.1s
[CV] END criterion=gini, max_depth=100, min_samples_split=10; total time=   0.1s
[CV] END criterion=gini, max_depth=100, min_samples_split=50; total time=   0.1s
[CV] END criterion=gini, max_depth=100, min_samples_split=10; total time=   0.1s
[CV] END criterion=gini, max_depth=100, min_samples_split=50; total time=   0.1s
[CV] END criterion=gini, max_depth=100, min_samples_split=100; total time=   0.1s
[CV] END criterion=gini, max_depth=100, min_samples_split=50; total time=   0.1s
[CV] END criterion=gini, max_depth=100, min_samples_split=100; total time=   0.1s
[CV] END criterion=gini, max_depth=100, min_samples_split=100; total time=   0.1s
[CV] END criterion=gini, max_depth=100, min_samples_split=50; total time=   0.1s
[CV] END .criterion=gini, max_depth=250, min_samples_split=2; total time=   0.1s
[CV] END criterion=gini, max_depth=100, min_samples_split=100; total time=   0.1s
[CV] END .criterion=gini, max_depth=250, min_samples_split=2; total time=   0.1s
[CV] END criterion=gini, max_depth=100, min_samples_split=100; total time=   0.1s
[CV] END .criterion=gini, max_depth=250, min_samples_split=2; total time=   0.1s
[CV] END .criterion=gini, max_depth=250, min_samples_split=5; total time=   0.2s
[CV] END .criterion=gini, max_depth=250, min_samples_split=2; total time=   0.1s
[CV] END .criterion=gini, max_depth=250, min_samples_split=5; total time=   0.1s
[CV] END .criterion=gini, max_depth=250, min_samples_split=5; total time=   0.1s
[CV] END criterion=gini, max_depth=250, min_samples_split=10; total time=   0.1s
[CV] END .criterion=gini, max_depth=250, min_samples_split=2; total time=   0.2s
[CV] END .criterion=gini, max_depth=250, min_samples_split=5; total time=   0.1s
[CV] END criterion=gini, max_depth=250, min_samples_split=10; total time=   0.1s
[CV] END criterion=gini, max_depth=250, min_samples_split=50; total time=   0.1s
[CV] END .criterion=gini, max_depth=250, min_samples_split=5; total time=   0.1s
[CV] END criterion=gini, max_depth=250, min_samples_split=10; total time=   0.1s
[CV] END criterion=gini, max_depth=250, min_samples_split=50; total time=   0.1s
[CV] END criterion=gini, max_depth=250, min_samples_split=10; total time=   0.1s
[CV] END criterion=gini, max_depth=250, min_samples_split=50; total time=   0.1s
[CV] END criterion=gini, max_depth=250, min_samples_split=50; total time=   0.1s
[CV] END criterion=gini, max_depth=250, min_samples_split=10; total time=   0.1s
[CV] END criterion=gini, max_depth=250, min_samples_split=100; total time=   0.1s
[CV] END criterion=gini, max_depth=250, min_samples_split=100; total time=   0.1s
[CV] END criterion=gini, max_depth=250, min_samples_split=50; total time=   0.1s
[CV] END criterion=gini, max_depth=250, min_samples_split=100; total time=   0.1s
[CV] END criterion=gini, max_depth=250, min_samples_split=100; total time=   0.1s
[CV] END .criterion=gini, max_depth=500, min_samples_split=2; total time=   0.1s
[CV] END .criterion=gini, max_depth=500, min_samples_split=2; total time=   0.1s
[CV] END .criterion=gini, max_depth=500, min_samples_split=2; total time=   0.1s
[CV] END criterion=gini, max_depth=250, min_samples_split=100; total time=   0.1s
[CV] END .criterion=gini, max_depth=500, min_samples_split=5; total time=   0.1s
[CV] END .criterion=gini, max_depth=500, min_samples_split=2; total time=   0.1s
[CV] END .criterion=gini, max_depth=500, min_samples_split=5; total time=   0.1s
[CV] END .criterion=gini, max_depth=500, min_samples_split=2; total time=   0.1s
[CV] END .criterion=gini, max_depth=500, min_samples_split=5; total time=   0.1s
[CV] END criterion=gini, max_depth=500, min_samples_split=10; total time=   0.2s
[CV] END criterion=gini, max_depth=500, min_samples_split=10; total time=   0.1s
[CV] END criterion=gini, max_depth=500, min_samples_split=10; total time=   0.1s
[CV] END .criterion=gini, max_depth=500, min_samples_split=5; total time=   0.2s
[CV] END criterion=gini, max_depth=500, min_samples_split=50; total time=   0.1s
[CV] END .criterion=gini, max_depth=500, min_samples_split=5; total time=   0.2s
[CV] END criterion=gini, max_depth=500, min_samples_split=50; total time=   0.1s
[CV] END criterion=gini, max_depth=500, min_samples_split=10; total time=   0.1s
[CV] END criterion=gini, max_depth=500, min_samples_split=100; total time=   0.1s
[CV] END criterion=gini, max_depth=500, min_samples_split=10; total time=   0.2s
[CV] END criterion=gini, max_depth=500, min_samples_split=50; total time=   0.2s
[CV] END criterion=gini, max_depth=500, min_samples_split=50; total time=   0.1s
[CV] END criterion=gini, max_depth=500, min_samples_split=50; total time=   0.1s
[CV] END criterion=gini, max_depth=500, min_samples_split=100; total time=   0.2s
[CV] END criterion=gini, max_depth=500, min_samples_split=100; total time=   0.1s
[CV] END criterion=entropy, max_depth=None, min_samples_split=2; total time=   0.1s
[CV] END criterion=gini, max_depth=500, min_samples_split=100; total time=   0.1s
[CV] END criterion=entropy, max_depth=None, min_samples_split=2; total time=   0.1s
[CV] END criterion=entropy, max_depth=None, min_samples_split=5; total time=   0.1s
[CV] END criterion=gini, max_depth=500, min_samples_split=100; total time=   0.1s
[CV] END criterion=entropy, max_depth=None, min_samples_split=2; total time=   0.1s
[CV] END criterion=entropy, max_depth=None, min_samples_split=2; total time=   0.1s
[CV] END criterion=entropy, max_depth=None, min_samples_split=5; total time=   0.1s
[CV] END criterion=entropy, max_depth=None, min_samples_split=2; total time=   0.1s
[CV] END criterion=entropy, max_depth=None, min_samples_split=10; total time=   0.1s
[CV] END criterion=entropy, max_depth=None, min_samples_split=5; total time=   0.1s
[CV] END criterion=entropy, max_depth=None, min_samples_split=5; total time=   0.1s
[CV] END criterion=entropy, max_depth=None, min_samples_split=10; total time=   0.1s
[CV] END criterion=entropy, max_depth=None, min_samples_split=5; total time=   0.1s
[CV] END criterion=entropy, max_depth=None, min_samples_split=50; total time=   0.1s
[CV] END criterion=entropy, max_depth=None, min_samples_split=10; total time=   0.1s
[CV] END criterion=entropy, max_depth=None, min_samples_split=10; total time=   0.1s
[CV] END criterion=entropy, max_depth=None, min_samples_split=50; total time=   0.1s
[CV] END criterion=entropy, max_depth=None, min_samples_split=10; total time=   0.1s
[CV] END criterion=entropy, max_depth=None, min_samples_split=50; total time=   0.1s
[CV] END criterion=entropy, max_depth=None, min_samples_split=100; total time=   0.1s
[CV] END criterion=entropy, max_depth=None, min_samples_split=50; total time=   0.1s
[CV] END criterion=entropy, max_depth=5, min_samples_split=2; total time=   0.1s
[CV] END criterion=entropy, max_depth=5, min_samples_split=2; total time=   0.1s
[CV] END criterion=entropy, max_depth=None, min_samples_split=100; total time=   0.1s
[CV] END criterion=entropy, max_depth=None, min_samples_split=50; total time=   0.1s
[CV] END criterion=entropy, max_depth=None, min_samples_split=100; total time=   0.1s
[CV] END criterion=entropy, max_depth=None, min_samples_split=100; total time=   0.1s
[CV] END criterion=entropy, max_depth=5, min_samples_split=2; total time=   0.1s
[CV] END criterion=entropy, max_depth=5, min_samples_split=2; total time=   0.0s
[CV] END criterion=entropy, max_depth=5, min_samples_split=2; total time=   0.1s
[CV] END criterion=entropy, max_depth=5, min_samples_split=5; total time=   0.1s
[CV] END criterion=entropy, max_depth=5, min_samples_split=5; total time=   0.0s
[CV] END criterion=entropy, max_depth=None, min_samples_split=100; total time=   0.1s
[CV] END criterion=entropy, max_depth=5, min_samples_split=5; total time=   0.1s
[CV] END criterion=entropy, max_depth=5, min_samples_split=5; total time=   0.1s
[CV] END criterion=entropy, max_depth=5, min_samples_split=10; total time=   0.0s
[CV] END criterion=entropy, max_depth=5, min_samples_split=5; total time=   0.0s
[CV] END criterion=entropy, max_depth=5, min_samples_split=10; total time=   0.0s
[CV] END criterion=entropy, max_depth=5, min_samples_split=10; total time=   0.0s
[CV] END criterion=entropy, max_depth=5, min_samples_split=10; total time=   0.1s
[CV] END criterion=entropy, max_depth=5, min_samples_split=10; total time=   0.0s
[CV] END criterion=entropy, max_depth=5, min_samples_split=50; total time=   0.0s
[CV] END criterion=entropy, max_depth=5, min_samples_split=50; total time=   0.0s
[CV] END criterion=entropy, max_depth=5, min_samples_split=50; total time=   0.0s
[CV] END criterion=entropy, max_depth=5, min_samples_split=50; total time=   0.0s
[CV] END criterion=entropy, max_depth=5, min_samples_split=100; total time=   0.1s
[CV] END criterion=entropy, max_depth=5, min_samples_split=100; total time=   0.1s
[CV] END criterion=entropy, max_depth=5, min_samples_split=50; total time=   0.1s
[CV] END criterion=entropy, max_depth=5, min_samples_split=100; total time=   0.1s
[CV] END criterion=entropy, max_depth=5, min_samples_split=100; total time=   0.1s
[CV] END criterion=entropy, max_depth=5, min_samples_split=100; total time=   0.1s
[CV] END criterion=entropy, max_depth=10, min_samples_split=2; total time=   0.1s
[CV] END criterion=entropy, max_depth=10, min_samples_split=2; total time=   0.1s
[CV] END criterion=entropy, max_depth=10, min_samples_split=2; total time=   0.1s
[CV] END criterion=entropy, max_depth=10, min_samples_split=5; total time=   0.1s
[CV] END criterion=entropy, max_depth=10, min_samples_split=2; total time=   0.1s
[CV] END criterion=entropy, max_depth=10, min_samples_split=5; total time=   0.1s
[CV] END criterion=entropy, max_depth=10, min_samples_split=2; total time=   0.1s
[CV] END criterion=entropy, max_depth=10, min_samples_split=5; total time=   0.1s
[CV] END criterion=entropy, max_depth=10, min_samples_split=5; total time=   0.1s
[CV] END criterion=entropy, max_depth=10, min_samples_split=10; total time=   0.1s
[CV] END criterion=entropy, max_depth=10, min_samples_split=5; total time=   0.1s
[CV] END criterion=entropy, max_depth=10, min_samples_split=10; total time=   0.1s
[CV] END criterion=entropy, max_depth=10, min_samples_split=10; total time=   0.1s
[CV] END criterion=entropy, max_depth=10, min_samples_split=50; total time=   0.1s
[CV] END criterion=entropy, max_depth=10, min_samples_split=10; total time=   0.1s
[CV] END criterion=entropy, max_depth=10, min_samples_split=50; total time=   0.1s
[CV] END criterion=entropy, max_depth=10, min_samples_split=10; total time=   0.1s
[CV] END criterion=entropy, max_depth=10, min_samples_split=50; total time=   0.1s

   mean_test_score                                                              params
2         0.690693   {'criterion': 'gini', 'max_depth': None, 'min_samples_split': 10}
0         0.681685    {'criterion': 'gini', 'max_depth': None, 'min_samples_split': 2}
1         0.681674    {'criterion': 'gini', 'max_depth': None, 'min_samples_split': 5}
3         0.681124   {'criterion': 'gini', 'max_depth': None, 'min_samples_split': 50}
4         0.669864  {'criterion': 'gini', 'max_depth': None, 'min_samples_split': 100}
8         0.327905      {'criterion': 'gini', 'max_depth': 5, 'min_samples_split': 50}
9         0.327341     {'criterion': 'gini', 'max_depth': 5, 'min_samples_split': 100}
7         0.326781      {'criterion': 'gini', 'max_depth': 5, 'min_samples_split': 10}
6         0.326778       {'criterion': 'gini', 'max_depth': 5, 'min_samples_split': 5}
5         0.326218       {'criterion': 'gini', 'max_depth': 5, 'min_samples_split': 2}

In [22]:
dt = DecisionTreeClassifier(criterion= 'gini', max_depth= None, min_samples_split = 10)
dt.fit(x_train, y_train)
y_pred = dt.predict(x_test)
print(classification_report(y_test , y_pred))

               precision    recall  f1-score   support

     analysis       0.88      0.79      0.83        56
  application       0.70      0.64      0.67        59
comprehension       0.66      0.66      0.66        74
   evaluation       0.64      0.72      0.68        57
    knowledge       0.68      0.74      0.71        54
    synthesis       0.80      0.79      0.79        56

     accuracy                           0.72       356
    macro avg       0.73      0.72      0.72       356
 weighted avg       0.72      0.72      0.72       356

In [23]:
question = 'How many total disk access is needed to search a record using two level indexing?'
processed_q = preprocess_text(question)
tfidf_q = vectorizer.transform([processed_q])
tfidf_q = pd.DataFrame(tfidf_q.toarray(), columns=vectorizer.get_feature_names_out())



# Adding linguistic features
q_ling_features = pd.DataFrame([extract_linguistic_features(question)])

# Concatenate DataFrames
token_q = pd.concat([q_ling_features, tfidf_q], axis=1)

print(dt.predict(tfidf_q))

['application']

### XGBoost

In [17]:
y_mapper = {
    'knowledge' : 0,
    'comprehension' : 1,
    'application' : 2,
    'analysis' : 3,
    'synthesis' : 4,
    'evaluation' : 5
}

xgb_y = y.map(y_mapper)
xgb_y_train = y_train.map(y_mapper)
xgb_y_test = y_test.map(y_mapper)

In [18]:
params = {
    'max_depth' : [None , 250],
    'n_estimators': [100, 200],
    'learning_rate': [0.01, 0.1 , 0.3],
    'subsample': [0.8, 0.9]
}
param_search = GridSearchCV(estimator= XGBClassifier(objective='multi:softprob' , verbosity= 1), 
                            param_grid= params, cv=5, n_jobs= -1,return_train_score=True, verbose=2)

param_search.fit(x , xgb_y)

cv_results = pd.DataFrame(param_search.cv_results_)
cv_results = cv_results[["mean_test_score", "params"]].head(10).sort_values(by="mean_test_score", ascending=False)

cv_results

Fitting 5 folds for each of 24 candidates, totalling 120 fits
[CV] END learning_rate=0.01, max_depth=None, n_estimators=100, subsample=0.8; total time=   1.9s
[CV] END learning_rate=0.01, max_depth=None, n_estimators=100, subsample=0.8; total time=   2.0s
[CV] END learning_rate=0.01, max_depth=None, n_estimators=100, subsample=0.8; total time=   2.1s
[CV] END learning_rate=0.01, max_depth=None, n_estimators=100, subsample=0.8; total time=   2.1s
[CV] END learning_rate=0.01, max_depth=None, n_estimators=100, subsample=0.9; total time=   1.8s
[CV] END learning_rate=0.01, max_depth=None, n_estimators=100, subsample=0.8; total time=   2.1s
[CV] END learning_rate=0.01, max_depth=None, n_estimators=100, subsample=0.9; total time=   2.1s
[CV] END learning_rate=0.01, max_depth=None, n_estimators=100, subsample=0.9; total time=   2.1s
[CV] END learning_rate=0.01, max_depth=None, n_estimators=100, subsample=0.9; total time=   2.2s
[CV] END learning_rate=0.01, max_depth=None, n_estimators=100, subsample=0.9; total time=   2.1s
[CV] END learning_rate=0.01, max_depth=None, n_estimators=200, subsample=0.8; total time=   4.0s
[CV] END learning_rate=0.01, max_depth=None, n_estimators=200, subsample=0.8; total time=   3.4s
[CV] END learning_rate=0.01, max_depth=None, n_estimators=200, subsample=0.8; total time=   3.7s
[CV] END learning_rate=0.01, max_depth=None, n_estimators=200, subsample=0.9; total time=   3.6s
[CV] END learning_rate=0.01, max_depth=None, n_estimators=200, subsample=0.8; total time=   3.9s
[CV] END learning_rate=0.01, max_depth=None, n_estimators=200, subsample=0.9; total time=   3.8s
[CV] END learning_rate=0.01, max_depth=None, n_estimators=200, subsample=0.9; total time=   3.9s
[CV] END learning_rate=0.01, max_depth=None, n_estimators=200, subsample=0.8; total time=   4.2s
[CV] END learning_rate=0.01, max_depth=None, n_estimators=200, subsample=0.9; total time=   4.0s
[CV] END learning_rate=0.01, max_depth=None, n_estimators=200, subsample=0.9; total time=   4.2s
[CV] END learning_rate=0.01, max_depth=250, n_estimators=100, subsample=0.8; total time=   4.9s
[CV] END learning_rate=0.01, max_depth=250, n_estimators=100, subsample=0.8; total time=   4.8s
[CV] END learning_rate=0.01, max_depth=250, n_estimators=100, subsample=0.8; total time=   4.9s
[CV] END learning_rate=0.01, max_depth=250, n_estimators=100, subsample=0.8; total time=   4.7s
[CV] END learning_rate=0.01, max_depth=250, n_estimators=100, subsample=0.8; total time=   5.3s
[CV] END learning_rate=0.01, max_depth=250, n_estimators=100, subsample=0.9; total time=   5.3s
[CV] END learning_rate=0.01, max_depth=250, n_estimators=100, subsample=0.9; total time=   5.4s
[CV] END learning_rate=0.01, max_depth=250, n_estimators=100, subsample=0.9; total time=   5.2s
[CV] END learning_rate=0.01, max_depth=250, n_estimators=100, subsample=0.9; total time=   5.6s
[CV] END learning_rate=0.01, max_depth=250, n_estimators=100, subsample=0.9; total time=   5.4s
[CV] END learning_rate=0.1, max_depth=None, n_estimators=100, subsample=0.8; total time=   2.0s
[CV] END learning_rate=0.1, max_depth=None, n_estimators=100, subsample=0.8; total time=   2.1s
[CV] END learning_rate=0.01, max_depth=250, n_estimators=200, subsample=0.8; total time=   9.9s
[CV] END learning_rate=0.01, max_depth=250, n_estimators=200, subsample=0.8; total time=  10.1s
[CV] END learning_rate=0.1, max_depth=None, n_estimators=100, subsample=0.8; total time=   1.9s
[CV] END learning_rate=0.1, max_depth=None, n_estimators=100, subsample=0.8; total time=   1.8s
[CV] END learning_rate=0.01, max_depth=250, n_estimators=200, subsample=0.8; total time=   9.9s
[CV] END learning_rate=0.1, max_depth=None, n_estimators=100, subsample=0.8; total time=   1.8s
[CV] END learning_rate=0.1, max_depth=None, n_estimators=100, subsample=0.9; total time=   1.9s
[CV] END learning_rate=0.1, max_depth=None, n_estimators=100, subsample=0.9; total time=   1.8s
[CV] END learning_rate=0.01, max_depth=250, n_estimators=200, subsample=0.8; total time=   9.1s
[CV] END learning_rate=0.01, max_depth=250, n_estimators=200, subsample=0.8; total time=   9.7s
[CV] END learning_rate=0.1, max_depth=None, n_estimators=100, subsample=0.9; total time=   1.9s
[CV] END learning_rate=0.1, max_depth=None, n_estimators=100, subsample=0.9; total time=   2.0s
[CV] END learning_rate=0.01, max_depth=250, n_estimators=200, subsample=0.9; total time=  10.4s
[CV] END learning_rate=0.01, max_depth=250, n_estimators=200, subsample=0.9; total time=   9.9s
[CV] END learning_rate=0.1, max_depth=None, n_estimators=100, subsample=0.9; total time=   1.9s
[CV] END learning_rate=0.01, max_depth=250, n_estimators=200, subsample=0.9; total time=  10.3s
[CV] END learning_rate=0.01, max_depth=250, n_estimators=200, subsample=0.9; total time=  10.4s
[CV] END learning_rate=0.01, max_depth=250, n_estimators=200, subsample=0.9; total time=  10.5s
[CV] END learning_rate=0.1, max_depth=None, n_estimators=200, subsample=0.8; total time=   3.5s
[CV] END learning_rate=0.1, max_depth=None, n_estimators=200, subsample=0.8; total time=   3.4s
[CV] END learning_rate=0.1, max_depth=None, n_estimators=200, subsample=0.8; total time=   3.6s
[CV] END learning_rate=0.1, max_depth=None, n_estimators=200, subsample=0.8; total time=   3.2s
[CV] END learning_rate=0.1, max_depth=None, n_estimators=200, subsample=0.8; total time=   3.6s
[CV] END learning_rate=0.1, max_depth=None, n_estimators=200, subsample=0.9; total time=   3.3s
[CV] END learning_rate=0.1, max_depth=None, n_estimators=200, subsample=0.9; total time=   3.6s
[CV] END learning_rate=0.1, max_depth=None, n_estimators=200, subsample=0.9; total time=   3.5s
[CV] END learning_rate=0.1, max_depth=None, n_estimators=200, subsample=0.9; total time=   3.7s
[CV] END learning_rate=0.1, max_depth=None, n_estimators=200, subsample=0.9; total time=   3.5s
[CV] END learning_rate=0.1, max_depth=250, n_estimators=100, subsample=0.8; total time=   4.1s
[CV] END learning_rate=0.1, max_depth=250, n_estimators=100, subsample=0.8; total time=   4.0s
[CV] END learning_rate=0.1, max_depth=250, n_estimators=100, subsample=0.8; total time=   4.2s
[CV] END learning_rate=0.1, max_depth=250, n_estimators=100, subsample=0.8; total time=   3.9s
[CV] END learning_rate=0.1, max_depth=250, n_estimators=100, subsample=0.8; total time=   4.0s
[CV] END learning_rate=0.1, max_depth=250, n_estimators=100, subsample=0.9; total time=   4.7s
[CV] END learning_rate=0.1, max_depth=250, n_estimators=100, subsample=0.9; total time=   4.6s
[CV] END learning_rate=0.1, max_depth=250, n_estimators=100, subsample=0.9; total time=   4.4s
[CV] END learning_rate=0.1, max_depth=250, n_estimators=100, subsample=0.9; total time=   4.3s
[CV] END learning_rate=0.1, max_depth=250, n_estimators=100, subsample=0.9; total time=   4.7s
[CV] END learning_rate=0.3, max_depth=None, n_estimators=100, subsample=0.8; total time=   1.8s
[CV] END learning_rate=0.1, max_depth=250, n_estimators=200, subsample=0.8; total time=   6.9s
[CV] END learning_rate=0.1, max_depth=250, n_estimators=200, subsample=0.8; total time=   6.5s
[CV] END learning_rate=0.3, max_depth=None, n_estimators=100, subsample=0.8; total time=   1.9s
[CV] END learning_rate=0.1, max_depth=250, n_estimators=200, subsample=0.8; total time=   6.3s
[CV] END learning_rate=0.1, max_depth=250, n_estimators=200, subsample=0.8; total time=   6.1s
[CV] END learning_rate=0.3, max_depth=None, n_estimators=100, subsample=0.8; total time=   2.0s
[CV] END learning_rate=0.1, max_depth=250, n_estimators=200, subsample=0.8; total time=   6.7s
[CV] END learning_rate=0.3, max_depth=None, n_estimators=100, subsample=0.8; total time=   1.9s
[CV] END learning_rate=0.1, max_depth=250, n_estimators=200, subsample=0.9; total time=   6.6s
[CV] END learning_rate=0.3, max_depth=None, n_estimators=100, subsample=0.8; total time=   1.8s
[CV] END learning_rate=0.3, max_depth=None, n_estimators=100, subsample=0.9; total time=   1.8s
[CV] END learning_rate=0.3, max_depth=None, n_estimators=100, subsample=0.9; total time=   1.9s
[CV] END learning_rate=0.1, max_depth=250, n_estimators=200, subsample=0.9; total time=   6.9s
[CV] END learning_rate=0.3, max_depth=None, n_estimators=100, subsample=0.9; total time=   1.8s
[CV] END learning_rate=0.3, max_depth=None, n_estimators=100, subsample=0.9; total time=   1.4s
[CV] END learning_rate=0.3, max_depth=None, n_estimators=100, subsample=0.9; total time=   1.8s
[CV] END learning_rate=0.1, max_depth=250, n_estimators=200, subsample=0.9; total time=   6.5s
[CV] END learning_rate=0.1, max_depth=250, n_estimators=200, subsample=0.9; total time=   6.8s
[CV] END learning_rate=0.1, max_depth=250, n_estimators=200, subsample=0.9; total time=   7.1s
[CV] END learning_rate=0.3, max_depth=None, n_estimators=200, subsample=0.8; total time=   3.3s
[CV] END learning_rate=0.3, max_depth=None, n_estimators=200, subsample=0.8; total time=   3.1s
[CV] END learning_rate=0.3, max_depth=None, n_estimators=200, subsample=0.8; total time=   3.4s
[CV] END learning_rate=0.3, max_depth=None, n_estimators=200, subsample=0.8; total time=   3.2s
[CV] END learning_rate=0.3, max_depth=None, n_estimators=200, subsample=0.8; total time=   3.2s
[CV] END learning_rate=0.3, max_depth=None, n_estimators=200, subsample=0.9; total time=   3.2s
[CV] END learning_rate=0.3, max_depth=None, n_estimators=200, subsample=0.9; total time=   3.0s
[CV] END learning_rate=0.3, max_depth=None, n_estimators=200, subsample=0.9; total time=   3.3s
[CV] END learning_rate=0.3, max_depth=None, n_estimators=200, subsample=0.9; total time=   3.4s
[CV] END learning_rate=0.3, max_depth=250, n_estimators=100, subsample=0.8; total time=   3.1s
[CV] END learning_rate=0.3, max_depth=None, n_estimators=200, subsample=0.9; total time=   3.6s
[CV] END learning_rate=0.3, max_depth=250, n_estimators=100, subsample=0.8; total time=   3.2s
[CV] END learning_rate=0.3, max_depth=250, n_estimators=100, subsample=0.8; total time=   3.0s
[CV] END learning_rate=0.3, max_depth=250, n_estimators=100, subsample=0.8; total time=   2.8s
[CV] END learning_rate=0.3, max_depth=250, n_estimators=100, subsample=0.8; total time=   3.0s
[CV] END learning_rate=0.3, max_depth=250, n_estimators=100, subsample=0.9; total time=   3.1s
[CV] END learning_rate=0.3, max_depth=250, n_estimators=100, subsample=0.9; total time=   3.1s
[CV] END learning_rate=0.3, max_depth=250, n_estimators=100, subsample=0.9; total time=   2.9s
[CV] END learning_rate=0.3, max_depth=250, n_estimators=100, subsample=0.9; total time=   3.2s
[CV] END learning_rate=0.3, max_depth=250, n_estimators=100, subsample=0.9; total time=   3.1s
[CV] END learning_rate=0.3, max_depth=250, n_estimators=200, subsample=0.8; total time=   4.7s
[CV] END learning_rate=0.3, max_depth=250, n_estimators=200, subsample=0.8; total time=   5.0s
[CV] END learning_rate=0.3, max_depth=250, n_estimators=200, subsample=0.8; total time=   4.5s
[CV] END learning_rate=0.3, max_depth=250, n_estimators=200, subsample=0.8; total time=   4.7s
[CV] END learning_rate=0.3, max_depth=250, n_estimators=200, subsample=0.8; total time=   4.9s
[CV] END learning_rate=0.3, max_depth=250, n_estimators=200, subsample=0.9; total time=   4.7s
[CV] END learning_rate=0.3, max_depth=250, n_estimators=200, subsample=0.9; total time=   4.5s
[CV] END learning_rate=0.3, max_depth=250, n_estimators=200, subsample=0.9; total time=   4.4s
[CV] END learning_rate=0.3, max_depth=250, n_estimators=200, subsample=0.9; total time=   4.6s
[CV] END learning_rate=0.3, max_depth=250, n_estimators=200, subsample=0.9; total time=   4.6s

   mean_test_score                                                                             params
7         0.703622   {'learning_rate': 0.01, 'max_depth': 250, 'n_estimators': 200, 'subsample': 0.9}
6         0.699117   {'learning_rate': 0.01, 'max_depth': 250, 'n_estimators': 200, 'subsample': 0.8}
5         0.698563   {'learning_rate': 0.01, 'max_depth': 250, 'n_estimators': 100, 'subsample': 0.9}
4         0.695752   {'learning_rate': 0.01, 'max_depth': 250, 'n_estimators': 100, 'subsample': 0.8}
8         0.689560   {'learning_rate': 0.1, 'max_depth': None, 'n_estimators': 100, 'subsample': 0.8}
9         0.687878   {'learning_rate': 0.1, 'max_depth': None, 'n_estimators': 100, 'subsample': 0.9}
3         0.665398  {'learning_rate': 0.01, 'max_depth': None, 'n_estimators': 200, 'subsample': 0.9}
2         0.664276  {'learning_rate': 0.01, 'max_depth': None, 'n_estimators': 200, 'subsample': 0.8}
0         0.654154  {'learning_rate': 0.01, 'max_depth': None, 'n_estimators': 100, 'subsample': 0.8}
1         0.646852  {'learning_rate': 0.01, 'max_depth': None, 'n_estimators': 100, 'subsample': 0.9}

In [20]:
xgb = XGBClassifier(learning_rate=0.01, max_depth=250, n_estimators=200, subsample=0.9)
xgb.fit(x_train, xgb_y_train)
y_pred = xgb.predict(x_test)
print(classification_report(xgb_y_test , y_pred))

              precision    recall  f1-score   support

           0       0.72      0.70      0.71        54
           1       0.70      0.69      0.69        74
           2       0.69      0.71      0.70        59
           3       0.91      0.86      0.88        56
           4       0.75      0.80      0.78        56
           5       0.80      0.79      0.80        57

    accuracy                           0.76       356
   macro avg       0.76      0.76      0.76       356
weighted avg       0.76      0.76      0.76       356

In [21]:
question = 'How many total disk access is needed to search a record using two level indexing?'
processed_q = preprocess_text(question)
tfidf_q = vectorizer.transform([processed_q])
tfidf_q = pd.DataFrame(tfidf_q.toarray(), columns=vectorizer.get_feature_names_out())



# Adding linguistic features
q_ling_features = pd.DataFrame([extract_linguistic_features(question)])

# Concatenate DataFrames
token_q = pd.concat([q_ling_features, tfidf_q], axis=1)
# token_q = token_q.drop(columns= ['blooms_verb_present'])

print(xgb.predict(tfidf_q))

[4]

### Linear SVM

In [26]:
params = {
    'penalty': ['l2'],
    'loss': ['squared_hinge' , 'hinge'],
    'dual': [True, False],
    'C': [0.1, 1, 10, 100]
}
param_search = GridSearchCV(estimator= LinearSVC(), param_grid= params, cv=5, n_jobs= -1, return_train_score=True, verbose= 2)

param_search.fit(x , y)

cv_results = pd.DataFrame(param_search.cv_results_)
cv_results = cv_results[["mean_test_score", "params"]].head(10).sort_values(by="mean_test_score", ascending=False)

cv_results

Fitting 5 folds for each of 16 candidates, totalling 80 fits
[CV] END ...C=0.1, dual=True, loss=squared_hinge, penalty=l2; total time=   0.1s
[CV] END ...C=0.1, dual=True, loss=squared_hinge, penalty=l2; total time=   0.0s
[CV] END ...C=0.1, dual=True, loss=squared_hinge, penalty=l2; total time=   0.0s
[CV] END ...C=0.1, dual=True, loss=squared_hinge, penalty=l2; total time=   0.0s
[CV] END ...C=0.1, dual=True, loss=squared_hinge, penalty=l2; total time=   0.0s
[CV] END ...........C=0.1, dual=True, loss=hinge, penalty=l2; total time=   0.1s
[CV] END ...........C=0.1, dual=True, loss=hinge, penalty=l2; total time=   0.1s
[CV] END ...........C=0.1, dual=True, loss=hinge, penalty=l2; total time=   0.1s
[CV] END ...........C=0.1, dual=True, loss=hinge, penalty=l2; total time=   0.1s
[CV] END ...........C=0.1, dual=True, loss=hinge, penalty=l2; total time=   0.0s
[CV] END ..C=0.1, dual=False, loss=squared_hinge, penalty=l2; total time=   0.0s
[CV] END ..C=0.1, dual=False, loss=squared_hinge, penalty=l2; total time=   0.0s
[CV] END ..C=0.1, dual=False, loss=squared_hinge, penalty=l2; total time=   0.0s
[CV] END ..C=0.1, dual=False, loss=squared_hinge, penalty=l2; total time=   0.0s
[CV] END ..C=0.1, dual=False, loss=squared_hinge, penalty=l2; total time=   0.1s
[CV] END ..........C=0.1, dual=False, loss=hinge, penalty=l2; total time=   0.0s
[CV] END ..........C=0.1, dual=False, loss=hinge, penalty=l2; total time=   0.1s
[CV] END ..........C=0.1, dual=False, loss=hinge, penalty=l2; total time=   0.0s
[CV] END ..........C=0.1, dual=False, loss=hinge, penalty=l2; total time=   0.0s
[CV] END ..........C=0.1, dual=False, loss=hinge, penalty=l2; total time=   0.0s
[CV] END .....C=1, dual=True, loss=squared_hinge, penalty=l2; total time=   0.1s
[CV] END .....C=1, dual=True, loss=squared_hinge, penalty=l2; total time=   0.1s
[CV] END .....C=1, dual=True, loss=squared_hinge, penalty=l2; total time=   0.0s
[CV] END .....C=1, dual=True, loss=squared_hinge, penalty=l2; total time=   0.0s
[CV] END .....C=1, dual=True, loss=squared_hinge, penalty=l2; total time=   0.0s
[CV] END .............C=1, dual=True, loss=hinge, penalty=l2; total time=   0.1s
[CV] END .............C=1, dual=True, loss=hinge, penalty=l2; total time=   0.1s
[CV] END .............C=1, dual=True, loss=hinge, penalty=l2; total time=   0.1s
[CV] END ....C=1, dual=False, loss=squared_hinge, penalty=l2; total time=   0.1s
[CV] END ....C=1, dual=False, loss=squared_hinge, penalty=l2; total time=   0.0s
[CV] END .............C=1, dual=True, loss=hinge, penalty=l2; total time=   0.1s
[CV] END .............C=1, dual=True, loss=hinge, penalty=l2; total time=   0.1s
[CV] END ....C=1, dual=False, loss=squared_hinge, penalty=l2; total time=   0.1s
[CV] END ....C=1, dual=False, loss=squared_hinge, penalty=l2; total time=   0.1s
[CV] END ............C=1, dual=False, loss=hinge, penalty=l2; total time=   0.1s
[CV] END ....C=1, dual=False, loss=squared_hinge, penalty=l2; total time=   0.1s
[CV] END ............C=1, dual=False, loss=hinge, penalty=l2; total time=   0.0s
[CV] END ............C=1, dual=False, loss=hinge, penalty=l2; total time=   0.0s
[CV] END ............C=1, dual=False, loss=hinge, penalty=l2; total time=   0.0s
[CV] END ............C=1, dual=False, loss=hinge, penalty=l2; total time=   0.0s
[CV] END ....C=10, dual=True, loss=squared_hinge, penalty=l2; total time=   0.1s
[CV] END ....C=10, dual=True, loss=squared_hinge, penalty=l2; total time=   0.1s
[CV] END ....C=10, dual=True, loss=squared_hinge, penalty=l2; total time=   0.1s
[CV] END ....C=10, dual=True, loss=squared_hinge, penalty=l2; total time=   0.1s
[CV] END ............C=10, dual=True, loss=hinge, penalty=l2; total time=   0.1s
[CV] END ...C=10, dual=False, loss=squared_hinge, penalty=l2; total time=   0.1s
[CV] END ....C=10, dual=True, loss=squared_hinge, penalty=l2; total time=   0.1s
[CV] END ............C=10, dual=True, loss=hinge, penalty=l2; total time=   0.1s
[CV] END ...C=10, dual=False, loss=squared_hinge, penalty=l2; total time=   0.1s
[CV] END ...C=10, dual=False, loss=squared_hinge, penalty=l2; total time=   0.1s
[CV] END ............C=10, dual=True, loss=hinge, penalty=l2; total time=   0.1s
[CV] END ............C=10, dual=True, loss=hinge, penalty=l2; total time=   0.1s
[CV] END ...........C=10, dual=False, loss=hinge, penalty=l2; total time=   0.0s
[CV] END ...........C=10, dual=False, loss=hinge, penalty=l2; total time=   0.1s
[CV] END ...C=10, dual=False, loss=squared_hinge, penalty=l2; total time=   0.1s
[CV] END ...........C=10, dual=False, loss=hinge, penalty=l2; total time=   0.0s
[CV] END ...C=10, dual=False, loss=squared_hinge, penalty=l2; total time=   0.1s
[CV] END ...........C=10, dual=False, loss=hinge, penalty=l2; total time=   0.0s
[CV] END ...........C=10, dual=False, loss=hinge, penalty=l2; total time=   0.1s
[CV] END ............C=10, dual=True, loss=hinge, penalty=l2; total time=   0.1s
[CV] END ...C=100, dual=True, loss=squared_hinge, penalty=l2; total time=   0.1s

/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END ...C=100, dual=True, loss=squared_hinge, penalty=l2; total time=   0.1s
[CV] END ...C=100, dual=True, loss=squared_hinge, penalty=l2; total time=   0.1s
[CV] END ...........C=100, dual=True, loss=hinge, penalty=l2; total time=   0.1s
[CV] END ...........C=100, dual=True, loss=hinge, penalty=l2; total time=   0.1s
[CV] END ...........C=100, dual=True, loss=hinge, penalty=l2; total time=   0.1s
[CV] END ...C=100, dual=True, loss=squared_hinge, penalty=l2; total time=   0.1s
[CV] END ...C=100, dual=True, loss=squared_hinge, penalty=l2; total time=   0.2s
[CV] END ..C=100, dual=False, loss=squared_hinge, penalty=l2; total time=   0.1s
[CV] END ...........C=100, dual=True, loss=hinge, penalty=l2; total time=   0.1s
[CV] END ..C=100, dual=False, loss=squared_hinge, penalty=l2; total time=   0.1s

/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END ..C=100, dual=False, loss=squared_hinge, penalty=l2; total time=   0.1s
[CV] END ..........C=100, dual=False, loss=hinge, penalty=l2; total time=   0.0s
[CV] END ..C=100, dual=False, loss=squared_hinge, penalty=l2; total time=   0.1s
[CV] END ..........C=100, dual=False, loss=hinge, penalty=l2; total time=   0.0s
[CV] END ..C=100, dual=False, loss=squared_hinge, penalty=l2; total time=   0.1s
[CV] END ..........C=100, dual=False, loss=hinge, penalty=l2; total time=   0.0s
[CV] END ..........C=100, dual=False, loss=hinge, penalty=l2; total time=   0.0s
[CV] END ..........C=100, dual=False, loss=hinge, penalty=l2; total time=   0.0s
[CV] END ...........C=100, dual=True, loss=hinge, penalty=l2; total time=   0.1s

/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

   mean_test_score                                                               params
1         0.712046           {'C': 0.1, 'dual': True, 'loss': 'hinge', 'penalty': 'l2'}
0         0.712029   {'C': 0.1, 'dual': True, 'loss': 'squared_hinge', 'penalty': 'l2'}
2         0.712029  {'C': 0.1, 'dual': False, 'loss': 'squared_hinge', 'penalty': 'l2'}
5         0.704719             {'C': 1, 'dual': True, 'loss': 'hinge', 'penalty': 'l2'}
4         0.695702     {'C': 1, 'dual': True, 'loss': 'squared_hinge', 'penalty': 'l2'}
6         0.695702    {'C': 1, 'dual': False, 'loss': 'squared_hinge', 'penalty': 'l2'}
9         0.669263            {'C': 10, 'dual': True, 'loss': 'hinge', 'penalty': 'l2'}
8         0.666444    {'C': 10, 'dual': True, 'loss': 'squared_hinge', 'penalty': 'l2'}
3              NaN          {'C': 0.1, 'dual': False, 'loss': 'hinge', 'penalty': 'l2'}
7              NaN            {'C': 1, 'dual': False, 'loss': 'hinge', 'penalty': 'l2'}

In [27]:
lsvm = LinearSVC(C= 0.1, dual= True, loss= 'hinge', penalty= 'l2')
lsvm.fit(x_train, y_train)
y_pred = lsvm.predict(x_test)
print(classification_report(y_test , y_pred))

               precision    recall  f1-score   support

     analysis       0.92      0.80      0.86        56
  application       0.75      0.64      0.69        59
comprehension       0.74      0.78      0.76        74
   evaluation       0.78      0.82      0.80        57
    knowledge       0.66      0.74      0.70        54
    synthesis       0.77      0.79      0.78        56

     accuracy                           0.76       356
    macro avg       0.77      0.76      0.76       356
 weighted avg       0.77      0.76      0.76       356

In [31]:
question = 'How many total disk access is needed to search a record using two level indexing?'
processed_q = preprocess_text(question)
tfidf_q = vectorizer.transform([processed_q])
tfidf_q = pd.DataFrame(tfidf_q.toarray(), columns=vectorizer.get_feature_names_out())



# Adding linguistic features
q_ling_features = pd.DataFrame([extract_linguistic_features(question)])

# Concatenate DataFrames
token_q = pd.concat([q_ling_features, tfidf_q], axis=1)

print(lsvm.predict(tfidf_q))

['application']

### SVM

In [28]:
params = {
    'C': [0.001, 0.1, 1, 10],
    'gamma': ['scale', 'auto', 0.22],
    'kernel': ['rbf', 'poly', 'sigmoid'],
    'degree': [1, 2, 4],
}
param_search = GridSearchCV(estimator= SVC(shrinking=False), param_grid= params, cv=5, n_jobs= -1, return_train_score=True, verbose= 2)

param_search.fit(x , y)

cv_results = pd.DataFrame(param_search.cv_results_)
cv_results = cv_results[["mean_test_score", "params"]].head(10).sort_values(by="mean_test_score", ascending=False)

cv_results

Fitting 5 folds for each of 108 candidates, totalling 540 fits
[CV] END .........C=0.001, degree=1, gamma=scale, kernel=rbf; total time=   2.3s
[CV] END .........C=0.001, degree=1, gamma=scale, kernel=rbf; total time=   2.3s
[CV] END .........C=0.001, degree=1, gamma=scale, kernel=rbf; total time=   2.2s
[CV] END ........C=0.001, degree=1, gamma=scale, kernel=poly; total time=   2.5s
[CV] END .........C=0.001, degree=1, gamma=scale, kernel=rbf; total time=   2.5s
[CV] END ........C=0.001, degree=1, gamma=scale, kernel=poly; total time=   2.6s
[CV] END ........C=0.001, degree=1, gamma=scale, kernel=poly; total time=   2.6s
[CV] END ........C=0.001, degree=1, gamma=scale, kernel=poly; total time=   2.7s
[CV] END .........C=0.001, degree=1, gamma=scale, kernel=rbf; total time=   2.6s
[CV] END ........C=0.001, degree=1, gamma=scale, kernel=poly; total time=   2.6s
[CV] END .....C=0.001, degree=1, gamma=scale, kernel=sigmoid; total time=   2.7s
[CV] END .....C=0.001, degree=1, gamma=scale, kernel=sigmoid; total time=   2.4s
[CV] END .....C=0.001, degree=1, gamma=scale, kernel=sigmoid; total time=   2.5s
[CV] END .....C=0.001, degree=1, gamma=scale, kernel=sigmoid; total time=   2.7s
[CV] END .....C=0.001, degree=1, gamma=scale, kernel=sigmoid; total time=   2.7s
[CV] END ..........C=0.001, degree=1, gamma=auto, kernel=rbf; total time=   2.5s
[CV] END .........C=0.001, degree=1, gamma=auto, kernel=poly; total time=   2.6s
[CV] END ..........C=0.001, degree=1, gamma=auto, kernel=rbf; total time=   2.5s
[CV] END ..........C=0.001, degree=1, gamma=auto, kernel=rbf; total time=   2.8s
[CV] END .........C=0.001, degree=1, gamma=auto, kernel=poly; total time=   2.6s
[CV] END ..........C=0.001, degree=1, gamma=auto, kernel=rbf; total time=   2.7s
[CV] END ..........C=0.001, degree=1, gamma=auto, kernel=rbf; total time=   2.7s
[CV] END .........C=0.001, degree=1, gamma=auto, kernel=poly; total time=   2.2s
[CV] END ......C=0.001, degree=1, gamma=auto, kernel=sigmoid; total time=   2.2s
[CV] END .........C=0.001, degree=1, gamma=auto, kernel=poly; total time=   2.2s
[CV] END .........C=0.001, degree=1, gamma=auto, kernel=poly; total time=   2.4s
[CV] END ......C=0.001, degree=1, gamma=auto, kernel=sigmoid; total time=   2.2s
[CV] END ......C=0.001, degree=1, gamma=auto, kernel=sigmoid; total time=   2.4s
[CV] END ......C=0.001, degree=1, gamma=auto, kernel=sigmoid; total time=   2.3s
[CV] END ......C=0.001, degree=1, gamma=auto, kernel=sigmoid; total time=   2.4s
[CV] END ..........C=0.001, degree=1, gamma=0.22, kernel=rbf; total time=   2.4s
[CV] END ..........C=0.001, degree=1, gamma=0.22, kernel=rbf; total time=   2.5s
[CV] END ..........C=0.001, degree=1, gamma=0.22, kernel=rbf; total time=   2.6s
[CV] END ..........C=0.001, degree=1, gamma=0.22, kernel=rbf; total time=   2.9s
[CV] END .........C=0.001, degree=1, gamma=0.22, kernel=poly; total time=   2.6s
[CV] END .........C=0.001, degree=1, gamma=0.22, kernel=poly; total time=   2.6s
[CV] END .........C=0.001, degree=1, gamma=0.22, kernel=poly; total time=   2.7s
[CV] END .........C=0.001, degree=1, gamma=0.22, kernel=poly; total time=   2.6s
[CV] END ......C=0.001, degree=1, gamma=0.22, kernel=sigmoid; total time=   2.7s
[CV] END .........C=0.001, degree=1, gamma=0.22, kernel=poly; total time=   2.8s
[CV] END ..........C=0.001, degree=1, gamma=0.22, kernel=rbf; total time=   3.0s
[CV] END ......C=0.001, degree=1, gamma=0.22, kernel=sigmoid; total time=   2.3s
[CV] END ......C=0.001, degree=1, gamma=0.22, kernel=sigmoid; total time=   2.4s
[CV] END ......C=0.001, degree=1, gamma=0.22, kernel=sigmoid; total time=   2.4s
[CV] END ......C=0.001, degree=1, gamma=0.22, kernel=sigmoid; total time=   2.4s
[CV] END ........C=0.001, degree=2, gamma=scale, kernel=poly; total time=   2.2s
[CV] END .........C=0.001, degree=2, gamma=scale, kernel=rbf; total time=   2.3s
[CV] END .........C=0.001, degree=2, gamma=scale, kernel=rbf; total time=   2.6s
[CV] END ........C=0.001, degree=2, gamma=scale, kernel=poly; total time=   2.2s
[CV] END .........C=0.001, degree=2, gamma=scale, kernel=rbf; total time=   2.8s
[CV] END ........C=0.001, degree=2, gamma=scale, kernel=poly; total time=   2.6s
[CV] END ........C=0.001, degree=2, gamma=scale, kernel=poly; total time=   2.6s
[CV] END .........C=0.001, degree=2, gamma=scale, kernel=rbf; total time=   2.7s
[CV] END ........C=0.001, degree=2, gamma=scale, kernel=poly; total time=   2.8s
[CV] END .........C=0.001, degree=2, gamma=scale, kernel=rbf; total time=   2.7s
[CV] END .....C=0.001, degree=2, gamma=scale, kernel=sigmoid; total time=   2.0s
[CV] END .....C=0.001, degree=2, gamma=scale, kernel=sigmoid; total time=   2.3s
[CV] END .....C=0.001, degree=2, gamma=scale, kernel=sigmoid; total time=   2.6s
[CV] END .....C=0.001, degree=2, gamma=scale, kernel=sigmoid; total time=   2.5s
[CV] END .....C=0.001, degree=2, gamma=scale, kernel=sigmoid; total time=   2.5s
[CV] END .........C=0.001, degree=2, gamma=auto, kernel=poly; total time=   2.4s
[CV] END ..........C=0.001, degree=2, gamma=auto, kernel=rbf; total time=   2.5s
[CV] END ..........C=0.001, degree=2, gamma=auto, kernel=rbf; total time=   2.6s
[CV] END ..........C=0.001, degree=2, gamma=auto, kernel=rbf; total time=   2.6s
[CV] END ..........C=0.001, degree=2, gamma=auto, kernel=rbf; total time=   2.6s
[CV] END ..........C=0.001, degree=2, gamma=auto, kernel=rbf; total time=   2.5s
[CV] END .........C=0.001, degree=2, gamma=auto, kernel=poly; total time=   1.9s
[CV] END .........C=0.001, degree=2, gamma=auto, kernel=poly; total time=   2.3s
[CV] END ......C=0.001, degree=2, gamma=auto, kernel=sigmoid; total time=   2.0s
[CV] END .........C=0.001, degree=2, gamma=auto, kernel=poly; total time=   2.2s
[CV] END .........C=0.001, degree=2, gamma=auto, kernel=poly; total time=   2.5s
[CV] END ......C=0.001, degree=2, gamma=auto, kernel=sigmoid; total time=   2.2s
[CV] END ......C=0.001, degree=2, gamma=auto, kernel=sigmoid; total time=   2.3s
[CV] END ......C=0.001, degree=2, gamma=auto, kernel=sigmoid; total time=   2.3s
[CV] END ......C=0.001, degree=2, gamma=auto, kernel=sigmoid; total time=   2.4s
[CV] END ..........C=0.001, degree=2, gamma=0.22, kernel=rbf; total time=   2.5s
[CV] END ..........C=0.001, degree=2, gamma=0.22, kernel=rbf; total time=   2.7s
[CV] END ..........C=0.001, degree=2, gamma=0.22, kernel=rbf; total time=   2.0s
[CV] END ..........C=0.001, degree=2, gamma=0.22, kernel=rbf; total time=   1.9s
[CV] END .........C=0.001, degree=2, gamma=0.22, kernel=poly; total time=   1.8s
[CV] END .........C=0.001, degree=2, gamma=0.22, kernel=poly; total time=   2.1s
[CV] END ..........C=0.001, degree=2, gamma=0.22, kernel=rbf; total time=   2.1s
[CV] END .........C=0.001, degree=2, gamma=0.22, kernel=poly; total time=   2.1s
[CV] END .........C=0.001, degree=2, gamma=0.22, kernel=poly; total time=   2.2s
[CV] END .........C=0.001, degree=2, gamma=0.22, kernel=poly; total time=   2.2s
[CV] END ......C=0.001, degree=2, gamma=0.22, kernel=sigmoid; total time=   2.1s
[CV] END ......C=0.001, degree=2, gamma=0.22, kernel=sigmoid; total time=   2.0s
[CV] END ......C=0.001, degree=2, gamma=0.22, kernel=sigmoid; total time=   2.2s
[CV] END ......C=0.001, degree=2, gamma=0.22, kernel=sigmoid; total time=   1.9s
[CV] END ......C=0.001, degree=2, gamma=0.22, kernel=sigmoid; total time=   2.2s
[CV] END .........C=0.001, degree=4, gamma=scale, kernel=rbf; total time=   2.1s
[CV] END .........C=0.001, degree=4, gamma=scale, kernel=rbf; total time=   2.0s
[CV] END .........C=0.001, degree=4, gamma=scale, kernel=rbf; total time=   2.3s
[CV] END ........C=0.001, degree=4, gamma=scale, kernel=poly; total time=   2.2s
[CV] END .........C=0.001, degree=4, gamma=scale, kernel=rbf; total time=   2.4s
[CV] END ........C=0.001, degree=4, gamma=scale, kernel=poly; total time=   2.4s
[CV] END ........C=0.001, degree=4, gamma=scale, kernel=poly; total time=   2.3s
[CV] END ........C=0.001, degree=4, gamma=scale, kernel=poly; total time=   2.2s
[CV] END .........C=0.001, degree=4, gamma=scale, kernel=rbf; total time=   2.4s
[CV] END ........C=0.001, degree=4, gamma=scale, kernel=poly; total time=   2.0s
[CV] END .....C=0.001, degree=4, gamma=scale, kernel=sigmoid; total time=   2.0s
[CV] END .....C=0.001, degree=4, gamma=scale, kernel=sigmoid; total time=   2.3s
[CV] END .....C=0.001, degree=4, gamma=scale, kernel=sigmoid; total time=   2.4s
[CV] END .....C=0.001, degree=4, gamma=scale, kernel=sigmoid; total time=   2.4s
[CV] END .....C=0.001, degree=4, gamma=scale, kernel=sigmoid; total time=   2.7s
[CV] END ..........C=0.001, degree=4, gamma=auto, kernel=rbf; total time=   2.3s
[CV] END ..........C=0.001, degree=4, gamma=auto, kernel=rbf; total time=   2.5s
[CV] END .........C=0.001, degree=4, gamma=auto, kernel=poly; total time=   2.3s
[CV] END ..........C=0.001, degree=4, gamma=auto, kernel=rbf; total time=   2.5s
[CV] END ..........C=0.001, degree=4, gamma=auto, kernel=rbf; total time=   2.4s
[CV] END ..........C=0.001, degree=4, gamma=auto, kernel=rbf; total time=   2.6s
[CV] END .........C=0.001, degree=4, gamma=auto, kernel=poly; total time=   1.9s
[CV] END .........C=0.001, degree=4, gamma=auto, kernel=poly; total time=   1.9s
[CV] END .........C=0.001, degree=4, gamma=auto, kernel=poly; total time=   1.9s
[CV] END .........C=0.001, degree=4, gamma=auto, kernel=poly; total time=   2.2s
[CV] END ......C=0.001, degree=4, gamma=auto, kernel=sigmoid; total time=   2.2s
[CV] END ......C=0.001, degree=4, gamma=auto, kernel=sigmoid; total time=   2.1s
[CV] END ......C=0.001, degree=4, gamma=auto, kernel=sigmoid; total time=   2.1s
[CV] END ......C=0.001, degree=4, gamma=auto, kernel=sigmoid; total time=   2.1s
[CV] END ......C=0.001, degree=4, gamma=auto, kernel=sigmoid; total time=   2.3s
[CV] END ..........C=0.001, degree=4, gamma=0.22, kernel=rbf; total time=   2.0s
[CV] END ..........C=0.001, degree=4, gamma=0.22, kernel=rbf; total time=   2.2s
[CV] END ..........C=0.001, degree=4, gamma=0.22, kernel=rbf; total time=   1.7s
[CV] END ..........C=0.001, degree=4, gamma=0.22, kernel=rbf; total time=   2.0s
[CV] END .........C=0.001, degree=4, gamma=0.22, kernel=poly; total time=   1.9s
[CV] END .........C=0.001, degree=4, gamma=0.22, kernel=poly; total time=   2.2s
[CV] END .........C=0.001, degree=4, gamma=0.22, kernel=poly; total time=   2.2s
[CV] END .........C=0.001, degree=4, gamma=0.22, kernel=poly; total time=   2.1s
[CV] END .........C=0.001, degree=4, gamma=0.22, kernel=poly; total time=   2.1s
[CV] END ......C=0.001, degree=4, gamma=0.22, kernel=sigmoid; total time=   2.1s
[CV] END ..........C=0.001, degree=4, gamma=0.22, kernel=rbf; total time=   2.4s
[CV] END ......C=0.001, degree=4, gamma=0.22, kernel=sigmoid; total time=   2.3s
[CV] END ......C=0.001, degree=4, gamma=0.22, kernel=sigmoid; total time=   2.2s
[CV] END ......C=0.001, degree=4, gamma=0.22, kernel=sigmoid; total time=   2.2s
[CV] END ......C=0.001, degree=4, gamma=0.22, kernel=sigmoid; total time=   1.8s
[CV] END ...........C=0.1, degree=1, gamma=scale, kernel=rbf; total time=   2.2s
[CV] END ...........C=0.1, degree=1, gamma=scale, kernel=rbf; total time=   2.4s
[CV] END ..........C=0.1, degree=1, gamma=scale, kernel=poly; total time=   2.3s
[CV] END ..........C=0.1, degree=1, gamma=scale, kernel=poly; total time=   2.4s
[CV] END ..........C=0.1, degree=1, gamma=scale, kernel=poly; total time=   2.4s
[CV] END ..........C=0.1, degree=1, gamma=scale, kernel=poly; total time=   2.3s
[CV] END ...........C=0.1, degree=1, gamma=scale, kernel=rbf; total time=   2.7s
[CV] END ...........C=0.1, degree=1, gamma=scale, kernel=rbf; total time=   2.5s
[CV] END ...........C=0.1, degree=1, gamma=scale, kernel=rbf; total time=   2.6s
[CV] END ..........C=0.1, degree=1, gamma=scale, kernel=poly; total time=   2.3s
[CV] END .......C=0.1, degree=1, gamma=scale, kernel=sigmoid; total time=   2.3s
[CV] END .......C=0.1, degree=1, gamma=scale, kernel=sigmoid; total time=   2.2s
[CV] END .......C=0.1, degree=1, gamma=scale, kernel=sigmoid; total time=   2.4s
[CV] END .......C=0.1, degree=1, gamma=scale, kernel=sigmoid; total time=   2.4s
[CV] END .......C=0.1, degree=1, gamma=scale, kernel=sigmoid; total time=   2.6s
[CV] END ............C=0.1, degree=1, gamma=auto, kernel=rbf; total time=   2.6s
[CV] END ............C=0.1, degree=1, gamma=auto, kernel=rbf; total time=   2.5s
[CV] END ............C=0.1, degree=1, gamma=auto, kernel=rbf; total time=   2.6s
[CV] END ............C=0.1, degree=1, gamma=auto, kernel=rbf; total time=   2.8s
[CV] END ............C=0.1, degree=1, gamma=auto, kernel=rbf; total time=   2.5s
[CV] END ...........C=0.1, degree=1, gamma=auto, kernel=poly; total time=   2.0s
[CV] END ...........C=0.1, degree=1, gamma=auto, kernel=poly; total time=   2.0s
[CV] END ...........C=0.1, degree=1, gamma=auto, kernel=poly; total time=   1.9s
[CV] END ...........C=0.1, degree=1, gamma=auto, kernel=poly; total time=   2.0s
[CV] END ...........C=0.1, degree=1, gamma=auto, kernel=poly; total time=   2.2s
[CV] END ........C=0.1, degree=1, gamma=auto, kernel=sigmoid; total time=   1.9s
[CV] END ........C=0.1, degree=1, gamma=auto, kernel=sigmoid; total time=   2.2s
[CV] END ........C=0.1, degree=1, gamma=auto, kernel=sigmoid; total time=   2.1s
[CV] END ........C=0.1, degree=1, gamma=auto, kernel=sigmoid; total time=   2.2s
[CV] END ........C=0.1, degree=1, gamma=auto, kernel=sigmoid; total time=   2.1s
[CV] END ............C=0.1, degree=1, gamma=0.22, kernel=rbf; total time=   2.2s
[CV] END ............C=0.1, degree=1, gamma=0.22, kernel=rbf; total time=   2.2s
[CV] END ............C=0.1, degree=1, gamma=0.22, kernel=rbf; total time=   2.2s
[CV] END ...........C=0.1, degree=1, gamma=0.22, kernel=poly; total time=   2.0s
[CV] END ............C=0.1, degree=1, gamma=0.22, kernel=rbf; total time=   2.1s
[CV] END ...........C=0.1, degree=1, gamma=0.22, kernel=poly; total time=   2.2s
[CV] END ............C=0.1, degree=1, gamma=0.22, kernel=rbf; total time=   2.2s
[CV] END ...........C=0.1, degree=1, gamma=0.22, kernel=poly; total time=   2.0s
[CV] END ...........C=0.1, degree=1, gamma=0.22, kernel=poly; total time=   2.2s
[CV] END ...........C=0.1, degree=1, gamma=0.22, kernel=poly; total time=   2.2s
[CV] END ........C=0.1, degree=1, gamma=0.22, kernel=sigmoid; total time=   2.3s
[CV] END ........C=0.1, degree=1, gamma=0.22, kernel=sigmoid; total time=   2.1s
[CV] END ........C=0.1, degree=1, gamma=0.22, kernel=sigmoid; total time=   2.2s
[CV] END ........C=0.1, degree=1, gamma=0.22, kernel=sigmoid; total time=   2.1s
[CV] END ........C=0.1, degree=1, gamma=0.22, kernel=sigmoid; total time=   2.1s
[CV] END ...........C=0.1, degree=2, gamma=scale, kernel=rbf; total time=   2.3s
[CV] END ...........C=0.1, degree=2, gamma=scale, kernel=rbf; total time=   2.2s
[CV] END ...........C=0.1, degree=2, gamma=scale, kernel=rbf; total time=   2.4s
[CV] END ..........C=0.1, degree=2, gamma=scale, kernel=poly; total time=   2.2s
[CV] END ..........C=0.1, degree=2, gamma=scale, kernel=poly; total time=   2.4s
[CV] END ...........C=0.1, degree=2, gamma=scale, kernel=rbf; total time=   2.4s
[CV] END ..........C=0.1, degree=2, gamma=scale, kernel=poly; total time=   2.2s
[CV] END ..........C=0.1, degree=2, gamma=scale, kernel=poly; total time=   2.1s
[CV] END ...........C=0.1, degree=2, gamma=scale, kernel=rbf; total time=   2.5s
[CV] END ..........C=0.1, degree=2, gamma=scale, kernel=poly; total time=   2.1s
[CV] END .......C=0.1, degree=2, gamma=scale, kernel=sigmoid; total time=   1.8s
[CV] END .......C=0.1, degree=2, gamma=scale, kernel=sigmoid; total time=   2.1s
[CV] END .......C=0.1, degree=2, gamma=scale, kernel=sigmoid; total time=   2.3s
[CV] END .......C=0.1, degree=2, gamma=scale, kernel=sigmoid; total time=   2.6s
[CV] END .......C=0.1, degree=2, gamma=scale, kernel=sigmoid; total time=   2.4s
[CV] END ............C=0.1, degree=2, gamma=auto, kernel=rbf; total time=   2.5s
[CV] END ...........C=0.1, degree=2, gamma=auto, kernel=poly; total time=   2.4s
[CV] END ............C=0.1, degree=2, gamma=auto, kernel=rbf; total time=   2.5s
[CV] END ............C=0.1, degree=2, gamma=auto, kernel=rbf; total time=   2.2s
[CV] END ............C=0.1, degree=2, gamma=auto, kernel=rbf; total time=   2.5s
[CV] END ............C=0.1, degree=2, gamma=auto, kernel=rbf; total time=   2.6s
[CV] END ...........C=0.1, degree=2, gamma=auto, kernel=poly; total time=   1.7s
[CV] END ...........C=0.1, degree=2, gamma=auto, kernel=poly; total time=   1.5s
[CV] END ...........C=0.1, degree=2, gamma=auto, kernel=poly; total time=   1.8s
[CV] END ...........C=0.1, degree=2, gamma=auto, kernel=poly; total time=   2.0s
[CV] END ........C=0.1, degree=2, gamma=auto, kernel=sigmoid; total time=   2.1s
[CV] END ........C=0.1, degree=2, gamma=auto, kernel=sigmoid; total time=   2.0s
[CV] END ........C=0.1, degree=2, gamma=auto, kernel=sigmoid; total time=   2.2s
[CV] END ........C=0.1, degree=2, gamma=auto, kernel=sigmoid; total time=   2.3s
[CV] END ........C=0.1, degree=2, gamma=auto, kernel=sigmoid; total time=   2.3s
[CV] END ............C=0.1, degree=2, gamma=0.22, kernel=rbf; total time=   2.2s
[CV] END ............C=0.1, degree=2, gamma=0.22, kernel=rbf; total time=   2.4s
[CV] END ............C=0.1, degree=2, gamma=0.22, kernel=rbf; total time=   2.2s
[CV] END ............C=0.1, degree=2, gamma=0.22, kernel=rbf; total time=   2.0s
[CV] END ............C=0.1, degree=2, gamma=0.22, kernel=rbf; total time=   1.8s
[CV] END ...........C=0.1, degree=2, gamma=0.22, kernel=poly; total time=   1.8s
[CV] END ...........C=0.1, degree=2, gamma=0.22, kernel=poly; total time=   1.9s
[CV] END ...........C=0.1, degree=2, gamma=0.22, kernel=poly; total time=   1.8s
[CV] END ...........C=0.1, degree=2, gamma=0.22, kernel=poly; total time=   1.9s
[CV] END ...........C=0.1, degree=2, gamma=0.22, kernel=poly; total time=   1.8s
[CV] END ........C=0.1, degree=2, gamma=0.22, kernel=sigmoid; total time=   2.0s
[CV] END ........C=0.1, degree=2, gamma=0.22, kernel=sigmoid; total time=   1.8s
[CV] END ........C=0.1, degree=2, gamma=0.22, kernel=sigmoid; total time=   1.9s
[CV] END ........C=0.1, degree=2, gamma=0.22, kernel=sigmoid; total time=   1.8s
[CV] END ...........C=0.1, degree=4, gamma=scale, kernel=rbf; total time=   1.9s
[CV] END ...........C=0.1, degree=4, gamma=scale, kernel=rbf; total time=   2.1s
[CV] END ...........C=0.1, degree=4, gamma=scale, kernel=rbf; total time=   1.8s
[CV] END ........C=0.1, degree=2, gamma=0.22, kernel=sigmoid; total time=   1.8s
[CV] END ..........C=0.1, degree=4, gamma=scale, kernel=poly; total time=   2.0s
[CV] END ..........C=0.1, degree=4, gamma=scale, kernel=poly; total time=   1.9s
[CV] END ...........C=0.1, degree=4, gamma=scale, kernel=rbf; total time=   2.1s
[CV] END ...........C=0.1, degree=4, gamma=scale, kernel=rbf; total time=   2.2s
[CV] END ..........C=0.1, degree=4, gamma=scale, kernel=poly; total time=   1.4s
[CV] END ..........C=0.1, degree=4, gamma=scale, kernel=poly; total time=   1.8s
[CV] END .......C=0.1, degree=4, gamma=scale, kernel=sigmoid; total time=   1.8s
[CV] END .......C=0.1, degree=4, gamma=scale, kernel=sigmoid; total time=   2.1s
[CV] END .......C=0.1, degree=4, gamma=scale, kernel=sigmoid; total time=   2.1s
[CV] END .......C=0.1, degree=4, gamma=scale, kernel=sigmoid; total time=   1.9s
[CV] END .......C=0.1, degree=4, gamma=scale, kernel=sigmoid; total time=   2.0s
[CV] END ..........C=0.1, degree=4, gamma=scale, kernel=poly; total time=   2.2s
[CV] END ............C=0.1, degree=4, gamma=auto, kernel=rbf; total time=   2.0s
[CV] END ............C=0.1, degree=4, gamma=auto, kernel=rbf; total time=   2.0s
[CV] END ............C=0.1, degree=4, gamma=auto, kernel=rbf; total time=   2.0s
[CV] END ...........C=0.1, degree=4, gamma=auto, kernel=poly; total time=   1.7s
[CV] END ............C=0.1, degree=4, gamma=auto, kernel=rbf; total time=   1.9s
[CV] END ...........C=0.1, degree=4, gamma=auto, kernel=poly; total time=   1.9s

   mean_test_score                                                            params
0         0.206976      {'C': 0.001, 'degree': 1, 'gamma': 'scale', 'kernel': 'rbf'}
1         0.206976     {'C': 0.001, 'degree': 1, 'gamma': 'scale', 'kernel': 'poly'}
2         0.206976  {'C': 0.001, 'degree': 1, 'gamma': 'scale', 'kernel': 'sigmoid'}
3         0.206976       {'C': 0.001, 'degree': 1, 'gamma': 'auto', 'kernel': 'rbf'}
4         0.206976      {'C': 0.001, 'degree': 1, 'gamma': 'auto', 'kernel': 'poly'}
5         0.206976   {'C': 0.001, 'degree': 1, 'gamma': 'auto', 'kernel': 'sigmoid'}
6         0.206976         {'C': 0.001, 'degree': 1, 'gamma': 0.22, 'kernel': 'rbf'}
7         0.206976        {'C': 0.001, 'degree': 1, 'gamma': 0.22, 'kernel': 'poly'}
8         0.206976     {'C': 0.001, 'degree': 1, 'gamma': 0.22, 'kernel': 'sigmoid'}
9         0.206976      {'C': 0.001, 'degree': 2, 'gamma': 'scale', 'kernel': 'rbf'}

### Naive Bayes

In [29]:
params = {
    'alpha': [1e-1000,1e-500,1e-100, 1e-50,1e-20,1e-10,1e-06],
    'fit_prior': [True, False],
    'force_alpha': [True, False]
}
param_search = GridSearchCV(estimator= MultinomialNB(), param_grid= params, cv=5, n_jobs= -1)

param_search.fit(x, y)

cv_results = pd.DataFrame(param_search.cv_results_)
cv_results = cv_results[["mean_test_score", "params"]].head(10).sort_values(by="mean_test_score", ascending=False)

cv_results

/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:898: RuntimeWarning: divide by zero encountered in log
  self.feature_log_prob_ = np.log(smoothed_fc) - np.log(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:898: RuntimeWarning: divide by zero encountered in log
  self.feature_log_prob_ = np.log(smoothed_fc) - np.log(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:898: RuntimeWarning: divide by zero encountered in log
  self.feature_log_prob_ = np.log(smoothed_fc) - np.log(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:898: RuntimeWarning: divide by zero encountered in log
  self.feature_log_prob_ = np.log(smoothed_fc) - np.log(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:898: RuntimeWarning: divide by zero encountered in log
  self.feature_log_prob_ = np.log(smoothed_fc) - np.log(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:898: RuntimeWarning: divide by zero encountered in log
  self.feature_log_prob_ = np.log(smoothed_fc) - np.log(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:898: RuntimeWarning: divide by zero encountered in log
  self.feature_log_prob_ = np.log(smoothed_fc) - np.log(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:898: RuntimeWarning: divide by zero encountered in log
  self.feature_log_prob_ = np.log(smoothed_fc) - np.log(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:898: RuntimeWarning: divide by zero encountered in log
  self.feature_log_prob_ = np.log(smoothed_fc) - np.log(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:898: RuntimeWarning: divide by zero encountered in log
  self.feature_log_prob_ = np.log(smoothed_fc) - np.log(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:898: RuntimeWarning: divide by zero encountered in log
  self.feature_log_prob_ = np.log(smoothed_fc) - np.log(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:898: RuntimeWarning: divide by zero encountered in log
  self.feature_log_prob_ = np.log(smoothed_fc) - np.log(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:898: RuntimeWarning: divide by zero encountered in log
  self.feature_log_prob_ = np.log(smoothed_fc) - np.log(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:898: RuntimeWarning: divide by zero encountered in log
  self.feature_log_prob_ = np.log(smoothed_fc) - np.log(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:898: RuntimeWarning: divide by zero encountered in log
  self.feature_log_prob_ = np.log(smoothed_fc) - np.log(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:898: RuntimeWarning: divide by zero encountered in log
  self.feature_log_prob_ = np.log(smoothed_fc) - np.log(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:898: RuntimeWarning: divide by zero encountered in log
  self.feature_log_prob_ = np.log(smoothed_fc) - np.log(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:898: RuntimeWarning: divide by zero encountered in log
  self.feature_log_prob_ = np.log(smoothed_fc) - np.log(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:898: RuntimeWarning: divide by zero encountered in log
  self.feature_log_prob_ = np.log(smoothed_fc) - np.log(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:898: RuntimeWarning: divide by zero encountered in log
  self.feature_log_prob_ = np.log(smoothed_fc) - np.log(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(

   mean_test_score                                                      params
1         0.529199     {'alpha': 0.0, 'fit_prior': True, 'force_alpha': False}
5         0.529199     {'alpha': 0.0, 'fit_prior': True, 'force_alpha': False}
9         0.529199  {'alpha': 1e-100, 'fit_prior': True, 'force_alpha': False}
3         0.528077    {'alpha': 0.0, 'fit_prior': False, 'force_alpha': False}
7         0.528077    {'alpha': 0.0, 'fit_prior': False, 'force_alpha': False}
8         0.514005   {'alpha': 1e-100, 'fit_prior': True, 'force_alpha': True}
0         0.158042      {'alpha': 0.0, 'fit_prior': True, 'force_alpha': True}
2         0.158042     {'alpha': 0.0, 'fit_prior': False, 'force_alpha': True}
4         0.158042      {'alpha': 0.0, 'fit_prior': True, 'force_alpha': True}
6         0.158042     {'alpha': 0.0, 'fit_prior': False, 'force_alpha': True}

In [30]:
nb = MultinomialNB(alpha= 0, fit_prior= True, force_alpha= False)
nb.fit(x_train, y_train)
y_pred = nb.predict(x_test)
print(classification_report(y_test , y_pred))

               precision    recall  f1-score   support

     analysis       0.67      0.52      0.59        56
  application       0.54      0.63      0.58        59
comprehension       0.59      0.64      0.61        74
   evaluation       0.67      0.72      0.69        57
    knowledge       0.68      0.52      0.59        54
    synthesis       0.52      0.59      0.55        56

     accuracy                           0.60       356
    macro avg       0.61      0.60      0.60       356
 weighted avg       0.61      0.60      0.60       356