# Import Libraries

In [1]:
import pandas as pd
import numpy as np
import h5py
import spacy
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.model_selection import GridSearchCV, cross_val_score
from sklearn.ensemble import RandomForestClassifier
import matplotlib.pyplot as plt
import os
import string as st
import tensorflow as tf
from sklearn.decomposition import PCA, TruncatedSVD
from imblearn.ensemble import BalancedBaggingClassifier
from imblearn.combine import SMOTETomek
from imblearn.under_sampling import NearMiss
from sklearn.tree import DecisionTreeClassifier
from xgboost import XGBClassifier
from collections import Counter
from sklearn.svm import SVC, LinearSVC
from sklearn.naive_bayes import MultinomialNB

import warnings
warnings.filterwarnings('ignore')
pd.set_option('display.max_columns', None)  # Show all columns
pd.set_option('display.max_rows', None)  # Show all rows
pd.set_option('display.max_colwidth', None)  # Show full content in each cell
pd.set_option('display.width', 1000)  # Set max width

# Load spaCy's English model
nlp = spacy.load('en_core_web_sm')

# Linguistic Modules

In [2]:
def preprocess_text(text):
    # Define interrogative words to KEEP
    interrogatives = {"what", "why", "how", "who", "where", "when", "which", "whom", "whose", "no", "not",
                    "very" ,"too" ,"too" ,"just", "if", "but", "however", "without", "like"}
    custom_stopwords = set(nlp.Defaults.stop_words)
    custom_stopwords -= interrogatives

    doc = nlp(text.lower().strip())  # Lowercase and remove whitespace
    
# Process tokens: lemmatize, filter stopwords/punct/numbers, keep interrogatives
    tokens = [
        token.lemma_ 
        for token in doc 
        if (
            (not token.is_stop or token.text in interrogatives) and  # Keep interrogatives
            not token.is_punct and token.is_alpha                                  # Remove punctuation
            # (token.is_alpha or token.like_num)                       # Keep words/numbers
        )
    ]

    return ' '.join(tokens)

In [3]:
def extract_linguistic_features(text):
    doc = nlp(text)
    features = {
        'num_verbs': len([token for token in doc if token.pos_ == 'VERB']),
        'num_nouns': len([token for token in doc if token.pos_ == 'NOUN']),
        'sentence_length': len(doc),
        'number_present': any(token.pos_ == 'NUM' for token in doc)
    }
    return features

# Pre-Processing

### Import Data

In [9]:
mapping = {
    'knowledge': 'knowledge',
    'remember': 'knowledge',
    'comprehension': 'comprehension',
    'understand': 'comprehension',
    'application': 'application',
    'apply': 'application',
    'analysis': 'analysis',
    'analyse': 'analysis',
    'evaluation': 'evaluation',
    'evaluate': 'evaluation',
    'synthesis': 'synthesis',
    'create': 'synthesis'
}


# Load dataset
df = pd.DataFrame()
for i in [1,2,4,5]:
    q_df = pd.read_csv(os.getcwd().replace('notebook' , 'dataset') + '/dataset' + str(i) + '.csv')
    q_df['dataset_id'] = i
    print(i)
    print(q_df['label'].value_counts())
    df = pd.concat([df , q_df])

# Apply preprocessing
df['label'] = df['label'].str.lower()
df['label'] = df['label'].replace(mapping)

df['processed_question'] = df['question'].apply(preprocess_text)
df['processed_question'] = [''.join(text) for text in df['processed_question']]

1
label
Analysis         100
Knowledge        100
Comprehension    100
Evaluation       100
Synthesis        100
Application      100
Name: count, dtype: int64
2
label
COMPREHENSION    135
APPLY             72
EVALUATE          57
ANALYSIS          56
KNOWLEDGE         50
SYNTHESIS         45
Name: count, dtype: int64
4
label
Synthesis        29
Knowledge        22
Evaluation       21
Comprehension    20
Analysis         19
Application      15
Name: count, dtype: int64
5
label
COMPREHENSION    669
KNOWLEDGE        149
EVALUATION       107
APPLICATION      100
ANALYSIS          99
SYNTHESIS         76
Name: count, dtype: int64

In [5]:
mapping = {
    'knowledge': 'knowledge',
    'remember': 'knowledge',
    'comprehension': 'comprehension',
    'understand': 'comprehension',
    'application': 'application',
    'apply': 'application',
    'analysis': 'analysis',
    'analyse': 'analysis',
    'evaluation': 'evaluation',
    'evaluate': 'evaluation',
    'synthesis': 'synthesis',
    'create': 'synthesis'
}

# Load dataset
test_df = pd.read_csv(os.getcwd().replace('notebook' , 'dataset') + '/dataset' + str(3) + '.csv')
    
test_df = test_df.reset_index(drop=True)

# Apply preprocessing
test_df['label'] = test_df['label'].str.lower()
test_df['label'] = test_df['label'].replace(mapping)

test_df['processed_question'] = test_df['question'].apply(preprocess_text)
test_df['processed_question'] = [''.join(text) for text in test_df['processed_question']]

## Tokenize

### Vectorization

In [11]:
# token_pattern: words of 2+ word-chars, but not all digits
token_pattern = r"(?u)\b[a-zA-Z]{3,}\b"

vectorizer = TfidfVectorizer(
    min_df= 5 , ngram_range=(1,2), use_idf= True, norm= 'l2', token_pattern= token_pattern
                             )
tfidf = vectorizer.fit_transform(df['processed_question'])

# Convert TF-IDF sparse matrix to DataFrame with appropriate column names
tfidf_df = pd.DataFrame(tfidf.toarray(), columns= vectorizer.get_feature_names_out(), index=df.index)

print('Training Shape: ' + str(tfidf_df.shape))

Training Shape: (2341, 946)

In [12]:
test_tfidf = vectorizer.transform(test_df['processed_question'])

# Convert TF-IDF sparse matrix to DataFrame with appropriate column names
test_tfidf_df = pd.DataFrame(test_tfidf.toarray(), columns= vectorizer.get_feature_names_out(), index=test_df.index)

print('Test Shape: ' + str(test_tfidf_df.shape))

Test Shape: (181, 946)

### Label Balancing

### NOTE: Run below resampling if dataset 1 , 4 or both included

In [13]:
mask = df['dataset_id'].isin([5,6])
to_us_df   = df[mask]
to_keep_df = df[~mask]

to_keep = vectorizer.transform(to_keep_df['processed_question'])
to_us = vectorizer.transform(to_us_df['processed_question'])

df_to_us = pd.DataFrame(
    to_us.toarray(), 
    columns=vectorizer.get_feature_names_out()
)

df_to_keep = pd.DataFrame(
    to_keep.toarray(), 
    columns=vectorizer.get_feature_names_out()
)
df_to_keep['bt_label'] = to_keep_df['label'].values

x , y = df_to_us , to_us_df['label']
x_resampled , y_resampled = NearMiss().fit_resample(x , y)


x_resampled['bt_label'] = y_resampled

df_final = pd.concat([df_to_keep, x_resampled], ignore_index=True)

print(df_final.shape)
print(df_final['bt_label'].value_counts())

x = df_final.drop(columns= 'bt_label')
y = df_final['bt_label']

:

### Else run below, no need for resampling

In [8]:
x , y = tfidf_df , df['label']
print(x.shape)
print(y.value_counts())

# x , y = x_resampled , y_resampled

(2341, 946)
label
comprehension    924
knowledge        321
application      287
evaluation       285
analysis         274
synthesis        250
Name: count, dtype: int64

# Modelling

## Basic Machine Learning

In [10]:
x_train , x_test , y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=34 , stratify= y)

In [ ]:
x_train , y_train = tfidf_df , df['label']
x_test , y_test = test_tfidf , test_df['label']

### Random Forest

In [82]:
params = {
    'n_estimators' : [2 , 5 , 10 , 100, 250 , 500],
    'criterion' : ['gini' , 'entropy'],
    # 'max_depth' : [None , 10 , 100 , 250 , 500]
}
param_search = GridSearchCV(estimator= RandomForestClassifier(), param_grid= params, cv=5, n_jobs= -1, verbose= 2)

param_search.fit(x, y)

cv_results = pd.DataFrame(param_search.cv_results_)
cv_results = cv_results[["mean_test_score", "params"]].head(10).sort_values(by="mean_test_score", ascending=False)

cv_results

Fitting 5 folds for each of 12 candidates, totalling 60 fits
[CV] END .....................criterion=gini, n_estimators=2; total time=   0.1s
[CV] END .....................criterion=gini, n_estimators=2; total time=   0.0s
[CV] END .....................criterion=gini, n_estimators=2; total time=   0.1s
[CV] END .....................criterion=gini, n_estimators=2; total time=   0.1s
[CV] END .....................criterion=gini, n_estimators=5; total time=   0.1s
[CV] END .....................criterion=gini, n_estimators=2; total time=   0.1s
[CV] END ....................criterion=gini, n_estimators=10; total time=   0.1s
[CV] END .....................criterion=gini, n_estimators=5; total time=   0.1s
[CV] END ....................criterion=gini, n_estimators=10; total time=   0.1s
[CV] END .....................criterion=gini, n_estimators=5; total time=   0.1s
[CV] END ....................criterion=gini, n_estimators=10; total time=   0.1s
[CV] END .....................criterion=gini, n_estimators=5; total time=   0.0s
[CV] END ....................criterion=gini, n_estimators=10; total time=   0.1s
[CV] END .....................criterion=gini, n_estimators=5; total time=   0.0s
[CV] END ....................criterion=gini, n_estimators=10; total time=   0.1s
[CV] END ...................criterion=gini, n_estimators=100; total time=   0.3s
[CV] END ...................criterion=gini, n_estimators=100; total time=   0.3s
[CV] END ...................criterion=gini, n_estimators=100; total time=   0.3s
[CV] END ...................criterion=gini, n_estimators=100; total time=   0.3s
[CV] END ...................criterion=gini, n_estimators=100; total time=   0.4s
[CV] END ..................criterion=entropy, n_estimators=2; total time=   0.0s
[CV] END ..................criterion=entropy, n_estimators=2; total time=   0.0s
[CV] END ..................criterion=entropy, n_estimators=2; total time=   0.1s
[CV] END ..................criterion=entropy, n_estimators=2; total time=   0.1s
[CV] END ..................criterion=entropy, n_estimators=2; total time=   0.0s
[CV] END ...................criterion=gini, n_estimators=250; total time=   0.9s
[CV] END ..................criterion=entropy, n_estimators=5; total time=   0.1s
[CV] END ...................criterion=gini, n_estimators=250; total time=   0.9s
[CV] END ...................criterion=gini, n_estimators=250; total time=   1.0s
[CV] END ..................criterion=entropy, n_estimators=5; total time=   0.0s
[CV] END ...................criterion=gini, n_estimators=250; total time=   1.0s
[CV] END ..................criterion=entropy, n_estimators=5; total time=   0.0s
[CV] END ...................criterion=gini, n_estimators=250; total time=   0.9s
[CV] END ..................criterion=entropy, n_estimators=5; total time=   0.0s
[CV] END ..................criterion=entropy, n_estimators=5; total time=   0.0s
[CV] END .................criterion=entropy, n_estimators=10; total time=   0.1s
[CV] END .................criterion=entropy, n_estimators=10; total time=   0.1s
[CV] END .................criterion=entropy, n_estimators=10; total time=   0.1s
[CV] END .................criterion=entropy, n_estimators=10; total time=   0.1s
[CV] END .................criterion=entropy, n_estimators=10; total time=   0.1s
[CV] END ................criterion=entropy, n_estimators=100; total time=   0.4s
[CV] END ................criterion=entropy, n_estimators=100; total time=   0.4s
[CV] END ................criterion=entropy, n_estimators=100; total time=   0.4s
[CV] END ................criterion=entropy, n_estimators=100; total time=   0.4s
[CV] END ...................criterion=gini, n_estimators=500; total time=   1.7s
[CV] END ................criterion=entropy, n_estimators=100; total time=   0.5s
[CV] END ...................criterion=gini, n_estimators=500; total time=   1.7s
[CV] END ...................criterion=gini, n_estimators=500; total time=   1.8s
[CV] END ...................criterion=gini, n_estimators=500; total time=   1.8s
[CV] END ...................criterion=gini, n_estimators=500; total time=   2.0s
[CV] END ................criterion=entropy, n_estimators=250; total time=   1.1s
[CV] END ................criterion=entropy, n_estimators=250; total time=   0.9s
[CV] END ................criterion=entropy, n_estimators=250; total time=   1.0s
[CV] END ................criterion=entropy, n_estimators=250; total time=   1.0s
[CV] END ................criterion=entropy, n_estimators=250; total time=   0.9s
[CV] END ................criterion=entropy, n_estimators=500; total time=   1.5s
[CV] END ................criterion=entropy, n_estimators=500; total time=   1.5s
[CV] END ................criterion=entropy, n_estimators=500; total time=   1.4s
[CV] END ................criterion=entropy, n_estimators=500; total time=   1.4s
[CV] END ................criterion=entropy, n_estimators=500; total time=   1.3s

   mean_test_score                                         params
4         0.756336     {'criterion': 'gini', 'n_estimators': 250}
3         0.756325     {'criterion': 'gini', 'n_estimators': 100}
5         0.754641     {'criterion': 'gini', 'n_estimators': 500}
9         0.743577  {'criterion': 'entropy', 'n_estimators': 100}
8         0.729181   {'criterion': 'entropy', 'n_estimators': 10}
2         0.722340      {'criterion': 'gini', 'n_estimators': 10}
1         0.703668       {'criterion': 'gini', 'n_estimators': 5}
7         0.692647    {'criterion': 'entropy', 'n_estimators': 5}
0         0.600090       {'criterion': 'gini', 'n_estimators': 2}
6         0.585683    {'criterion': 'entropy', 'n_estimators': 2}

In [83]:
classifier = RandomForestClassifier(n_estimators=250 , criterion= 'gini', n_jobs= -1)
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
print(classification_report(y_test , y_pred))

               precision    recall  f1-score   support

     analysis       0.79      0.59      0.67       100
  application       0.55      0.52      0.54       100
comprehension       0.33      0.39      0.36       100
   evaluation       0.86      0.36      0.51       100
    knowledge       0.37      0.77      0.50       100
    synthesis       0.70      0.43      0.53       100

     accuracy                           0.51       600
    macro avg       0.60      0.51      0.52       600
 weighted avg       0.60      0.51      0.52       600

In [84]:
question = 'What are different types of single level indexing?'
processed_q = preprocess_text(question)
tfidf_q = vectorizer.transform([processed_q])
tfidf_q = pd.DataFrame(tfidf_q.toarray(), columns=vectorizer.get_feature_names_out())



# Adding linguistic features
q_ling_features = pd.DataFrame([extract_linguistic_features(question)])

# Concatenate DataFrames
token_q = pd.concat([q_ling_features, tfidf_q], axis=1)

print(classifier.predict(tfidf_q))

['knowledge']

### Decision Tree

In [85]:
params = {
    'min_samples_split' : [2 , 5 , 10 , 50 , 100],
    'criterion' : ['gini' , 'entropy'],
    'max_depth' : [None , 5 , 10 , 50 , 100 , 250 , 500]
}
param_search = GridSearchCV(estimator= DecisionTreeClassifier(), param_grid= params, cv=5, n_jobs= -1, verbose= 2)

param_search.fit(x , y)

cv_results = pd.DataFrame(param_search.cv_results_)
cv_results = cv_results[["mean_test_score", "params"]].head(10).sort_values(by="mean_test_score", ascending=False)

cv_results

Fitting 5 folds for each of 70 candidates, totalling 350 fits
[CV] END criterion=gini, max_depth=None, min_samples_split=2; total time=   0.1s
[CV] END criterion=gini, max_depth=None, min_samples_split=2; total time=   0.1s
[CV] END criterion=gini, max_depth=None, min_samples_split=2; total time=   0.1s
[CV] END criterion=gini, max_depth=None, min_samples_split=2; total time=   0.1s
[CV] END criterion=gini, max_depth=None, min_samples_split=2; total time=   0.1s
[CV] END criterion=gini, max_depth=None, min_samples_split=5; total time=   0.1s
[CV] END criterion=gini, max_depth=None, min_samples_split=5; total time=   0.1s
[CV] END criterion=gini, max_depth=None, min_samples_split=5; total time=   0.1s
[CV] END criterion=gini, max_depth=None, min_samples_split=5; total time=   0.1s
[CV] END criterion=gini, max_depth=None, min_samples_split=5; total time=   0.1s
[CV] END criterion=gini, max_depth=None, min_samples_split=10; total time=   0.1s
[CV] END criterion=gini, max_depth=None, min_samples_split=10; total time=   0.1s
[CV] END criterion=gini, max_depth=None, min_samples_split=10; total time=   0.1s
[CV] END criterion=gini, max_depth=None, min_samples_split=10; total time=   0.1s
[CV] END criterion=gini, max_depth=None, min_samples_split=10; total time=   0.1s
[CV] END criterion=gini, max_depth=None, min_samples_split=50; total time=   0.1s
[CV] END criterion=gini, max_depth=None, min_samples_split=50; total time=   0.1s
[CV] END criterion=gini, max_depth=None, min_samples_split=50; total time=   0.1s
[CV] END criterion=gini, max_depth=None, min_samples_split=50; total time=   0.1s
[CV] END criterion=gini, max_depth=None, min_samples_split=50; total time=   0.1s
[CV] END criterion=gini, max_depth=None, min_samples_split=100; total time=   0.1s
[CV] END criterion=gini, max_depth=None, min_samples_split=100; total time=   0.1s
[CV] END criterion=gini, max_depth=None, min_samples_split=100; total time=   0.1s
[CV] END criterion=gini, max_depth=None, min_samples_split=100; total time=   0.1s
[CV] END ...criterion=gini, max_depth=5, min_samples_split=2; total time=   0.0s
[CV] END criterion=gini, max_depth=None, min_samples_split=100; total time=   0.1s
[CV] END ...criterion=gini, max_depth=5, min_samples_split=2; total time=   0.0s
[CV] END ...criterion=gini, max_depth=5, min_samples_split=2; total time=   0.0s
[CV] END ...criterion=gini, max_depth=5, min_samples_split=5; total time=   0.0s
[CV] END ...criterion=gini, max_depth=5, min_samples_split=2; total time=   0.1s
[CV] END ...criterion=gini, max_depth=5, min_samples_split=2; total time=   0.0s
[CV] END ...criterion=gini, max_depth=5, min_samples_split=5; total time=   0.0s
[CV] END ...criterion=gini, max_depth=5, min_samples_split=5; total time=   0.0s
[CV] END ...criterion=gini, max_depth=5, min_samples_split=5; total time=   0.0s
[CV] END ...criterion=gini, max_depth=5, min_samples_split=5; total time=   0.1s
[CV] END ..criterion=gini, max_depth=5, min_samples_split=10; total time=   0.0s
[CV] END ..criterion=gini, max_depth=5, min_samples_split=10; total time=   0.0s
[CV] END ..criterion=gini, max_depth=5, min_samples_split=10; total time=   0.0s
[CV] END ..criterion=gini, max_depth=5, min_samples_split=10; total time=   0.1s
[CV] END ..criterion=gini, max_depth=5, min_samples_split=50; total time=   0.0s
[CV] END ..criterion=gini, max_depth=5, min_samples_split=50; total time=   0.1s
[CV] END ..criterion=gini, max_depth=5, min_samples_split=10; total time=   0.0s
[CV] END ..criterion=gini, max_depth=5, min_samples_split=50; total time=   0.0s
[CV] END ..criterion=gini, max_depth=5, min_samples_split=50; total time=   0.0s
[CV] END ..criterion=gini, max_depth=5, min_samples_split=50; total time=   0.0s
[CV] END .criterion=gini, max_depth=5, min_samples_split=100; total time=   0.0s
[CV] END .criterion=gini, max_depth=5, min_samples_split=100; total time=   0.1s
[CV] END .criterion=gini, max_depth=5, min_samples_split=100; total time=   0.1s
[CV] END ..criterion=gini, max_depth=10, min_samples_split=2; total time=   0.0s
[CV] END .criterion=gini, max_depth=5, min_samples_split=100; total time=   0.0s
[CV] END .criterion=gini, max_depth=5, min_samples_split=100; total time=   0.0s
[CV] END ..criterion=gini, max_depth=10, min_samples_split=2; total time=   0.0s
[CV] END ..criterion=gini, max_depth=10, min_samples_split=2; total time=   0.0s
[CV] END ..criterion=gini, max_depth=10, min_samples_split=2; total time=   0.0s
[CV] END ..criterion=gini, max_depth=10, min_samples_split=2; total time=   0.0s
[CV] END ..criterion=gini, max_depth=10, min_samples_split=5; total time=   0.0s
[CV] END ..criterion=gini, max_depth=10, min_samples_split=5; total time=   0.0s
[CV] END ..criterion=gini, max_depth=10, min_samples_split=5; total time=   0.0s
[CV] END .criterion=gini, max_depth=10, min_samples_split=10; total time=   0.0s
[CV] END ..criterion=gini, max_depth=10, min_samples_split=5; total time=   0.0s
[CV] END ..criterion=gini, max_depth=10, min_samples_split=5; total time=   0.0s
[CV] END .criterion=gini, max_depth=10, min_samples_split=10; total time=   0.0s
[CV] END .criterion=gini, max_depth=10, min_samples_split=10; total time=   0.0s
[CV] END .criterion=gini, max_depth=10, min_samples_split=10; total time=   0.0s
[CV] END .criterion=gini, max_depth=10, min_samples_split=10; total time=   0.0s
[CV] END .criterion=gini, max_depth=10, min_samples_split=50; total time=   0.0s
[CV] END .criterion=gini, max_depth=10, min_samples_split=50; total time=   0.0s
[CV] END criterion=gini, max_depth=10, min_samples_split=100; total time=   0.0s
[CV] END .criterion=gini, max_depth=10, min_samples_split=50; total time=   0.0s
[CV] END .criterion=gini, max_depth=10, min_samples_split=50; total time=   0.1s
[CV] END criterion=gini, max_depth=10, min_samples_split=100; total time=   0.0s
[CV] END criterion=gini, max_depth=10, min_samples_split=100; total time=   0.0s
[CV] END .criterion=gini, max_depth=10, min_samples_split=50; total time=   0.0s
[CV] END criterion=gini, max_depth=10, min_samples_split=100; total time=   0.0s
[CV] END criterion=gini, max_depth=10, min_samples_split=100; total time=   0.1s
[CV] END ..criterion=gini, max_depth=50, min_samples_split=2; total time=   0.1s
[CV] END ..criterion=gini, max_depth=50, min_samples_split=2; total time=   0.1s
[CV] END ..criterion=gini, max_depth=50, min_samples_split=2; total time=   0.1s
[CV] END ..criterion=gini, max_depth=50, min_samples_split=2; total time=   0.1s
[CV] END ..criterion=gini, max_depth=50, min_samples_split=5; total time=   0.1s
[CV] END ..criterion=gini, max_depth=50, min_samples_split=2; total time=   0.1s
[CV] END ..criterion=gini, max_depth=50, min_samples_split=5; total time=   0.1s
[CV] END ..criterion=gini, max_depth=50, min_samples_split=5; total time=   0.1s
[CV] END ..criterion=gini, max_depth=50, min_samples_split=5; total time=   0.1s
[CV] END .criterion=gini, max_depth=50, min_samples_split=10; total time=   0.1s
[CV] END ..criterion=gini, max_depth=50, min_samples_split=5; total time=   0.1s
[CV] END .criterion=gini, max_depth=50, min_samples_split=10; total time=   0.1s
[CV] END .criterion=gini, max_depth=50, min_samples_split=10; total time=   0.1s
[CV] END .criterion=gini, max_depth=50, min_samples_split=50; total time=   0.1s
[CV] END .criterion=gini, max_depth=50, min_samples_split=10; total time=   0.1s
[CV] END .criterion=gini, max_depth=50, min_samples_split=10; total time=   0.1s
[CV] END .criterion=gini, max_depth=50, min_samples_split=50; total time=   0.1s
[CV] END .criterion=gini, max_depth=50, min_samples_split=50; total time=   0.1s
[CV] END .criterion=gini, max_depth=50, min_samples_split=50; total time=   0.1s
[CV] END criterion=gini, max_depth=50, min_samples_split=100; total time=   0.1s
[CV] END criterion=gini, max_depth=50, min_samples_split=100; total time=   0.0s
[CV] END .criterion=gini, max_depth=50, min_samples_split=50; total time=   0.1s
[CV] END criterion=gini, max_depth=50, min_samples_split=100; total time=   0.1s
[CV] END criterion=gini, max_depth=50, min_samples_split=100; total time=   0.1s
[CV] END .criterion=gini, max_depth=100, min_samples_split=2; total time=   0.1s
[CV] END criterion=gini, max_depth=50, min_samples_split=100; total time=   0.1s
[CV] END .criterion=gini, max_depth=100, min_samples_split=2; total time=   0.1s
[CV] END .criterion=gini, max_depth=100, min_samples_split=2; total time=   0.1s
[CV] END .criterion=gini, max_depth=100, min_samples_split=2; total time=   0.1s
[CV] END .criterion=gini, max_depth=100, min_samples_split=5; total time=   0.1s
[CV] END .criterion=gini, max_depth=100, min_samples_split=2; total time=   0.1s
[CV] END .criterion=gini, max_depth=100, min_samples_split=5; total time=   0.1s
[CV] END .criterion=gini, max_depth=100, min_samples_split=5; total time=   0.1s
[CV] END criterion=gini, max_depth=100, min_samples_split=10; total time=   0.1s
[CV] END .criterion=gini, max_depth=100, min_samples_split=5; total time=   0.1s
[CV] END criterion=gini, max_depth=100, min_samples_split=10; total time=   0.1s
[CV] END .criterion=gini, max_depth=100, min_samples_split=5; total time=   0.1s
[CV] END criterion=gini, max_depth=100, min_samples_split=10; total time=   0.1s
[CV] END criterion=gini, max_depth=100, min_samples_split=50; total time=   0.1s
[CV] END criterion=gini, max_depth=100, min_samples_split=10; total time=   0.1s
[CV] END criterion=gini, max_depth=100, min_samples_split=10; total time=   0.1s
[CV] END criterion=gini, max_depth=100, min_samples_split=50; total time=   0.1s
[CV] END criterion=gini, max_depth=100, min_samples_split=50; total time=   0.1s
[CV] END criterion=gini, max_depth=100, min_samples_split=50; total time=   0.1s
[CV] END criterion=gini, max_depth=100, min_samples_split=100; total time=   0.1s
[CV] END criterion=gini, max_depth=100, min_samples_split=100; total time=   0.1s
[CV] END criterion=gini, max_depth=100, min_samples_split=100; total time=   0.1s
[CV] END criterion=gini, max_depth=100, min_samples_split=50; total time=   0.1s
[CV] END criterion=gini, max_depth=100, min_samples_split=100; total time=   0.1s
[CV] END criterion=gini, max_depth=100, min_samples_split=100; total time=   0.1s
[CV] END .criterion=gini, max_depth=250, min_samples_split=2; total time=   0.1s
[CV] END .criterion=gini, max_depth=250, min_samples_split=2; total time=   0.1s
[CV] END .criterion=gini, max_depth=250, min_samples_split=2; total time=   0.1s
[CV] END .criterion=gini, max_depth=250, min_samples_split=2; total time=   0.1s
[CV] END .criterion=gini, max_depth=250, min_samples_split=5; total time=   0.1s
[CV] END .criterion=gini, max_depth=250, min_samples_split=5; total time=   0.1s
[CV] END .criterion=gini, max_depth=250, min_samples_split=2; total time=   0.1s
[CV] END .criterion=gini, max_depth=250, min_samples_split=5; total time=   0.1s
[CV] END .criterion=gini, max_depth=250, min_samples_split=5; total time=   0.1s
[CV] END .criterion=gini, max_depth=250, min_samples_split=5; total time=   0.1s
[CV] END criterion=gini, max_depth=250, min_samples_split=10; total time=   0.1s
[CV] END criterion=gini, max_depth=250, min_samples_split=10; total time=   0.1s
[CV] END criterion=gini, max_depth=250, min_samples_split=10; total time=   0.1s
[CV] END criterion=gini, max_depth=250, min_samples_split=10; total time=   0.1s
[CV] END criterion=gini, max_depth=250, min_samples_split=50; total time=   0.1s
[CV] END criterion=gini, max_depth=250, min_samples_split=10; total time=   0.1s
[CV] END criterion=gini, max_depth=250, min_samples_split=50; total time=   0.1s
[CV] END criterion=gini, max_depth=250, min_samples_split=50; total time=   0.1s
[CV] END criterion=gini, max_depth=250, min_samples_split=50; total time=   0.1s
[CV] END criterion=gini, max_depth=250, min_samples_split=100; total time=   0.1s
[CV] END criterion=gini, max_depth=250, min_samples_split=50; total time=   0.1s
[CV] END criterion=gini, max_depth=250, min_samples_split=100; total time=   0.1s
[CV] END criterion=gini, max_depth=250, min_samples_split=100; total time=   0.1s
[CV] END criterion=gini, max_depth=250, min_samples_split=100; total time=   0.0s
[CV] END .criterion=gini, max_depth=500, min_samples_split=2; total time=   0.1s
[CV] END criterion=gini, max_depth=250, min_samples_split=100; total time=   0.0s
[CV] END .criterion=gini, max_depth=500, min_samples_split=2; total time=   0.1s
[CV] END .criterion=gini, max_depth=500, min_samples_split=2; total time=   0.1s
[CV] END .criterion=gini, max_depth=500, min_samples_split=2; total time=   0.1s
[CV] END .criterion=gini, max_depth=500, min_samples_split=5; total time=   0.1s
[CV] END .criterion=gini, max_depth=500, min_samples_split=2; total time=   0.1s
[CV] END .criterion=gini, max_depth=500, min_samples_split=5; total time=   0.1s
[CV] END .criterion=gini, max_depth=500, min_samples_split=5; total time=   0.1s
[CV] END .criterion=gini, max_depth=500, min_samples_split=5; total time=   0.1s
[CV] END criterion=gini, max_depth=500, min_samples_split=10; total time=   0.1s
[CV] END criterion=gini, max_depth=500, min_samples_split=10; total time=   0.1s
[CV] END .criterion=gini, max_depth=500, min_samples_split=5; total time=   0.1s
[CV] END criterion=gini, max_depth=500, min_samples_split=10; total time=   0.1s
[CV] END criterion=gini, max_depth=500, min_samples_split=10; total time=   0.1s
[CV] END criterion=gini, max_depth=500, min_samples_split=50; total time=   0.1s
[CV] END criterion=gini, max_depth=500, min_samples_split=10; total time=   0.1s
[CV] END criterion=gini, max_depth=500, min_samples_split=50; total time=   0.1s
[CV] END criterion=gini, max_depth=500, min_samples_split=50; total time=   0.1s
[CV] END criterion=gini, max_depth=500, min_samples_split=50; total time=   0.1s
[CV] END criterion=gini, max_depth=500, min_samples_split=100; total time=   0.1s
[CV] END criterion=gini, max_depth=500, min_samples_split=100; total time=   0.0s
[CV] END criterion=gini, max_depth=500, min_samples_split=50; total time=   0.1s
[CV] END criterion=gini, max_depth=500, min_samples_split=100; total time=   0.1s
[CV] END criterion=gini, max_depth=500, min_samples_split=100; total time=   0.0s
[CV] END criterion=entropy, max_depth=None, min_samples_split=2; total time=   0.1s
[CV] END criterion=gini, max_depth=500, min_samples_split=100; total time=   0.1s
[CV] END criterion=entropy, max_depth=None, min_samples_split=2; total time=   0.1s
[CV] END criterion=entropy, max_depth=None, min_samples_split=5; total time=   0.1s
[CV] END criterion=entropy, max_depth=None, min_samples_split=2; total time=   0.1s
[CV] END criterion=entropy, max_depth=None, min_samples_split=2; total time=   0.1s
[CV] END criterion=entropy, max_depth=None, min_samples_split=5; total time=   0.1s
[CV] END criterion=entropy, max_depth=None, min_samples_split=5; total time=   0.1s
[CV] END criterion=entropy, max_depth=None, min_samples_split=5; total time=   0.1s
[CV] END criterion=entropy, max_depth=None, min_samples_split=10; total time=   0.1s
[CV] END criterion=entropy, max_depth=None, min_samples_split=2; total time=   0.1s
[CV] END criterion=entropy, max_depth=None, min_samples_split=10; total time=   0.1s
[CV] END criterion=entropy, max_depth=None, min_samples_split=5; total time=   0.1s
[CV] END criterion=entropy, max_depth=None, min_samples_split=10; total time=   0.1s
[CV] END criterion=entropy, max_depth=None, min_samples_split=10; total time=   0.1s
[CV] END criterion=entropy, max_depth=None, min_samples_split=50; total time=   0.1s
[CV] END criterion=entropy, max_depth=None, min_samples_split=50; total time=   0.1s
[CV] END criterion=entropy, max_depth=None, min_samples_split=10; total time=   0.1s
[CV] END criterion=entropy, max_depth=None, min_samples_split=50; total time=   0.1s
[CV] END criterion=entropy, max_depth=None, min_samples_split=50; total time=   0.0s
[CV] END criterion=entropy, max_depth=None, min_samples_split=50; total time=   0.1s
[CV] END criterion=entropy, max_depth=None, min_samples_split=100; total time=   0.1s
[CV] END criterion=entropy, max_depth=5, min_samples_split=2; total time=   0.0s
[CV] END criterion=entropy, max_depth=None, min_samples_split=100; total time=   0.1s
[CV] END criterion=entropy, max_depth=None, min_samples_split=100; total time=   0.1s
[CV] END criterion=entropy, max_depth=None, min_samples_split=100; total time=   0.1s
[CV] END criterion=entropy, max_depth=5, min_samples_split=2; total time=   0.0s
[CV] END criterion=entropy, max_depth=5, min_samples_split=2; total time=   0.1s
[CV] END criterion=entropy, max_depth=5, min_samples_split=2; total time=   0.0s
[CV] END criterion=entropy, max_depth=None, min_samples_split=100; total time=   0.1s
[CV] END criterion=entropy, max_depth=5, min_samples_split=2; total time=   0.0s
[CV] END criterion=entropy, max_depth=5, min_samples_split=5; total time=   0.0s
[CV] END criterion=entropy, max_depth=5, min_samples_split=5; total time=   0.1s
[CV] END criterion=entropy, max_depth=5, min_samples_split=5; total time=   0.0s
[CV] END criterion=entropy, max_depth=5, min_samples_split=10; total time=   0.0s
[CV] END criterion=entropy, max_depth=5, min_samples_split=5; total time=   0.0s
[CV] END criterion=entropy, max_depth=5, min_samples_split=5; total time=   0.0s
[CV] END criterion=entropy, max_depth=5, min_samples_split=10; total time=   0.0s
[CV] END criterion=entropy, max_depth=5, min_samples_split=10; total time=   0.0s
[CV] END criterion=entropy, max_depth=5, min_samples_split=10; total time=   0.0s
[CV] END criterion=entropy, max_depth=5, min_samples_split=10; total time=   0.0s
[CV] END criterion=entropy, max_depth=5, min_samples_split=50; total time=   0.0s
[CV] END criterion=entropy, max_depth=5, min_samples_split=50; total time=   0.0s
[CV] END criterion=entropy, max_depth=5, min_samples_split=50; total time=   0.0s
[CV] END criterion=entropy, max_depth=5, min_samples_split=50; total time=   0.1s
[CV] END criterion=entropy, max_depth=5, min_samples_split=100; total time=   0.0s
[CV] END criterion=entropy, max_depth=5, min_samples_split=50; total time=   0.0s
[CV] END criterion=entropy, max_depth=5, min_samples_split=100; total time=   0.0s
[CV] END criterion=entropy, max_depth=5, min_samples_split=100; total time=   0.1s
[CV] END criterion=entropy, max_depth=5, min_samples_split=100; total time=   0.1s
[CV] END criterion=entropy, max_depth=10, min_samples_split=2; total time=   0.0s
[CV] END criterion=entropy, max_depth=5, min_samples_split=100; total time=   0.0s
[CV] END criterion=entropy, max_depth=10, min_samples_split=2; total time=   0.0s
[CV] END criterion=entropy, max_depth=10, min_samples_split=2; total time=   0.0s
[CV] END criterion=entropy, max_depth=10, min_samples_split=2; total time=   0.0s
[CV] END criterion=entropy, max_depth=10, min_samples_split=2; total time=   0.0s
[CV] END criterion=entropy, max_depth=10, min_samples_split=5; total time=   0.0s
[CV] END criterion=entropy, max_depth=10, min_samples_split=5; total time=   0.1s
[CV] END criterion=entropy, max_depth=10, min_samples_split=5; total time=   0.0s
[CV] END criterion=entropy, max_depth=10, min_samples_split=10; total time=   0.0s
[CV] END criterion=entropy, max_depth=10, min_samples_split=5; total time=   0.0s
[CV] END criterion=entropy, max_depth=10, min_samples_split=5; total time=   0.0s
[CV] END criterion=entropy, max_depth=10, min_samples_split=10; total time=   0.0s
[CV] END criterion=entropy, max_depth=10, min_samples_split=10; total time=   0.0s
[CV] END criterion=entropy, max_depth=10, min_samples_split=10; total time=   0.1s
[CV] END criterion=entropy, max_depth=10, min_samples_split=10; total time=   0.0s
[CV] END criterion=entropy, max_depth=10, min_samples_split=50; total time=   0.0s
[CV] END criterion=entropy, max_depth=10, min_samples_split=50; total time=   0.1s
[CV] END criterion=entropy, max_depth=10, min_samples_split=50; total time=   0.0s

   mean_test_score                                                              params
0         0.732557    {'criterion': 'gini', 'max_depth': None, 'min_samples_split': 2}
1         0.728312    {'criterion': 'gini', 'max_depth': None, 'min_samples_split': 5}
2         0.713869   {'criterion': 'gini', 'max_depth': None, 'min_samples_split': 10}
3         0.692712   {'criterion': 'gini', 'max_depth': None, 'min_samples_split': 50}
4         0.657075  {'criterion': 'gini', 'max_depth': None, 'min_samples_split': 100}
5         0.405777       {'criterion': 'gini', 'max_depth': 5, 'min_samples_split': 2}
7         0.405777      {'criterion': 'gini', 'max_depth': 5, 'min_samples_split': 10}
8         0.405777      {'criterion': 'gini', 'max_depth': 5, 'min_samples_split': 50}
6         0.404926       {'criterion': 'gini', 'max_depth': 5, 'min_samples_split': 5}
9         0.404082     {'criterion': 'gini', 'max_depth': 5, 'min_samples_split': 100}

In [86]:
dt = DecisionTreeClassifier(criterion= 'gini', max_depth= None, min_samples_split = 2)
dt.fit(x_train, y_train)
y_pred = dt.predict(x_test)
print(classification_report(y_test , y_pred))

               precision    recall  f1-score   support

     analysis       0.87      0.60      0.71       100
  application       0.45      0.56      0.50       100
comprehension       0.33      0.41      0.37       100
   evaluation       0.81      0.35      0.49       100
    knowledge       0.41      0.77      0.54       100
    synthesis       0.69      0.37      0.48       100

     accuracy                           0.51       600
    macro avg       0.59      0.51      0.51       600
 weighted avg       0.59      0.51      0.51       600

In [87]:
question = 'What are different types of single level indexing?'
processed_q = preprocess_text(question)
tfidf_q = vectorizer.transform([processed_q])
tfidf_q = pd.DataFrame(tfidf_q.toarray(), columns=vectorizer.get_feature_names_out())



# Adding linguistic features
q_ling_features = pd.DataFrame([extract_linguistic_features(question)])

# Concatenate DataFrames
token_q = pd.concat([q_ling_features, tfidf_q], axis=1)

print(dt.predict(tfidf_q))

['knowledge']

### XGBoost

In [88]:
y_mapper = {
    'knowledge' : 0,
    'comprehension' : 1,
    'application' : 2,
    'analysis' : 3,
    'synthesis' : 4,
    'evaluation' : 5
}

xgb_y = y.map(y_mapper)
xgb_y_train = y_train.map(y_mapper)
xgb_y_test = y_test.map(y_mapper)

In [89]:
params = {
    'max_depth' : [None , 250],
    'n_estimators': [100, 200],
    'learning_rate': [0.01, 0.1 , 0.3],
    'subsample': [0.8, 0.9]
}
param_search = GridSearchCV(estimator= XGBClassifier(objective='multi:softprob' , verbosity= 1), 
                            param_grid= params, cv=5, n_jobs= -1,return_train_score=True, verbose=2)

param_search.fit(x , xgb_y)

cv_results = pd.DataFrame(param_search.cv_results_)
cv_results = cv_results[["mean_test_score", "params"]].head(10).sort_values(by="mean_test_score", ascending=False)

cv_results

Fitting 5 folds for each of 24 candidates, totalling 120 fits
[CV] END learning_rate=0.01, max_depth=None, n_estimators=100, subsample=0.8; total time=   1.2s
[CV] END learning_rate=0.01, max_depth=None, n_estimators=100, subsample=0.8; total time=   1.3s
[CV] END learning_rate=0.01, max_depth=None, n_estimators=100, subsample=0.8; total time=   1.3s
[CV] END learning_rate=0.01, max_depth=None, n_estimators=100, subsample=0.8; total time=   1.2s
[CV] END learning_rate=0.01, max_depth=None, n_estimators=100, subsample=0.8; total time=   1.3s
[CV] END learning_rate=0.01, max_depth=None, n_estimators=100, subsample=0.9; total time=   1.3s
[CV] END learning_rate=0.01, max_depth=None, n_estimators=100, subsample=0.9; total time=   1.3s
[CV] END learning_rate=0.01, max_depth=None, n_estimators=100, subsample=0.9; total time=   1.3s
[CV] END learning_rate=0.01, max_depth=None, n_estimators=100, subsample=0.9; total time=   1.4s
[CV] END learning_rate=0.01, max_depth=None, n_estimators=100, subsample=0.9; total time=   1.5s
[CV] END learning_rate=0.01, max_depth=None, n_estimators=200, subsample=0.8; total time=   2.3s
[CV] END learning_rate=0.01, max_depth=None, n_estimators=200, subsample=0.8; total time=   2.2s
[CV] END learning_rate=0.01, max_depth=None, n_estimators=200, subsample=0.8; total time=   2.4s
[CV] END learning_rate=0.01, max_depth=None, n_estimators=200, subsample=0.9; total time=   2.3s
[CV] END learning_rate=0.01, max_depth=None, n_estimators=200, subsample=0.9; total time=   2.2s
[CV] END learning_rate=0.01, max_depth=None, n_estimators=200, subsample=0.9; total time=   2.3s
[CV] END learning_rate=0.01, max_depth=None, n_estimators=200, subsample=0.8; total time=   2.5s
[CV] END learning_rate=0.01, max_depth=None, n_estimators=200, subsample=0.9; total time=   2.3s
[CV] END learning_rate=0.01, max_depth=None, n_estimators=200, subsample=0.8; total time=   2.5s
[CV] END learning_rate=0.01, max_depth=None, n_estimators=200, subsample=0.9; total time=   2.4s
[CV] END learning_rate=0.01, max_depth=250, n_estimators=100, subsample=0.8; total time=   2.5s
[CV] END learning_rate=0.01, max_depth=250, n_estimators=100, subsample=0.8; total time=   2.6s
[CV] END learning_rate=0.01, max_depth=250, n_estimators=100, subsample=0.8; total time=   2.5s
[CV] END learning_rate=0.01, max_depth=250, n_estimators=100, subsample=0.8; total time=   2.2s
[CV] END learning_rate=0.01, max_depth=250, n_estimators=100, subsample=0.8; total time=   2.4s
[CV] END learning_rate=0.01, max_depth=250, n_estimators=100, subsample=0.9; total time=   2.6s
[CV] END learning_rate=0.01, max_depth=250, n_estimators=100, subsample=0.9; total time=   2.7s
[CV] END learning_rate=0.01, max_depth=250, n_estimators=100, subsample=0.9; total time=   2.6s
[CV] END learning_rate=0.01, max_depth=250, n_estimators=100, subsample=0.9; total time=   2.7s
[CV] END learning_rate=0.01, max_depth=250, n_estimators=100, subsample=0.9; total time=   2.6s
[CV] END learning_rate=0.1, max_depth=None, n_estimators=100, subsample=0.8; total time=   1.1s
[CV] END learning_rate=0.01, max_depth=250, n_estimators=200, subsample=0.8; total time=   4.5s
[CV] END learning_rate=0.1, max_depth=None, n_estimators=100, subsample=0.8; total time=   1.0s
[CV] END learning_rate=0.01, max_depth=250, n_estimators=200, subsample=0.8; total time=   5.2s
[CV] END learning_rate=0.1, max_depth=None, n_estimators=100, subsample=0.8; total time=   1.1s
[CV] END learning_rate=0.1, max_depth=None, n_estimators=100, subsample=0.8; total time=   1.0s
[CV] END learning_rate=0.01, max_depth=250, n_estimators=200, subsample=0.8; total time=   4.9s
[CV] END learning_rate=0.01, max_depth=250, n_estimators=200, subsample=0.8; total time=   4.6s
[CV] END learning_rate=0.1, max_depth=None, n_estimators=100, subsample=0.8; total time=   1.1s
[CV] END learning_rate=0.01, max_depth=250, n_estimators=200, subsample=0.8; total time=   4.8s
[CV] END learning_rate=0.1, max_depth=None, n_estimators=100, subsample=0.9; total time=   1.2s
[CV] END learning_rate=0.1, max_depth=None, n_estimators=100, subsample=0.9; total time=   1.2s
[CV] END learning_rate=0.01, max_depth=250, n_estimators=200, subsample=0.9; total time=   4.9s
[CV] END learning_rate=0.1, max_depth=None, n_estimators=100, subsample=0.9; total time=   1.3s
[CV] END learning_rate=0.01, max_depth=250, n_estimators=200, subsample=0.9; total time=   5.0s
[CV] END learning_rate=0.01, max_depth=250, n_estimators=200, subsample=0.9; total time=   5.2s
[CV] END learning_rate=0.01, max_depth=250, n_estimators=200, subsample=0.9; total time=   5.2s
[CV] END learning_rate=0.1, max_depth=None, n_estimators=100, subsample=0.9; total time=   1.1s
[CV] END learning_rate=0.01, max_depth=250, n_estimators=200, subsample=0.9; total time=   5.4s
[CV] END learning_rate=0.1, max_depth=None, n_estimators=100, subsample=0.9; total time=   1.2s
[CV] END learning_rate=0.1, max_depth=None, n_estimators=200, subsample=0.8; total time=   1.8s
[CV] END learning_rate=0.1, max_depth=None, n_estimators=200, subsample=0.8; total time=   2.0s
[CV] END learning_rate=0.1, max_depth=None, n_estimators=200, subsample=0.8; total time=   1.9s
[CV] END learning_rate=0.1, max_depth=None, n_estimators=200, subsample=0.8; total time=   2.0s
[CV] END learning_rate=0.1, max_depth=None, n_estimators=200, subsample=0.8; total time=   2.0s
[CV] END learning_rate=0.1, max_depth=None, n_estimators=200, subsample=0.9; total time=   1.8s
[CV] END learning_rate=0.1, max_depth=None, n_estimators=200, subsample=0.9; total time=   2.0s
[CV] END learning_rate=0.1, max_depth=None, n_estimators=200, subsample=0.9; total time=   2.1s
[CV] END learning_rate=0.1, max_depth=None, n_estimators=200, subsample=0.9; total time=   2.0s
[CV] END learning_rate=0.1, max_depth=250, n_estimators=100, subsample=0.8; total time=   1.9s
[CV] END learning_rate=0.1, max_depth=None, n_estimators=200, subsample=0.9; total time=   2.1s
[CV] END learning_rate=0.1, max_depth=250, n_estimators=100, subsample=0.8; total time=   1.7s
[CV] END learning_rate=0.1, max_depth=250, n_estimators=100, subsample=0.8; total time=   2.0s
[CV] END learning_rate=0.1, max_depth=250, n_estimators=100, subsample=0.8; total time=   2.1s
[CV] END learning_rate=0.1, max_depth=250, n_estimators=100, subsample=0.8; total time=   1.9s
[CV] END learning_rate=0.1, max_depth=250, n_estimators=100, subsample=0.9; total time=   2.0s
[CV] END learning_rate=0.1, max_depth=250, n_estimators=100, subsample=0.9; total time=   1.9s
[CV] END learning_rate=0.1, max_depth=250, n_estimators=100, subsample=0.9; total time=   2.1s
[CV] END learning_rate=0.1, max_depth=250, n_estimators=100, subsample=0.9; total time=   2.3s
[CV] END learning_rate=0.1, max_depth=250, n_estimators=100, subsample=0.9; total time=   2.1s
[CV] END learning_rate=0.3, max_depth=None, n_estimators=100, subsample=0.8; total time=   1.0s
[CV] END learning_rate=0.1, max_depth=250, n_estimators=200, subsample=0.8; total time=   3.1s
[CV] END learning_rate=0.1, max_depth=250, n_estimators=200, subsample=0.8; total time=   3.3s
[CV] END learning_rate=0.1, max_depth=250, n_estimators=200, subsample=0.8; total time=   3.1s
[CV] END learning_rate=0.1, max_depth=250, n_estimators=200, subsample=0.8; total time=   3.2s
[CV] END learning_rate=0.1, max_depth=250, n_estimators=200, subsample=0.8; total time=   3.2s
[CV] END learning_rate=0.3, max_depth=None, n_estimators=100, subsample=0.8; total time=   1.1s
[CV] END learning_rate=0.3, max_depth=None, n_estimators=100, subsample=0.8; total time=   1.1s
[CV] END learning_rate=0.1, max_depth=250, n_estimators=200, subsample=0.9; total time=   3.1s
[CV] END learning_rate=0.3, max_depth=None, n_estimators=100, subsample=0.8; total time=   1.1s
[CV] END learning_rate=0.3, max_depth=None, n_estimators=100, subsample=0.8; total time=   0.8s
[CV] END learning_rate=0.1, max_depth=250, n_estimators=200, subsample=0.9; total time=   3.3s
[CV] END learning_rate=0.1, max_depth=250, n_estimators=200, subsample=0.9; total time=   3.2s
[CV] END learning_rate=0.1, max_depth=250, n_estimators=200, subsample=0.9; total time=   3.4s
[CV] END learning_rate=0.3, max_depth=None, n_estimators=100, subsample=0.9; total time=   1.1s
[CV] END learning_rate=0.3, max_depth=None, n_estimators=100, subsample=0.9; total time=   1.1s
[CV] END learning_rate=0.1, max_depth=250, n_estimators=200, subsample=0.9; total time=   3.3s
[CV] END learning_rate=0.3, max_depth=None, n_estimators=100, subsample=0.9; total time=   1.0s
[CV] END learning_rate=0.3, max_depth=None, n_estimators=100, subsample=0.9; total time=   1.1s
[CV] END learning_rate=0.3, max_depth=None, n_estimators=100, subsample=0.9; total time=   1.1s
[CV] END learning_rate=0.3, max_depth=None, n_estimators=200, subsample=0.8; total time=   1.8s
[CV] END learning_rate=0.3, max_depth=None, n_estimators=200, subsample=0.8; total time=   1.8s
[CV] END learning_rate=0.3, max_depth=None, n_estimators=200, subsample=0.8; total time=   1.9s
[CV] END learning_rate=0.3, max_depth=None, n_estimators=200, subsample=0.8; total time=   1.7s
[CV] END learning_rate=0.3, max_depth=None, n_estimators=200, subsample=0.8; total time=   1.8s
[CV] END learning_rate=0.3, max_depth=250, n_estimators=100, subsample=0.8; total time=   1.5s
[CV] END learning_rate=0.3, max_depth=None, n_estimators=200, subsample=0.9; total time=   1.7s
[CV] END learning_rate=0.3, max_depth=None, n_estimators=200, subsample=0.9; total time=   1.8s
[CV] END learning_rate=0.3, max_depth=None, n_estimators=200, subsample=0.9; total time=   1.8s
[CV] END learning_rate=0.3, max_depth=None, n_estimators=200, subsample=0.9; total time=   1.9s
[CV] END learning_rate=0.3, max_depth=None, n_estimators=200, subsample=0.9; total time=   1.9s
[CV] END learning_rate=0.3, max_depth=250, n_estimators=100, subsample=0.8; total time=   1.5s
[CV] END learning_rate=0.3, max_depth=250, n_estimators=100, subsample=0.8; total time=   1.5s
[CV] END learning_rate=0.3, max_depth=250, n_estimators=100, subsample=0.8; total time=   1.4s
[CV] END learning_rate=0.3, max_depth=250, n_estimators=100, subsample=0.9; total time=   1.3s
[CV] END learning_rate=0.3, max_depth=250, n_estimators=100, subsample=0.8; total time=   1.5s
[CV] END learning_rate=0.3, max_depth=250, n_estimators=100, subsample=0.9; total time=   1.4s
[CV] END learning_rate=0.3, max_depth=250, n_estimators=100, subsample=0.9; total time=   1.6s
[CV] END learning_rate=0.3, max_depth=250, n_estimators=100, subsample=0.9; total time=   1.4s
[CV] END learning_rate=0.3, max_depth=250, n_estimators=100, subsample=0.9; total time=   1.5s
[CV] END learning_rate=0.3, max_depth=250, n_estimators=200, subsample=0.8; total time=   2.3s
[CV] END learning_rate=0.3, max_depth=250, n_estimators=200, subsample=0.8; total time=   2.4s
[CV] END learning_rate=0.3, max_depth=250, n_estimators=200, subsample=0.8; total time=   2.0s
[CV] END learning_rate=0.3, max_depth=250, n_estimators=200, subsample=0.8; total time=   2.1s
[CV] END learning_rate=0.3, max_depth=250, n_estimators=200, subsample=0.8; total time=   2.1s
[CV] END learning_rate=0.3, max_depth=250, n_estimators=200, subsample=0.9; total time=   1.9s
[CV] END learning_rate=0.3, max_depth=250, n_estimators=200, subsample=0.9; total time=   2.0s
[CV] END learning_rate=0.3, max_depth=250, n_estimators=200, subsample=0.9; total time=   2.1s
[CV] END learning_rate=0.3, max_depth=250, n_estimators=200, subsample=0.9; total time=   2.1s
[CV] END learning_rate=0.3, max_depth=250, n_estimators=200, subsample=0.9; total time=   1.9s

   mean_test_score                                                                             params
8         0.729185   {'learning_rate': 0.1, 'max_depth': None, 'n_estimators': 100, 'subsample': 0.8}
9         0.724082   {'learning_rate': 0.1, 'max_depth': None, 'n_estimators': 100, 'subsample': 0.9}
6         0.723231   {'learning_rate': 0.01, 'max_depth': 250, 'n_estimators': 200, 'subsample': 0.8}
7         0.718136   {'learning_rate': 0.01, 'max_depth': 250, 'n_estimators': 200, 'subsample': 0.9}
4         0.717285   {'learning_rate': 0.01, 'max_depth': 250, 'n_estimators': 100, 'subsample': 0.8}
5         0.717270   {'learning_rate': 0.01, 'max_depth': 250, 'n_estimators': 100, 'subsample': 0.9}
2         0.702038  {'learning_rate': 0.01, 'max_depth': None, 'n_estimators': 200, 'subsample': 0.8}
3         0.702030  {'learning_rate': 0.01, 'max_depth': None, 'n_estimators': 200, 'subsample': 0.9}
0         0.693556  {'learning_rate': 0.01, 'max_depth': None, 'n_estimators': 100, 'subsample': 0.8}
1         0.691846  {'learning_rate': 0.01, 'max_depth': None, 'n_estimators': 100, 'subsample': 0.9}

In [90]:
xgb = XGBClassifier(learning_rate=0.1, max_depth=None, n_estimators=100, subsample=0.8)
xgb.fit(x_train, xgb_y_train)
y_pred = xgb.predict(x_test)
print(classification_report(xgb_y_test , y_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00       100
           1       0.00      0.00      0.00       100
           2       0.00      0.00      0.00       100
           3       0.17      1.00      0.29       100
           4       0.00      0.00      0.00       100
           5       0.00      0.00      0.00       100

    accuracy                           0.17       600
   macro avg       0.03      0.17      0.05       600
weighted avg       0.03      0.17      0.05       600

In [91]:
question = 'What are different types of single level indexing?'
processed_q = preprocess_text(question)
tfidf_q = vectorizer.transform([processed_q])
tfidf_q = pd.DataFrame(tfidf_q.toarray(), columns=vectorizer.get_feature_names_out())



# Adding linguistic features
q_ling_features = pd.DataFrame([extract_linguistic_features(question)])

# Concatenate DataFrames
token_q = pd.concat([q_ling_features, tfidf_q], axis=1)
# token_q = token_q.drop(columns= ['blooms_verb_present'])

print(xgb.predict(tfidf_q))

[0]

### Linear SVM

In [92]:
params = {
    'penalty': ['l2'],
    'loss': ['squared_hinge' , 'hinge'],
    'dual': [True, False],
    'C': [0.1, 1, 10, 100]
}
param_search = GridSearchCV(estimator= LinearSVC(), param_grid= params, cv=5, n_jobs= -1, return_train_score=True, verbose= 2)

param_search.fit(x , y)

cv_results = pd.DataFrame(param_search.cv_results_)
cv_results = cv_results[["mean_test_score", "params"]].head(10).sort_values(by="mean_test_score", ascending=False)

cv_results

Fitting 5 folds for each of 16 candidates, totalling 80 fits
[CV] END ...C=0.1, dual=True, loss=squared_hinge, penalty=l2; total time=   0.0s
[CV] END ...C=0.1, dual=True, loss=squared_hinge, penalty=l2; total time=   0.0s
[CV] END ...C=0.1, dual=True, loss=squared_hinge, penalty=l2; total time=   0.0s
[CV] END ...C=0.1, dual=True, loss=squared_hinge, penalty=l2; total time=   0.0s
[CV] END ...C=0.1, dual=True, loss=squared_hinge, penalty=l2; total time=   0.0s
[CV] END ...........C=0.1, dual=True, loss=hinge, penalty=l2; total time=   0.0s
[CV] END ...........C=0.1, dual=True, loss=hinge, penalty=l2; total time=   0.0s
[CV] END ...........C=0.1, dual=True, loss=hinge, penalty=l2; total time=   0.0s
[CV] END ...........C=0.1, dual=True, loss=hinge, penalty=l2; total time=   0.0s
[CV] END ...........C=0.1, dual=True, loss=hinge, penalty=l2; total time=   0.0s
[CV] END ..C=0.1, dual=False, loss=squared_hinge, penalty=l2; total time=   0.0s
[CV] END ..C=0.1, dual=False, loss=squared_hinge, penalty=l2; total time=   0.0s
[CV] END ..C=0.1, dual=False, loss=squared_hinge, penalty=l2; total time=   0.0s
[CV] END ..C=0.1, dual=False, loss=squared_hinge, penalty=l2; total time=   0.0s
[CV] END ..C=0.1, dual=False, loss=squared_hinge, penalty=l2; total time=   0.0s
[CV] END ..........C=0.1, dual=False, loss=hinge, penalty=l2; total time=   0.0s
[CV] END ..........C=0.1, dual=False, loss=hinge, penalty=l2; total time=   0.0s
[CV] END ..........C=0.1, dual=False, loss=hinge, penalty=l2; total time=   0.0s
[CV] END ..........C=0.1, dual=False, loss=hinge, penalty=l2; total time=   0.0s
[CV] END ..........C=0.1, dual=False, loss=hinge, penalty=l2; total time=   0.0s
[CV] END .....C=1, dual=True, loss=squared_hinge, penalty=l2; total time=   0.1s
[CV] END .....C=1, dual=True, loss=squared_hinge, penalty=l2; total time=   0.0s
[CV] END .....C=1, dual=True, loss=squared_hinge, penalty=l2; total time=   0.0s
[CV] END .....C=1, dual=True, loss=squared_hinge, penalty=l2; total time=   0.1s
[CV] END .............C=1, dual=True, loss=hinge, penalty=l2; total time=   0.0s
[CV] END .....C=1, dual=True, loss=squared_hinge, penalty=l2; total time=   0.0s
[CV] END .............C=1, dual=True, loss=hinge, penalty=l2; total time=   0.0s
[CV] END ....C=1, dual=False, loss=squared_hinge, penalty=l2; total time=   0.0s
[CV] END .............C=1, dual=True, loss=hinge, penalty=l2; total time=   0.0s
[CV] END .............C=1, dual=True, loss=hinge, penalty=l2; total time=   0.0s

/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END ....C=1, dual=False, loss=squared_hinge, penalty=l2; total time=   0.0s
[CV] END .............C=1, dual=True, loss=hinge, penalty=l2; total time=   0.0s
[CV] END ....C=1, dual=False, loss=squared_hinge, penalty=l2; total time=   0.0s
[CV] END ....C=1, dual=False, loss=squared_hinge, penalty=l2; total time=   0.0s
[CV] END ............C=1, dual=False, loss=hinge, penalty=l2; total time=   0.0s
[CV] END ....C=1, dual=False, loss=squared_hinge, penalty=l2; total time=   0.0s
[CV] END ............C=1, dual=False, loss=hinge, penalty=l2; total time=   0.0s
[CV] END ............C=1, dual=False, loss=hinge, penalty=l2; total time=   0.0s
[CV] END ............C=1, dual=False, loss=hinge, penalty=l2; total time=   0.0s
[CV] END ............C=1, dual=False, loss=hinge, penalty=l2; total time=   0.0s
[CV] END ....C=10, dual=True, loss=squared_hinge, penalty=l2; total time=   0.1s
[CV] END ....C=10, dual=True, loss=squared_hinge, penalty=l2; total time=   0.1s
[CV] END ....C=10, dual=True, loss=squared_hinge, penalty=l2; total time=   0.1s
[CV] END ....C=10, dual=True, loss=squared_hinge, penalty=l2; total time=   0.0s
[CV] END ............C=10, dual=True, loss=hinge, penalty=l2; total time=   0.1s

/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END ............C=10, dual=True, loss=hinge, penalty=l2; total time=   0.1s
[CV] END ....C=10, dual=True, loss=squared_hinge, penalty=l2; total time=   0.1s
[CV] END ............C=10, dual=True, loss=hinge, penalty=l2; total time=   0.1s
[CV] END ...C=10, dual=False, loss=squared_hinge, penalty=l2; total time=   0.0s
[CV] END ............C=10, dual=True, loss=hinge, penalty=l2; total time=   0.1s
[CV] END ...C=10, dual=False, loss=squared_hinge, penalty=l2; total time=   0.0s
[CV] END ............C=10, dual=True, loss=hinge, penalty=l2; total time=   0.1s
[CV] END ...........C=10, dual=False, loss=hinge, penalty=l2; total time=   0.0s
[CV] END ...C=10, dual=False, loss=squared_hinge, penalty=l2; total time=   0.0s
[CV] END ...........C=10, dual=False, loss=hinge, penalty=l2; total time=   0.0s
[CV] END ...C=10, dual=False, loss=squared_hinge, penalty=l2; total time=   0.0s
[CV] END ...C=10, dual=False, loss=squared_hinge, penalty=l2; total time=   0.0s
[CV] END ...........C=10, dual=False, loss=hinge, penalty=l2; total time=   0.0s
[CV] END ...........C=10, dual=False, loss=hinge, penalty=l2; total time=   0.0s
[CV] END ...........C=10, dual=False, loss=hinge, penalty=l2; total time=   0.0s
[CV] END ...C=100, dual=True, loss=squared_hinge, penalty=l2; total time=   0.1s

/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END ...C=100, dual=True, loss=squared_hinge, penalty=l2; total time=   0.1s
[CV] END ...C=100, dual=True, loss=squared_hinge, penalty=l2; total time=   0.1s
[CV] END ...........C=100, dual=True, loss=hinge, penalty=l2; total time=   0.1s
[CV] END ...C=100, dual=True, loss=squared_hinge, penalty=l2; total time=   0.1s
[CV] END ...........C=100, dual=True, loss=hinge, penalty=l2; total time=   0.1s
[CV] END ...........C=100, dual=True, loss=hinge, penalty=l2; total time=   0.1s
[CV] END ...C=100, dual=True, loss=squared_hinge, penalty=l2; total time=   0.1s
[CV] END ...........C=100, dual=True, loss=hinge, penalty=l2; total time=   0.1s
[CV] END ...........C=100, dual=True, loss=hinge, penalty=l2; total time=   0.1s
[CV] END ..C=100, dual=False, loss=squared_hinge, penalty=l2; total time=   0.1s
[CV] END ..C=100, dual=False, loss=squared_hinge, penalty=l2; total time=   0.1s
[CV] END ..C=100, dual=False, loss=squared_hinge, penalty=l2; total time=   0.1s
[CV] END ..........C=100, dual=False, loss=hinge, penalty=l2; total time=   0.0s
[CV] END ..C=100, dual=False, loss=squared_hinge, penalty=l2; total time=   0.1s
[CV] END ..C=100, dual=False, loss=squared_hinge, penalty=l2; total time=   0.1s
[CV] END ..........C=100, dual=False, loss=hinge, penalty=l2; total time=   0.0s
[CV] END ..........C=100, dual=False, loss=hinge, penalty=l2; total time=   0.0s
[CV] END ..........C=100, dual=False, loss=hinge, penalty=l2; total time=   0.0s
[CV] END ..........C=100, dual=False, loss=hinge, penalty=l2; total time=   0.0s

   mean_test_score                                                               params
5         0.713916             {'C': 1, 'dual': True, 'loss': 'hinge', 'penalty': 'l2'}
4         0.713895     {'C': 1, 'dual': True, 'loss': 'squared_hinge', 'penalty': 'l2'}
6         0.713895    {'C': 1, 'dual': False, 'loss': 'squared_hinge', 'penalty': 'l2'}
0         0.710516   {'C': 0.1, 'dual': True, 'loss': 'squared_hinge', 'penalty': 'l2'}
2         0.710516  {'C': 0.1, 'dual': False, 'loss': 'squared_hinge', 'penalty': 'l2'}
1         0.704598           {'C': 0.1, 'dual': True, 'loss': 'hinge', 'penalty': 'l2'}
8         0.688381    {'C': 10, 'dual': True, 'loss': 'squared_hinge', 'penalty': 'l2'}
9         0.683285            {'C': 10, 'dual': True, 'loss': 'hinge', 'penalty': 'l2'}
3              NaN          {'C': 0.1, 'dual': False, 'loss': 'hinge', 'penalty': 'l2'}
7              NaN            {'C': 1, 'dual': False, 'loss': 'hinge', 'penalty': 'l2'}

In [93]:
lsvm = LinearSVC(C= 1, dual= True, loss= 'hinge', penalty= 'l2')
lsvm.fit(x_train, y_train)
y_pred = lsvm.predict(x_test)
print(classification_report(y_test , y_pred))

               precision    recall  f1-score   support

     analysis       0.64      0.65      0.64       100
  application       0.37      0.54      0.44       100
comprehension       0.49      0.64      0.56       100
   evaluation       0.69      0.43      0.53       100
    knowledge       0.52      0.47      0.49       100
    synthesis       0.59      0.40      0.48       100

     accuracy                           0.52       600
    macro avg       0.55      0.52      0.52       600
 weighted avg       0.55      0.52      0.52       600

In [94]:
question = 'What are different types of single level indexing?'
processed_q = preprocess_text(question)
tfidf_q = vectorizer.transform([processed_q])
tfidf_q = pd.DataFrame(tfidf_q.toarray(), columns=vectorizer.get_feature_names_out())



# Adding linguistic features
q_ling_features = pd.DataFrame([extract_linguistic_features(question)])

# Concatenate DataFrames
token_q = pd.concat([q_ling_features, tfidf_q], axis=1)

print(lsvm.predict(tfidf_q))

['analysis']

### Naive Bayes

In [95]:
params = {
    'alpha': [1e-1000,1e-500,1e-100, 1e-50,1e-20,1e-10,1e-06],
    'fit_prior': [True, False],
    'force_alpha': [True, False]
}
param_search = GridSearchCV(estimator= MultinomialNB(), param_grid= params, cv=5, n_jobs= -1)

param_search.fit(x, y)

cv_results = pd.DataFrame(param_search.cv_results_)
cv_results = cv_results[["mean_test_score", "params"]].head(10).sort_values(by="mean_test_score", ascending=False)

cv_results

/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:898: RuntimeWarning: divide by zero encountered in log
  self.feature_log_prob_ = np.log(smoothed_fc) - np.log(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:898: RuntimeWarning: divide by zero encountered in log
  self.feature_log_prob_ = np.log(smoothed_fc) - np.log(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:898: RuntimeWarning: divide by zero encountered in log
  self.feature_log_prob_ = np.log(smoothed_fc) - np.log(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:898: RuntimeWarning: divide by zero encountered in log
  self.feature_log_prob_ = np.log(smoothed_fc) - np.log(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:898: RuntimeWarning: divide by zero encountered in log
  self.feature_log_prob_ = np.log(smoothed_fc) - np.log(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:898: RuntimeWarning: divide by zero encountered in log
  self.feature_log_prob_ = np.log(smoothed_fc) - np.log(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:898: RuntimeWarning: divide by zero encountered in log
  self.feature_log_prob_ = np.log(smoothed_fc) - np.log(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:898: RuntimeWarning: divide by zero encountered in log
  self.feature_log_prob_ = np.log(smoothed_fc) - np.log(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:898: RuntimeWarning: divide by zero encountered in log
  self.feature_log_prob_ = np.log(smoothed_fc) - np.log(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:898: RuntimeWarning: divide by zero encountered in log
  self.feature_log_prob_ = np.log(smoothed_fc) - np.log(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:898: RuntimeWarning: divide by zero encountered in log
  self.feature_log_prob_ = np.log(smoothed_fc) - np.log(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:898: RuntimeWarning: divide by zero encountered in log
  self.feature_log_prob_ = np.log(smoothed_fc) - np.log(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:898: RuntimeWarning: divide by zero encountered in log
  self.feature_log_prob_ = np.log(smoothed_fc) - np.log(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:898: RuntimeWarning: divide by zero encountered in log
  self.feature_log_prob_ = np.log(smoothed_fc) - np.log(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:898: RuntimeWarning: divide by zero encountered in log
  self.feature_log_prob_ = np.log(smoothed_fc) - np.log(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:898: RuntimeWarning: divide by zero encountered in log
  self.feature_log_prob_ = np.log(smoothed_fc) - np.log(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:898: RuntimeWarning: divide by zero encountered in log
  self.feature_log_prob_ = np.log(smoothed_fc) - np.log(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:898: RuntimeWarning: divide by zero encountered in log
  self.feature_log_prob_ = np.log(smoothed_fc) - np.log(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:898: RuntimeWarning: divide by zero encountered in log
  self.feature_log_prob_ = np.log(smoothed_fc) - np.log(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:898: RuntimeWarning: divide by zero encountered in log
  self.feature_log_prob_ = np.log(smoothed_fc) - np.log(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/opt/anaconda3/envs/yt_env/lib/python3.10/site-packages/sklearn/naive_bayes.py:623: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(

   mean_test_score                                                      params
1         0.527811     {'alpha': 0.0, 'fit_prior': True, 'force_alpha': False}
5         0.527811     {'alpha': 0.0, 'fit_prior': True, 'force_alpha': False}
9         0.527811  {'alpha': 1e-100, 'fit_prior': True, 'force_alpha': False}
3         0.524418    {'alpha': 0.0, 'fit_prior': False, 'force_alpha': False}
7         0.524418    {'alpha': 0.0, 'fit_prior': False, 'force_alpha': False}
8         0.507425   {'alpha': 1e-100, 'fit_prior': True, 'force_alpha': True}
0         0.153649      {'alpha': 0.0, 'fit_prior': True, 'force_alpha': True}
2         0.153649     {'alpha': 0.0, 'fit_prior': False, 'force_alpha': True}
4         0.153649      {'alpha': 0.0, 'fit_prior': True, 'force_alpha': True}
6         0.153649     {'alpha': 0.0, 'fit_prior': False, 'force_alpha': True}

In [96]:
nb = MultinomialNB(alpha= 0.0, fit_prior= True, force_alpha= False)
nb.fit(x_train, y_train)
y_pred = nb.predict(x_test)
print(classification_report(y_test , y_pred))

               precision    recall  f1-score   support

     analysis       0.55      0.47      0.51       100
  application       0.33      0.40      0.36       100
comprehension       0.36      0.60      0.45       100
   evaluation       0.60      0.44      0.51       100
    knowledge       0.55      0.23      0.32       100
    synthesis       0.49      0.55      0.52       100

     accuracy                           0.45       600
    macro avg       0.48      0.45      0.44       600
 weighted avg       0.48      0.45      0.44       600

In [97]:
question = 'What are different types of single level indexing?'
processed_q = preprocess_text(question)
tfidf_q = vectorizer.transform([processed_q])
tfidf_q = pd.DataFrame(tfidf_q.toarray(), columns=vectorizer.get_feature_names_out())



# Adding linguistic features
q_ling_features = pd.DataFrame([extract_linguistic_features(question)])

# Concatenate DataFrames
token_q = pd.concat([q_ling_features, tfidf_q], axis=1)

print(nb.predict(tfidf_q))

['analysis']